### ISSUE TITLE
crash in header export involving function pointers

### ISSUE THREAD

**Issue by caughtbyatoe** [ispc/ispc#1005]
I consistently hit assertions when exporting structs from ispc that have function pointers. 

*repro*
typedef void (*FuncPtr)();

struct Functions
{
    FuncPtr fn;
};

export
void init(const uniform Functions * uniform funcs)
{
}

$> ispc test.ispc -h test_ispc.h

module.cpp:1651: Assertion failed: "CastType<AtomicType>(type) != NULL".
***
*** Please file a bug report at https://github.com/ispc/ispc/issues
*** (Including as much information as you can about how to reproduce this error).
*** You have apparently encountered a bug in the compiler that we'd like to fix!
***
main.cpp(226): FATAL ERROR: Unhandled signal sent to process; terminating.
Abort (core dumped)

*version*
$> ispc -v
Intel(r) SPMD Program Compiler (ispc), 1.8.1 (build commit c2016af1623c535a @ 20141231, LLVM 3.5)

**Comment by Vsevolod-Livinskij** [comment]
Bug was fixed in https://github.com/ispc/ispc/commit/637a4cc812aec0c5210973d0ffbc989b207c3a12.

**Comment by dbabokin** [comment]
So it's fixed in trunk, will show up in next binary release.
