### ISSUE TITLE
ISPC generated code crashes on XGETBV with disabled Windows AVX support

### ISSUE THREAD

**Issue by Novum** [ispc/ispc#1026]
If I disable AVX on Windows via "bcdedit /set xsavedisable 1" I get a crash in the generated code (with multiple targets) on the XGETBV instruction.

**Comment by Novum** [comment]
Seems like you are not checking for CPUID.1:ECX.OSXSAVE[bit 27]

**Comment by dbabokin** [comment]
What version of ispc are you using?

**Comment by Novum** [comment]
ISPC 1.8.1

**Comment by Novum** [comment]
if ((info[2] & (1 << 28)) != 0 &&
         __os_has_avx_support()) {  // AVX

I think this should also check for info[2] & (1 << 27)

**Comment by Novum** [comment]
This is also in the official Intel docu btw:
https://software.intel.com/en-us/articles/introduction-to-intel-advanced-vector-extensions

1. Verify that the operating system supports XGETBV using CPUID.1:ECX.OSXSAVE bit 27 = 1.

**Comment by dbabokin** [comment]
Agree, this is check is needed.
