### ISSUE TITLE
__floor_varying_double is undefined when compiling for Phi

### ISSUE THREAD

**Issue by BenWibking** [ispc/ispc#1037]
I cannot compile the --target=generic-16 output with ispc due to the following error:

icpc -O3 -mmic -I/nfs/03/osu8973/ispc-v1.8.1-linux/examples/intrinsics/ objs/transport_kernels_ispc.cpp -o objs/transport_kernels_MIC.o 
objs/transport_kernels_ispc.cpp(300): error: identifier "__floor_varying_double" is undefined
    calltmp_2e_i_2e_i_ =  /*tail*/ __floor_varying_double((__div(ix_load_to_double_, ngrid_x_load_to_double_smear_)));

Am I doing something wrong, or is this a bug?

[I also get this warning when compiling to *.cpp with ispc, but it is perhaps not related:
ispc --arch=x86-64 --emit-c++ --target=generic-16 --c++-include-file=knc.h transport_kernels.ispc -o objs/transport_kernels_ispc.cpp -h objs/transport_kernels_ispc.h
Warning: Module DataLayout is incompatible with library DataLayout: 
        Module DL: e-i64:64-f80:128-v16:16-v32:32-v4:128-n8:16:32:64-S128 
        Library DL: e-m:e-i64:64-f80:128-n8:16:32:64-S128 
]

**Comment by BenWibking** [comment]
Hmm, it looks like __floor_varying_double is indeed missing from knc.h.  __floor_varying_float is present.  Can anyone supply the missing intrinsic?  It is crucial for my application.

**Comment by Vsevolod-Livinskij** [comment]
This warning had been fixed in #940

**Comment by dbabokin** [comment]
Fixed by #1038. You can download knc.h from git and use it with ispc v1.8.1.
