### ISSUE TITLE
Problem indexing very large array

### ISSUE THREAD

**Issue by GregAbram** [ispc/ispc#1055]
I have code that iterates through the 2048 planes of a 2048 ^ 3 array initializing the first  element in each. I calculate the offset of each plane as size_t's.   If I do:

buf[off] = off;

I get a segfault.  If I 

float *p = buf + off;
*p = off;

all is well.   Here's by bug.c, followed by my bug.ispc and Makefile
--------------------------------------------------
xport void bug(uniform float buf[], uniform size_t np)
{
  foreach (i = 0 ... 2047)
  {
    size_t off = ((size_t)i) * 2048 * 2048;
#if 0
    float *p = buf + off;
    *p = off;
#else
    buf[off] = i;
#endif
  }
}
------------------------------------------------------
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <iostream>

#include "bug_ispc.h"

using namespace std;

int main(int argc, char *argv[])
{
  size_t xsz = 2048, ysz = 2048, zsz = 2048;

  size_t np = xsz*ysz*zsz;
  float *scalars = new float[np];

  ispc::bug(scalars, np);
  std::cerr << "done\n";
}
----------------------------------------------------
ISPC=/work/01249/gda/maverick/ispc-v1.8.2-linux/ispc
CXX=g++ -g

all: bug

bug:  bug.io
  ${CXX} -o bug bug.cpp bug.io 

bug.io: bug.ispc
  ${ISPC} --arch=x86-64 --pic -O3 --woff --target=avx --addressing=64 \
          --cpu=corei7-avx --opt=fast-math \
          -h bug_ispc.h -MMM bug_dev.idep -o bug.io bug.ispc

%.o : %.cpp
  ${CXX} ${INCDIRS} -fPIC -DDEBUG -g -fPIC -c -o $*.o $*.cpp

bug.o : bug_ispc.h

clean: ; rm -rf *.io *.o *.idep *_ispc.h bug

**Comment by dbabokin** [comment]
Posting source code here seems like bad idea. Gist (see the link on top of the page should be better alternative).

**Comment by GregAbram** [comment]
Learn something new every day.   GregAbram / gist:f17c6c7d8f36ab581289

**Comment by dbabokin** [comment]
Clickable link:
https://gist.github.com/f17c6c7d8f36ab581289

**Comment by dbabokin** [comment]
Fixed by #1056
