### ISSUE TITLE
ispc 1.8.2 crash in cast to int of pass by reference float arg

### ISSUE THREAD

**Issue by mauricevanswaaij** [ispc/ispc#1068]
Found the crash below, thanks in advance for looking.

```
void
test (const float & b)
{
	int bb = (int)b;
}
```
crashes with
 
trans.ispc:16:11: Error: Assertion failed (expr.cpp:7043): "fromAtomic != NULL". 
	int bb = (int)b;
          ^^^^^^

***
*** Please file a bug report at https://github.com/ispc/ispc/issues
*** (Including as much information as you can about how to reproduce this error).
*** You have apparently encountered a bug in the compiler that we'd like to fix!
***
main.cpp(232): FATAL ERROR: Unhandled signal sent to process; terminating.

**Comment by mauricevanswaaij** [comment]
I should have added that when 'b' is passed by value, it's fine

**Comment by dbabokin** [comment]
Fixed. Thanks for reporting.
