### ISSUE TITLE
ispc 1.8.2 (linux version) crashes after reporting syntax and other errors

### ISSUE THREAD

**Issue by mauricevanswaaij** [ispc/ispc#1071]
Hi, it seems that 1.8.2 (linux version) always crashes after reporting an error, unlike ispc 1.8.1.
I added an example below, but it doesn't seem to matter what the error is.

Thanks

```
export uniform float test (uniform float a)
{
    return a *
}
```

trans.ispc:14:1: Error: syntax error, unexpected '}'. 
}
^

main.cpp(232): FATAL ERROR: Unhandled signal sent to process; terminating.

---

**\* Please file a bug report at https://github.com/ispc/ispc/issues
**\* (Including as much information as you can about how to reproduce this error).
**\* You have apparently encountered a bug in the compiler that we'd like to fix!

---

**Comment by nurmukhametov** [comment]
Fixed since at least 1.9.1. Test is added by #2636
