### ISSUE TITLE
Does not properly handle char arrays, whereas int arrays are fine.

### ISSUE THREAD

**Issue by stolk** [ispc/ispc#1080]
This is with precompiled ispc 1.8.2 on linux.

The compiler does not like char arrays, where as int arrays are fine.

cost2pot/cost2pot_ispc.c:135:25: Warning: No type specified in declaration.
        Assuming int32.
        uniform const unsigned char cell[],^M

Using uniform const int cell[] works, but the char will make the compilation stop.

**Comment by dbabokin** [comment]
Sorry for late reply, ISPC supports 8, 16, 32 and 64 bit ints. They may be referred to as int8, int16, int (and also as int32) and int64.

There's no such type as "char" in ISPC. Actually, "char" is a bit overloaded thing in C standard, so getting rid of it is simplifying some things. For example, in C "signed char", "char" and "unsigned char" are 3 distinct types from language stand point (it's not true for integers).
