### ISSUE TITLE
negative pow in ispc 1.8.2 on osx 10.10.5

### ISSUE THREAD

**Issue by jnises** [ispc/ispc#1099]
Running the following code on my machine (early 2015 mbp running osx yosemite):
bug.ispc

``` c
export uniform float bug()
{
    return pow(-1.f, 2.f);
}
```

main.c

``` c
#include <stdio.h>
#include "bug.h"

int main(int argc, char *argv[])
{
    printf("%f\n", bug());
    return 0;
}
```

Makefile

``` Makefile
all: main

bug.o: bug.ispc Makefile
    ispc bug.ispc -o bug.o -h bug.h --target=avx2-i32x8 --arch=x86-64 #--math-lib=system

main.o: main.c bug.h bug.ispc Makefile
    clang -c main.c

main: main.o bug.o
    clang -o main main.o bug.o
```

Results in the printout 0.00000

If I switch to --math-lib=system I get the expected printout 1.000000

This is with the ispc version downloaded from http://sourceforge.net/projects/ispcmirror/files/v1.8.2/ispc-v1.8.2-osx.tar.gz/download

**Comment by dbabokin** [comment]
By default we use approximation pow(a,b) = exp(b * log(a)), which doesn't work for negative base.

We should probably fall back to system library if the base is negative.
