### ISSUE TITLE
1.8.2-r1 : builtins.cpp:794:86: error: conversion from ‘llvm::ErrorOr<std::unique_ptr<llvm::Module> >’ to non-scalar type ‘llvm::ErrorOr<llvm::Module*>’ requested

### ISSUE THREAD

**Issue by toralf** [ispc/ispc#1106]
origin is in https://bugs.gentoo.org/show_bug.cgi?id=562630 :: 

x86_64-pc-linux-gnu-g++ -march=native -O2 -pipe -I/usr/include    -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I. -Iobjs/ -I/usr/include -DLLVM_3_7 -Wall -DBUILD_DATE="\"20151009\"" -DBUILD_VERSION="\""no_version_info"\"" -Wno-sign-compare -Wno-unused-function -Werror -std=c++11 -Wno-c99-extensions -Wno-deprecated-register -o objs/builtins.o -c builtins.cpp
builtins.cpp: In function ‘void AddBitcodeToModule(const unsigned char*, int, llvm::Module*, SymbolTable*, bool)’:
builtins.cpp:794:86: error: conversion from ‘llvm::ErrorOr<std::unique_ptr<llvm::Module> >’ to non-scalar type ‘llvm::ErrorOr<llvm::Module*>’ requested
 ::ErrorOr<llvm::Module *> ModuleOrErr = llvm::parseBitcodeFile(bcBuf, *g->ctx);

**Comment by dbabokin** [comment]
What gcc version is it?
What ISPC source code revision is it?
What makefile is used to build it? (from the logs I can conclude that it's some customized file, not really our Makefile).
What LLVM version is in PATH and how it was built? Is it pre-built binaries from the llvm.org or manually built version? (what were the switches to configure and build it).

**Comment by toralf** [comment]
gcc-4.8.5, glibc-2.21-r1
dev-lang/ispc-1.8.2-r1 
llvm 3.7.0-r1

and b/c it is Gentoo - all is build from source (using the ebuild from Gentoo):

tor-relay / # emerge --info llvm
Portage 2.2.23 (python 3.4.3-final-0, default/linux/amd64/13.0/desktop, gcc-4.8.5, glibc-2.21-r1, 4.2.3-hardened-r1 x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-4.2.3-hardened-r1-x86_64-Intel-R-_Core-TM-_i7-3770_CPU_@_3.40GHz-with-gentoo-2.2
KiB Mem:    16166720 total,    580400 free
KiB Swap:          0 total,         0 free
Timestamp of repository gentoo: Mon, 12 Oct 2015 13:45:01 +0000
sh bash 4.3_p42
ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
ccache version 3.2.4 [disabled]
app-shells/bash:          4.3_p42::gentoo
dev-java/java-config:     2.2.0::gentoo
dev-lang/perl:            5.22.0::gentoo
dev-lang/python:          2.7.10::gentoo, 3.4.3::gentoo
dev-util/ccache:          3.2.4::gentoo
dev-util/cmake:           3.3.2-r1::gentoo
dev-util/pkgconfig:       0.29::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.18::gentoo
sys-apps/sandbox:         2.9::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69-r1::gentoo
sys-devel/automake:       1.9.6-r4::gentoo, 1.10.3-r1::gentoo, 1.11.6-r1::gentoo, 1.12.6::gentoo, 1.13.4::gentoo, 1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            4.8.5::gentoo, 4.9.3::gentoo
sys-devel/gcc-config:     1.8::gentoo
sys-devel/libtool:        2.4.6-r1::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 4.2::gentoo (virtual/os-headers)
sys-libs/glibc:           2.21-r1::gentoo
Repositories:

local
    location: /usr/local/portage
    masters: gentoo

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: 9999

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /etc/stunnel/stunnel.conf /usr/lib64/fax /usr/share/config /usr/share/gnupg/qualified.txt /usr/share/themes/oxygen-gtk/gtk-2.0 /var/lib/hsqldb /var/spool/fax/etc /var/yp/Makefile"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-march=native -O2 -pipe"
DISTDIR="/var/tmp/distfiles"
EMERGE_DEFAULT_OPTS="--color=n --nospinner --tree --quiet-build --accept-properties=-interactive --accept-restrict=-fetch"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://ftp.uni-erlangen.de/pub/mirrors/gentoo rsync://mirror.netcologne.de/gentoo/ ftp://sunsite.informatik.rwth-aachen.de/pub/Linux/gor.bytemark.co.uk/gentoo/ rsync://ftp.snt.utwente.nl/gentoo"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j1"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac acl acpi aes-ni alsa amd64 berkdb bindist bluetooth branding bzip2 cairo cdda cdr cgoups clang cli consolekit cracklib crypt cups curl custom-cflags custom-optimization cxx dbus designer dot dri drmkms dts dvd dvdr emboss encode exif extraengine fam ffmpeg firefox flac fortran fpm gdbm gif git glamor gpm gtk hdf5 iconv imap imlib inifile ipv6 javascript jpeg kerberos kvm lcms ldap libnotify libvirtd logrotate mad mbox mmx mmxext mng mod modules mp3 mp4 mpeg mssql multilib multimedia multitarget mysqli ncurses nls nptl obj objc ogg opengl openmp openmpi pam pango pax_kernel pcre pdf pdo png policykit postgres postscript ppds pwquality qemu qml qt3support qt4 readline scrypt sddm sdl seccomp session spell spice sqlite3 sse sse2 ssl ssse3 startup-notification svg system-cairo system-icu system-jpeg tcpd theora thinkpad tiff truetype udev udisks unicode upower usb usbredir uxa v4l v4l2 vorbis webkit wxwidgets x264 xcb xml xv xvfb xvid xvmc zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="keyboard mouse evdev" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LINGUAS="en en_GB" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-5" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_4" RUBY_TARGETS="ruby20 ruby21" USERLAND="GNU" VIDEO_CARDS="fbdev glint intel mach64 mga nouveau nv r128 radeon savage sis tdfx trident vesa via vmware dummy v4l" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON

=================================================================
                        Package Settings
=================================================================

sys-devel/llvm-3.7.0-r1::gentoo was built with the following:
USE="clang libffi multitarget ncurses static-analyzer xml -debug -doc -gold -libedit -lldb -ocaml -python -test" ABI_X86="64 -32 -x32" PYTHON_TARGETS="python2_7 -pypy" VIDEO_CARDS="radeon"

**Comment by dbabokin** [comment]
I'm not familiar with Gentoo internals, so I'm not sure what dev-lang/ispc-1.8.2-r1 means. I.e. what git revision it's based on? What makefile is used for the build?

**Comment by junghans** [comment]
Gentoo uses ispc-1.8.2 the `r1` is just a Gentoo-internal revision bump due to #1096.
We use the default bundle Makefile and use the following command to build ispc:
```
make -j1 'LDFLAGS=-Wl,-O1 -Wl,--as-needed' 'OPT=-march=native -O2 -pipe' CXX=x86_64-pc-linux-gnu-g++ CPP=x86_64-pc-linux-gnu-cpp 
```

**Comment by dbabokin** [comment]
Please use the version of the code from ispc trunk for function
void AddBitcodeToModule(const unsigned char *bitcode, int length, llvm::Module *module, SymbolTable *symbolTable, bool warn);

file builtins.cpp, line 792: https://github.com/ispc/ispc/blob/master/builtins.cpp#L792

At the time of 1.8.2 branching, LLVM 3.7 was not yet released, so this problem did not exist.

Alternative solution is to use LLVM 3.6, which is also reasonably new for ISPC 1.8.2.

**Comment by dbabokin** [comment]
Also note that in ISPC trunk ISPC_* macros are defined differently - you just need to port line 792-796 from builtins.cpp to fix the problem.

**Comment by dbabokin** [comment]
At the time of ISPC 1.8.2, LLVM 3.7 was not released. I see 2 bugs preventing compiling with LLVM 3.7:
- the bug in this issue - it needs line from 792-796 from builtins.cpp from master to be backported to v1.8.2;
- commits 26a93bc, 8217448 and 9f083f9 need to be applied to v1.8.2.

I think the easiest way to solve the problem, is to use LLVm 3.6, which is also reasonably new for 1.8.2.

**Comment by junghans** [comment]
I really don't want to patch more than two think into the Gentoo package.

Couldn't you just make a new release?

**Comment by dbabokin** [comment]
We'll do new release some time soon the most likely, but not right now.

Why not building with LLVM 3.6?

**Comment by junghans** [comment]
Gentoo Linux system now come with llvm-3.7 and we cannot hold back that package update due to ispc.

**Comment by dbabokin** [comment]
In this case applying the patches I've mentioned is perfectly fine and
looks like is the best thing we can do now. I can send you the patch with
required changes over email if needed.

Current trunk has too many regressions to release right now.

**Comment by junghans** [comment]
I blocked the build with llvm-3.7 for now! Please mail me a patch and I can bump it again!

**Comment by dbabokin** [comment]
I failed to located your email. Here's the patch: https://goo.gl/GXcCiR

Let me know if you have any other issues.

**Comment by junghans** [comment]
@toralf : Can you test that patch?

**Comment by junghans** [comment]
Done, this issue can be closed now!
