### ISSUE TITLE
Default system target warning

### ISSUE THREAD

**Issue by damiendr** [ispc/ispc#1122]
I'm calling `ispc` from a Julia tool: https://github.com/damiendr/ISPC.jl and I'd like to get rid of the warning:
```
Warning: No --target specified on command-line. Using default system target
        "avx1-i32x8".
```
but preserve any performance warnings.

It would be nice to have a way to detect the default target or to set `--target=default` so that the warning can be avoided while keeping the code cross-platform.

**Comment by dbabokin** [comment]
I think that's it's very valid request, though I think it should be "host", not "default".

We'll add it.

**Comment by dbabokin** [comment]
--target=host was added.
