### ISSUE TITLE
ISPC compiler asserts when performing a bad assignment to an struct member with an enum

### ISSUE THREAD

**Issue by Twinklebear** [ispc/ispc#1208]
When trying to do some C-style polymorphism using an enum to identify the different child types to cast to them I encountered a crash in the compiler, triggered by the following code:

``` c
enum Identifier {
    ID_A
};
struct Base {
    Identifier type;
};
struct Child {
    Base base;
};
void bug_reproduction(){
    Child child;
    child.base = ID_A;
}
```

Compiling this causes the compiler to abort with the following error:

```
./bad_assign_repro.ispc:15:15: Error: Assertion failed (expr.cpp:543): "toAtomicType != NULL || toVectorType != NULL".
        child.base = ID_A;
              ^^^^
```

Interestingly the compiler does give a type conversion error if instead of assigning `ID_A` we assign 0 or if the type member in Base is an int and we assign 0. Just the assignment of the enum seems to trigger this bug (also triggers if type is an int and we assign `ID_A`)

**Comment by dbabokin** [comment]
For current version (v1.17.0) compiler reports the following (which is correct):
```
Error: Type conversion from "const uniform enum 
        Identifier" to "varying struct Base" for assignment operator is not 
        possible. 
    child.base = ID_A;
                 ^^^^
```

If assignment is modified as
```c
    child.base.type = ID_A;
```

it compiles well. Proof: https://godbolt.org/z/zs9GEa6Ez
