### ISSUE TITLE
ISPC gave a warning while ICC did not

### ISSUE THREAD

**Issue by shengfu** [ispc/ispc#1213]
I got a warning with the following code:
 Warning: Function parameter "vec" shadows a 
        function declared in global scope. 

However, ICC is fine. Is it what we should expect?

void vec(int x)
{
    print("vec says x is %d\n", x);
}

void run(int vec)
{
    print("run says vec is %d\n", vec);
}

int main()
{
    run(1);
    vec(2);
}

**Comment by dbabokin** [comment]
Warning is valid.

Modify your C/C++ example like this:
void run(int vec)
{
    vec(5); // <<-- this will cause an error.
    printf("run says vec is %d\n", vec);
}
