### ISSUE TITLE
ISPC compiler asserts when compiling for generic CPU target with -O0

### ISSUE THREAD

**Issue by Twinklebear** [ispc/ispc#1223]
When compiling with `ispc -O0 --cpu=generic` the compiler fails an assert with the following message:

```
llvmutil.cpp:1560: Assertion failed: "llvm::isa<llvm::Instruction>(v) == true".
```

**Comment by dbabokin** [comment]
Generic targets were deprecated, so it's not an issue anymore. Closing.
