### ISSUE TITLE
Error compiling on arm

### ISSUE THREAD

**Issue by awiegersma** [ispc/ispc#1232]
I'm trying to compile ispc on a Raspberry Pi (Raspbian). In the Makefile I have set ARM_ENABLED=1. When compiling ispc I get

LLVM from $LLVM_HOME is used.
Updating dependencies
Using LLVM 3.8.1 from /home/user/development/image_processing/libraries/llvm/bin-3.8/lib
Using compiler to build: clang version 3.8.1 (tags/RELEASE_381/final 284390)
Creating objs/ directory
Compiling ast.cpp
error: unable to create target: 'No available targets are compatible with this
      triple, see -version for the available targets.'
1 error generated.
Makefile:286: recipe for target 'objs/ast.o' failed
make: *** [objs/ast.o] Error 1

I've searched on the internet for this error message but nothing came up. Any ideas?

**Comment by dbabokin** [comment]
LLVM that you have built doesn't have ARM target support.
alloy.py by default doesn't build ARM target. Add ARM to the enabled targets, grep in alloy.py for "--enable-targets=x86,x86_64,nvptx"

**Comment by awiegersma** [comment]
Thanks for your reply. Unfortunately adding arm to the enabled targets in alloy.py did not work. I did manage to compile ispc on Raspbian by using llvm 3.9.0.

On a Raspberry 2 when running the raytracing example I get a 1.4x speedup from ISPC and a 5.6x speedup from ISPC + tasks so it seems to work.
