### ISSUE TITLE
Varying parameter "rx" is illegal in an exported function.

### ISSUE THREAD

**Issue by lowkey9** [ispc/ispc#1240]
Linux 16.04 x86_64

ERROR:
Varying parameter "rx" is illegal in an exported function. export void nm(uniform int N, double &rx, double &ry)
Trying to index into non-array, vector, or pointer type "varying double &". q = (p*p + rx[index]) / (2.0 * p);
Assertion failed (expr.cpp:4330):  "sequentialType != NULL". q = (p*p + rx[index]) / (2.0 * p);

nm.cpp:
double *x = new double[SIZE];
double *y = new double[SIZE];
nm(SIZE, x, y);

nm.ispc:
export void nm(uniform int N, double &rx, double &ry)
{
	foreach(index = 0 ... N){
		double p = *(rx+index);
		double q = 0.0;
		while(1){
			q = (p*p + rx[index]) / (2.0 * p);
			if(abs(p-q)>=0.0001)
				p = q;
			else{
				ry[index] = q;
				break;
			}
		}
	}
}

makefile:
CXX=g++
CXXFLAGS=-I. -Wall -g -std=c++11
ISPC=ispc
ISPCFLAGS=--arch=x86-64 --target=sse2

default: nmsqrt

.PHONY: clean
.PRECIOUS: nm_ispc.h

clean:
	/bin/rm -rf objs *~ nmsqrt

nmsqrt: nm.o nm_ispc.o
	$(CXX) $(CXXFLAGS) -o $@ nm.o nm_ispc.o

nm.o: nm.cpp nm_ispc.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<

%_ispc.h %_ispc.o: %.ispc
	$(ISPC) $(ISPCFLAGS) $< -o $*_ispc.o -h $*_ispc.h

**Comment by jbrodman** [comment]
This is illegal for ABI reasons.  If you really really want a varying,
uniform pointers to varying *are* allowed, but it's up to you to properly
size things on the other side.

**Comment by lowkey9** [comment]
Thank you for your quick reply. Problem was solved.
