### ISSUE TITLE
Hexadecimal float constants and double types

### ISSUE THREAD

**Issue by damiendr** [ispc/ispc#1241]
It seems that hexadecimal floating-points literals are always parsed as floats, never doubles -- even when the literal has more digits than a float can handle. Is `doublebits()` the best way to type in a bit-accurate double literal?

The manual also has the following example:
```c
float pi  = 0x1.921fb54442d18p+1;  // 3.1415926535...
```
but that's too many hex digits for a 32-bit float, so the statement "this form can ensure a perfectly bit-accurate representation of a particular floating-point number" could be slightly misleading here.

Demonstration:
```c
export uniform double x() {
    return 0x1.921fb54442d18p+1;
}
export uniform double y() {
    return doublebits(0x400921fb54442d18);
}
```
```cpp
int main() {
        printf("%a %a\n", ispc::x(), ispc::y());
        return 0;
}
```
```
$ ./main
0x1.921fb6p+1 0x1.921fb54442d18p+1
```

**Comment by dbabokin** [comment]
The way to use hexadecimal floating-point types with double is to add `d` or `D` suffix. In 1.17.0 this part of documentation was cleaned up and extended: https://ispc.github.io/ispc.html#floating-point-literals

For example:
```c
export uniform double x() {
    return 0x1.921fb54442d18p+1d;
}
```

But looking at the updated version of the docs I see that I missed `d` suffix for hexadecimal example for doubles 🤦🏻‍♂️ Will fix the docs and close the issue.

Also, [this test](https://github.com/ispc/ispc/blob/main/tests/lit-tests/float_literals_value.ispc) contains all the examples of spelling floating point numbers.
