### ISSUE TITLE
generic_defs.h included in .cpp from ISPC, but missing

### ISSUE THREAD

**Issue by elchtest** [ispc/ispc#1252]
Compiled file like that:

ispc example.ispc --emit-c++ --target=generic-x8 -o foo.cpp

In the created cpp file it wants to include this:
**#include "generic_defs.h"**

which is not to be found anywhere. I also looked inside the ISPC source, but could only find generic-16.h, generic-32.h, generic-64.h. Trying to include one of these instead reveals more errors:
1>foo.cpp(38): error : more than one instance of overloaded function "memcpy" has "C" linkage
1>    uint8_t *memcpy(uint8_t *, uint8_t *, uint64_t );

1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cmath(278): error : expected a ")"
1>    _Check_return_ inline float round(_In_ float _Xx) _NOEXCEPT
...

Using MSVC 2015, Update 3.

**Comment by dbabokin** [comment]
``generic_defs.h`` should be provided by user. We provide several reference implementations available in [examples/intrinsics](https://github.com/ispc/ispc/tree/master/examples/intrinsics).

You need to use ``--c++-include-file=<file>`` to point to something other than ``generic_defs.h``.

Note that generic targets are not maintained currently and contain multiple known issues.
