### ISSUE TITLE
--no-stdlib seems to be broken on windows in 1.9.1

### ISSUE THREAD

**Issue by jamesrburgess** [ispc/ispc#1258]
Trying to work around the Windows multiple defined symbols for things like __math_lib_ispc in 1.9.1 (this issue https://github.com/ispc/ispc/issues/1233) I tried --no-stdlib. ispc just bails with a non-zero exit and does nothing if I used that flag. No error is printed.

Cheers,
- James

**Comment by dbabokin** [comment]
I've tried it with single and multiple targets and it works just fine. I'm using 1.9.1 release binaries.

**Comment by dbabokin** [comment]
--nostdlib make stdlib.ispc not to link, but bunch of constants are stilled added, as well as bitcode part of stdlib.
