### ISSUE TITLE
Compiling on ppc64le

### ISSUE THREAD

**Issue by maedoc** [ispc/ispc#1261]
I'd like to use ISPC on ppc64le, and I've managed to do this, sort of, using the generic-16 target, but it requires running ISPC on an x86 system first, and then compiling the result on the target system.  That only works with Clang but it's fairly slow; GCC barfs on the generated C++, and xlc++ segfaults.

I noticed that `ispc.cpp` has a bunch x86 specific ASM for cpuid.  Can this be outsourced to a library like libhwloc?

Even if ISPC wouldn't work well for ppc64le, it would be nice to be able to use the NVPTX backend on the ppc64le architecture.

_edit_ I'm not saying you guys should do this, but rather asking if it would be possible to patch ISPC w/ some small effort to get it running on ppc64le?

**Comment by dbabokin** [comment]
Does LLVM fully support ppc64le? If so, it's better to build a ppc64le native target for ispc.

**Comment by dbabokin** [comment]
We have removed `generic-*` targets, as they are difficult to maintain and doesn't bring much value. So this route is not usable anymore for ppc64le port. If anyone decides to implement ppc64le port, we should explore native target option.
