### ISSUE TITLE
Compiler crash/Bug report requested by compiler

### ISSUE THREAD

**Issue by peterhuba** [ispc/ispc#1271]
Compiler output:
> ispc: /export/users/dybaboki/llvm/llvm-3.8/lib/IR/Instructions.cpp:1832: void llvm::InsertValueInst::init(llvm::Value *, llvm::Value *, ArrayRef<unsigned int>, const llvm::Twine &): Assertion `ExtractValueInst::getIndexedType(Agg->getType(), Idxs) == Val->getType() && "Inserted value must match indexed type!"' failed.
> main.cpp(235): FATAL ERROR: Unhandled signal sent to process; terminating.
> ***
> *** Please file a bug report at https://github.com/ispc/ispc/issues
> *** (Including as much information as you can about how to reproduce this error).
> *** You have apparently encountered a bug in the compiler that we'd like to fix!
> ***
> Aborted (core dumped)

Compiler version:
1.9.1 (build commit 87d0c9a2ed7c9d0e @ 20160708, LLVM 3.8)

The error seems to be related to the `bool` element in the struct. When removed, the error does not appear.

Note: the `-O2` compiler flag was set.

[SimulationData_ispc.txt](https://github.com/ispc/ispc/files/987046/SimulationData_ispc.txt)

**Comment by dbabokin** [comment]
Fixed.
