### ISSUE TITLE
Illegitimate perfomance warning

### ISSUE THREAD

**Issue by peterhuba** [ispc/ispc#1273]
```
struct SimulationData
{
	uniform double *uniform particles_x;
};

export void allocate_init_particle_data(uniform SimulationData &data)
{
	data.particles_x = uniform new uniform double[16];

	uniform SimulationData data_ = data;
	foreach (i = 0 ... 16)
	{
		data_.particles_x[i] = 0;
		data.particles_x[i] = 0; // scatter
	}
}
```
The code above results in a scatter related perfomance warning. This strange behavior can be avoided with a copy of the structure.

Compiler output:

> test.ispc:14:3: Performance Warning: Scatter required to store 
>         value. 
> 		data.particles_x[i] = 0;
>   ^^^^^^^^^^^^^^^^^^^

**Comment by dbabokin** [comment]
Fixed,
