### ISSUE TITLE
crashing after hitting assert in opt.cpp

### ISSUE THREAD

**Issue by comand** [ispc/ispc#1274]
Given the following program, isolated from a (not much) larger program:

    struct ColorRGB
    {
        float r, g, b;
    };

    void do_test(
        ColorRGB * uniform col,
        const uniform int doPremult,
        ColorRGB * uniform CI)
    {
        foreach(j=0...10) {
            if (doPremult) {
                // Note: the real program would actually premultiply here, but that
                // detail was not required to hit the assertion.
                CI[j] = col[j];
            } else {
                CI[j] = col[j];
            }
        }
    }

Compiling the program results in a failed assertion and crash when using pre-compiled v1.9.1 binaries for Linux:

    $ ispc-v1.9.1-linux/ispc --target=sse4 bugtest.ispc 
    Warning: No output file or header file name specified. Program will be compiled and warnings/errors will be issued, but no output will be generated. 
    opt.cpp:4262: Assertion failed: "ok".
    ***
    *** Please file a bug report at https://github.com/ispc/ispc/issues
    *** (Including as much information as you can about how to reproduce this error).
    *** You have apparently encountered a bug in the compiler that we'd like to fix!
    ***
    main.cpp(235): FATAL ERROR: Unhandled signal sent to process; terminating.
    Aborted (core dumped)

    $ gdb --args ispc-v1.9.1-linux/ispc --target=sse4-i32x4 bugtest.ispc 
    Reading symbols from ispc-v1.9.1-linux/ispc...(no debugging symbols found)...done.
    (gdb) run
    Starting program: ispc-v1.9.1-linux/ispc -g --cpu=corei7 --target=sse4-i32x4 bugtest.ispc
    Warning: No output file or header file name specified. Program will be compiled and warnings/errors will be issued, but no output will be generated. 
    opt.cpp:4262: Assertion failed: "ok".
    ***
    *** Please file a bug report at https://github.com/ispc/ispc/issues
    *** (Including as much information as you can about how to reproduce this error).
    *** You have apparently encountered a bug in the compiler that we'd like to fix!
    ***

    Program received signal SIGABRT, Aborted.
    0x00000000020458f9 in raise ()
    (gdb) bt
    #0  0x00000000020458f9 in raise ()
    #1  0x0000000002150a5a in abort ()
    #2  0x00000000004dd4fd in DoAssert(char const*, int, char const*) ()
    #3  0x00000000004b3642 in GatherCoalescePass::runOnBasicBlock(llvm::BasicBlock&) ()
    #4  0x0000000001f41437 in (anonymous namespace)::BBPassManager::runOnFunction(llvm::Function&) ()
    #5  0x0000000001f3c644 in llvm::FPPassManager::runOnFunction(llvm::Function&) ()
    #6  0x0000000001bb3ab7 in (anonymous namespace)::CGPassManager::runOnModule(llvm::Module&) ()
    #7  0x0000000001f3cd58 in llvm::legacy::PassManagerImpl::run(llvm::Module&) ()
    #8  0x00000000004ab435 in Optimize(llvm::Module*, int) ()
    #9  0x000000000049bd45 in Module::CompileFile() ()
    #10 0x00000000004a38b1 in Module::CompileAndOutput(char const*, char const*, char const*, char const*, bool, Module::OutputType, char const*, char const*, char const*, char const*, char const*, char const*) ()
    #11 0x000000000049a927 in main ()
    (gdb)

**Comment by dbabokin** [comment]
Fixed.
