### ISSUE TITLE
Assertion failed - Compiler crash

### ISSUE THREAD

**Issue by peterhuba** [ispc/ispc#1277]
Compiler crash when ISPC built from source. The `ispc` command was called without any parameters.

builtins.cpp:1051: Assertion failed: "func != NULL".
***
*** Please file a bug report at https://github.com/ispc/ispc/issues
*** (Including as much information as you can about how to reproduce this error).
*** You have apparently encountered a bug in the compiler that we'd like to fix!
***
main.cpp(235): FATAL ERROR: Unhandled signal sent to process; terminating.

**Comment by dbabokin** [comment]
I can't reproduce. Please give more details on how you build / versions.

**Comment by peterhuba** [comment]
Oddly enough, I didn't manage to reproduce it either. What I did was I cloned the repository and built it from branch master. Before that I had to install several packages. Here are the relevant commands from my history:
```
sudo apt install llvm
sudo apt install libclang-3.8-dev
sudo apt install libc6-dev-i386
sudo apt install flex bison
sudo apt install libncurses5-dev
make -j4
cp ispc /usr/local/bin/
sudo cp ispc /usr/local/bin/
ispc
```

**Comment by peterhuba** [comment]
I just realized I didnát follow the exact build instructions on the wiki page.

**Comment by dbabokin** [comment]
Just for the record, here's what use on Ubuntu 16.04 (in Docker image):
apt-get install -y cmake gcc g++ git subversion python m4 bison flex zlib1g-dev ncurses-dev libtinfo-dev libc6-dev-i386
