### ISSUE TITLE
While debugging with 1.9.2rc1, can't inspect the values of enums

### ISSUE THREAD

**Issue by zigguratvertigo** [ispc/ispc#1284]
Hi,

It seems that one can't inspect the value of enums types. 

So far the only way I've found to visualize this directly is to rely on ints, instead of enums.

![image](https://user-images.githubusercontent.com/1844966/27994784-84bfcf98-64c4-11e7-85f3-bd1c95be7ce6.png)

![image](https://user-images.githubusercontent.com/1844966/27994760-1469f4a8-64c4-11e7-9a3c-f795264d7501.png)

![image](https://user-images.githubusercontent.com/1844966/27994606-93d5fe42-64c1-11e7-9a4a-c794ba66cb15.png)

-Colin

**Comment by dbabokin** [comment]
I've tried on MacOS and enum values are visible in debugger without any issues. I'll try Windows to check if it's platform specific problem.

**Comment by dbabokin** [comment]
I've found and fixed the problem. The fix will be available in 1.9.2.

**Comment by dbabokin** [comment]
Fixed.
