### ISSUE TITLE
Error Update/Suggestion: "Error: Passing structs to/from application functions is currently broken."

### ISSUE THREAD

**Issue by zigguratvertigo** [ispc/ispc#1285]
While the following suggestion in the warning is indeed correct, it feels like it should be updated to suggest the very-common usecase of passing values by reference first. 

_"Passing structs to/from application functions by value is currently not supported. Use a reference, a const reference, a pointer, or a const pointer to the struct instead."_

**Comment by dbabokin** [comment]
Good suggestion. I've fixed that.

**Comment by dbabokin** [comment]
Fixed.
