### ISSUE TITLE
"Implementing Reductions Efficiently" sample code incorrect

### ISSUE THREAD

**Issue by sourada-e5** [ispc/ispc#1290]
If I implement a small example with the sample code provided in the "Implementing Reductions Efficiently" section of https://ispc.github.io/perfguide.html#using-foreach-active-effectively , I get bad results for both of the last two ISPC implementations, those that have a '+programIndex' in them. If I remove the '+programIndex', then I get correct results.

It makes more sense to me without the +programIndex (because there is already effectively a +programIndex incorporated into the value of i), but then, I'm a newbie to ISPC and can't say I have a complete grasp of it yet...

Intel(r) SPMD Program Compiler (ispc), 1.9.1 (build commit 87d0c9a2ed7c9d0e @ 20160708, LLVM 3.8)

**Comment by dbabokin** [comment]
Good catch, I've fixed that. Website will change after the release.

**Comment by dbabokin** [comment]
Fixed.
