### ISSUE TITLE
Struct init raises: "Ptr must be a pointer to Val type" assert

### ISSUE THREAD

**Issue by tkoziara** [ispc/ispc#1294]
I have attached a simple code with a struct initialisation (simple types inside) which fails and asks to be reported as a bug. Note, that assignment of pointer arrays in the example is incorrect, but perhaps could be handled better by the compiler.
[bug6.zip](https://github.com/ispc/ispc/files/1328870/bug6.zip)

Best regards:)
Tomek

**Comment by dbabokin** [comment]
Fixed.
