### ISSUE TITLE
compile error in 1.9.2 not in 1.9.1

### ISSUE THREAD

**Issue by caughtbyatoe** [ispc/ispc#1309]
Using 1.9.1 and previous versions, the following code compiles without error:

```
inline float
someFunc()
{
    static const float scale = 1.0f / 8.0f;
    static const float halfScale = 0.5f * scale;

    return halfScale;
}
```

But in 1.9.2, the following error is produced:

test.ispc:5:36: Error: Initializer for 
        static variable "halfScale" must 
        be a constant. 
    static const float halfScale = 0.5f * scale;

One workaround is to add the "uniform" keyword to scale and halfScale.

**Comment by dbabokin** [comment]
Fixed with #1377.
