### ISSUE TITLE
Assertion failed using ispc 1.9.2

### ISSUE THREAD

**Issue by igpooh** [ispc/ispc#1323]
Hello!
I got the following error after transferring the algorithm to ispc code:
Performing Custom Build Tools
Assertion failed: (i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!", file C:\Users\dybaboki\ispc\llvm_home_vs2015\llvm-5.0\lib\IR\Instructions.cpp, line 299

Source file can be found: [bvh.zip](https://github.com/ispc/ispc/files/2030426/bvh.zip)

Compilation options are:
ispc.exe -O0 ispc_kernels\%(Filename).ispc -o Debug\%(Filename)_ispc.obj -h ispc_kernels\%(Filename)_ispc.h --arch=x86 --target=sse2-i32x4,sse4-i32x8,avx1-i32x8,avx2-i32x8,avx512knl-i32x16,avx512skx-i32x16 -g

I use the binary version of ispc 1.9.2. Please, feel free to request any additional details.

Thank you in advance!
Ilyas

**Comment by DeepakRajendrakumaran** [comment]
Can reduce it to the following code snippet for reproducing it:

_typedef float<3> float3;
struct AABB {
  uniform float3 pmin;
};
static void check_x(uniform const float3 a) {
  return;
}
static void grow_x( AABB box, uniform const float3 p) {
  check_x(box.pmin);
}_

Seem to be an issue with _uniform_

**Comment by dbabokin** [comment]
Fixed by PR #1326

**Comment by dbabokin** [comment]
This change has broke ./tests/align1.ispc and ./tests/align2.ispc tests.

I think the better fix is to make short vector alignment platform agnostic.

**Comment by dbabokin** [comment]
@aneshlya can we close it?

**Comment by aneshlya** [comment]
Yes, I'm closing it.
