### ISSUE TITLE
Setup appveyor/travis for CI build and artifacts

### ISSUE THREAD

**Issue by emoon** [ispc/ispc#1344]
Hi,

Something that would be really nice to have is to have CI setup so one can download build binaries for the very latest version similar to how DXC for example is setup https://github.com/Microsoft/DirectXShaderCompiler/blob/master/appveyor.yml where you can download the artifacts from the CI

**Comment by dbabokin** [comment]
Yes, we are working on it.

**Comment by dbabokin** [comment]
Travis CI support for Linux was enabled with PR #1360.
Windows is a little more complex, we are still working on it.

**Comment by emoon** [comment]
Awesome! Thanks for the update :)

**Comment by dbabokin** [comment]
Appveyor support for Windows was merged. It's still experimental. Windows LLVM builds are hosted on docker hub. That's not the most straightforward way to store them and I'm not sure if we stick with it going forward. Builds are based on VS2017.

You feedback is welcome.

**Comment by dbabokin** [comment]
For Windows you can go to Appveyor artifacts to download the latest build:
https://ci.appveyor.com/project/ispc/ispc/branch/master

I recommend the build with LLVM 5.0 (there are 4.0, 5.0, 6.0 and 7.0 builds).

For Mac/Linux build artifacts are not available yet, but I can make a package if needed.

**Comment by emoon** [comment]
Ah, cool! Thanks :) I only need Windows for now so that is fine

**Comment by dbabokin** [comment]
We have links to the latest Linux and Windows builds on the README page. I think this should be considered implemented and can be closed.
