### ISSUE TITLE
Unnecessary multiplies in 32x32 -> 64 integer multiplication

### ISSUE THREAD

**Issue by MichaelBell** [ispc/ispc#1362]
I'm looking at using ispc for some multiprecision arithmetic, and I noticed the generated assembler for an important loop has twice the number of pmuludq instructions that I would expect.

I think this might actually be an LLVM problem, but I thought I'd ask here first as I have little experience with the toolchain.

The following ispc input exhibits the problem:
```
export void mul_test(uint A[], uint R[], uniform int size) {
        uint64 cy = 0;
        for (uniform int i = 0; i < size; ++i) {
                uint64 p = (uint64)A[i] * A[0];
                p += cy;
                R[i] = (uint)p;
                cy = p >> 32;
        }
}
```

While a simple `(uint64)A[1] * A[0]` will generate the expected code, when it's in the loop the generated code contains multiples of the high half of A[0]:

```
        vpmovzxdq       16(%rdx), %ymm0 # ymm0 = mem[0],zero,mem[1],zero,mem[2],zero,mem[3],zero
        vpmovzxdq       (%rdx), %ymm1   # ymm1 = mem[0],zero,mem[1],zero,mem[2],zero,mem[3],zero
...
        vpsrlq  $32, %ymm1, %ymm2
        vpsrlq  $32, %ymm0, %ymm3
...
        vpmuludq        %ymm8, %ymm1, %ymm9
        vpaddq  %ymm5, %ymm9, %ymm5
        vpmuludq        %ymm8, %ymm2, %ymm8
        vpsllq  $32, %ymm8, %ymm8
        vpaddq  %ymm5, %ymm8, %ymm5
```
As you can see, ymm2 is guaranteed to be all zeros, but it is multiplied, shifted and added to the result as if it was the high part of a 64-bit quantity.

I saw there were some code generation changes to do with muludq in llvm, so I tried compiling with llvm trunk, but I still get this result.  The problem happens on avx1.1 and sse2 targets as well as avx2 (above).

What's the best way to approach getting this fixed?

**Comment by DeepakRajendrakumaran** [comment]
This is an llvm issue. The zero extension happens in one BB in the LLVM IR and the computation in another. The 2nd BB is not considering the fact that it's a zero extended value.
 The llvm backend should be taking care of this.

**Comment by dbabokin** [comment]
It sounds like a bug that we need to follow up with LLVM. We also seem that we may try fixing it improving phase order.

**Comment by topperc** [comment]
Attempt at an LLVM patch https://reviews.llvm.org/D54725

**Comment by dbabokin** [comment]
I would ask @DeepakRajendrakumaran to try this out and post here what assembly he has out of ISPC.

**Comment by DeepakRajendrakumaran** [comment]
See attached file
[1362_withFix_nov20.txt](https://github.com/ispc/ispc/files/2601704/1362_withFix_nov20.txt)

**Comment by dbabokin** [comment]
@MichaelBell does this look good to you?

**Comment by MichaelBell** [comment]
Yes that asm looks good to me.  Thank you!

I'll double check this also fixes my real program, then will close.

**Comment by dbabokin** [comment]
@MichaelBell Thanks a lot for checking this with your code! We need to port the LLVM fix back to the LLVM version that we are going to use for the next release (it's not going to be LLVM 8.0). So we to keep this bug open till we do the port.

**Comment by aneshlya** [comment]
Looks like everything is fixed here, I'm closing the issue.
