### ISSUE TITLE
Add non-temporal store function or keyword.

### ISSUE THREAD

**Issue by nnevatie** [ispc/ispc#1368]
It would be nice to be able to invoke non-temporal stores in ISPC, e.g. via library functions.

See related Intel docs here: https://software.intel.com/en-us/node/524263

**Comment by dbabokin** [comment]
This is coming, we already have pull request for that: https://github.com/ispc/ispc/pull/1337
It's almost ready, but I'd like to do some checks before merging it in. Your feedback is welcome.

**Comment by nnevatie** [comment]
Thanks! I will try it out as soon as it lands to the main repository.

**Comment by nnevatie** [comment]
I noticed 1.10.0 release ships with `streaming_store` and `streaming_load`. However, much to my surprise, both functions take an unsized uniform array as the destination/source argument.

My typical use case for using streaming stores would be something of the following lines:
`
export void func(uniform const int src[], uniform int dest[], uniform const int length)
{
    foreach (i = 0 ... length)
        dest[i] = some_op(src[i]);
}
`

How could `streaming_store` be applied in the above example?

**Comment by perrstep** [comment]
Hello @dbabokin ,
Running ispc 1.13.0 windows, and given the following function, ispc fails to compile on overload resolution because of the "array to pointer decay" (looks similar to C++ ?).  Do you have insights on this?  Thanks.  
```
export void scale1_s_ispc(uniform int16 vin[], uniform float scales_in[4], uniform int count) {
  assert(programCount % 4 == 0);
  assert(count % 4 == 0);

  float scaleFactors = scales_in[programIndex & 3];

  for( int i = 0;  i < count; i += programCount)
  {
    int16 v = streaming_load(&vin[i]);
    streaming_store(&vin[i], (int16)round((float)v * scaleFactors));
  }

  memory_barrier();
}
```
```
1>myfile.ispc:9:15: Error: Unable to find any matching overload for call to function "streaming_load".
1>Passed types: (uniform int16 * varying)
1>
1>    int16 v = streaming_load(&vin[i]);
1>              ^^^^^^^^^^^^^^
1>
1>myfile.ispc:10:5: Error: Unable to find any matching overload for call to function "streaming_store".
1>Passed types: (uniform int16 * varying, varying int16)
1>
1>    streaming_store(&vin[i], (int16)round((float)v * scaleFactors));
1>    ^^^^^^^^^^^^^^^
1>
```

**Comment by dbabokin** [comment]
Sorry, I've missed ``uniform`` keyword for ``i`` in my code snippet, I've fixed that. This should fix your bug.

**Comment by perrstep** [comment]
Right!  Thank you!
