### ISSUE TITLE
'#pragma ignore warning' feature doesn't prevent failure when -werror switch is used.

### ISSUE THREAD

**Issue by DeepakRajendrakumaran** [ispc/ispc#1394]
1. '#pragma ignore warning' feature  is used to suppress warnings in ispc code. --werror switch causes ispc compilation to fail if there are any warnings. Using '#pragma ignore warning'  should prevent compilation failure with --werror for warnings which the user choose to ignore. This isn't happening currently
2. Compilation doesn't fail with --werror when there's a performance warning.

**Comment by dbabokin** [comment]
Fixed by #1395
