### ISSUE TITLE
Compiler Error while running ISPC

### ISSUE THREAD

**Issue by pradeepisro** [ispc/ispc#1411]
Platform:
OS: Ubuntu 18.04 LTS
CPU: Intel i7-6700 4 core / 8 Threads
RAM: 16 GB
ispc version: Intel(r) SPMD Program Compiler (ispc), 1.10.1dev (build commit 71cb5c75d73709ac @ 20190124, LLVM 9.0.0)

I got the following error while running ispc command
`Warning: No output file or header file name specified. Program will be compiled and warnings/errors will be issued, but 
	        no output will be generated. 
	Warning: No --target specified on command-line. Using default system target "avx2-i32x8". 
	Error: Premature end of file: syntax error, unexpected end of file. `

**Comment by dbabokin** [comment]
What is command line? What is input file?

**Comment by pradeepisro** [comment]
I just typed `ispc`

**Comment by dbabokin** [comment]
It's intended behaviour. When run without parameters, ispc uses stdin as input file.
