### ISSUE TITLE
Support #pragma once as header guard

### ISSUE THREAD

**Issue by emoon** [ispc/ispc#1425]
Currently ISPC will take the path sent in on the command line as path when generating the header guard for the header file to a kernel. If the build system (which happen in our case) send in full paths it will cause the guard to be `LOCAL_DRIVER_PATH_TO_FILE_H` This can cause some bad side effects that every user will have its own unique header which is troublesome if trying to do caching of the build as the hash of this file will change for each user. There are some fixes for this

* On our side we could make sure to not send in the full path.
* Have ISPC using `#pragma once` at the top of the header file. `#pragma once` is heavily supported on most compilers these days https://en.wikipedia.org/wiki/Pragma_once and has been for a while.
* An alternative would be to have ISPC support both formats and have a command line option to pick one of the formats.

**Comment by dbabokin** [comment]
I think it's time to switch to #pragma once. Though I would prefer to keep old behavior under some switch.

**Comment by dbabokin** [comment]
I suggest switching to ``#pragma once`` by default and have old behaviour under ``--no-pragma-once``.

**Comment by emoon** [comment]
That sounds good to me

**Comment by dbabokin** [comment]
Fixed.
