### ISSUE TITLE
ISPC test failures with LLVM 8.0

### ISSUE THREAD

**Issue by DeepakRajendrakumaran** [ispc/ispc#1430]
This issue is to track failures in out test suite with llvm 8.0. Will update as failures get rootcaused

1. Compilation fail/hang with tests/pmuls-vi64*
This is an LLVM codegen issue. The corresponding LLVM bug is  https://bugs.llvm.org/show_bug.cgi?id=40891
2. Affected tests:
	./tests/cfor-gs-double-improve-multidim-2.ispc
	./tests/cfor-gs-improve-multidim-2.ispc
	./tests/gs-double-improve-multidim-2.ispc
	./tests/gs-improve-multidim-2.ispc
	./tests/gs-improve-unif.ispc
	./tests/struct-test-118.ispc

This is also a LLVM bug. DeadstoreEliminationPass removes useful stores because it's fails to identify that gather later uses the result of this store.

Corresponding llvm review req- https://reviews.llvm.org/D58805

**Comment by dbabokin** [comment]
First bug is fixed in 8.0.

**Comment by dbabokin** [comment]
The bugs are fixed in LLVM trunk and 8.0, and patches ported to LLVM 7.0. So we can close that.
