### ISSUE TITLE
Compiler crash when compiling code containing specific float4 swizzle

### ISSUE THREAD

**Issue by petrsm** [ispc/ispc#1437]
Following code crashes latest ISPC compiler:

typedef float<4> float4;

inline float4 min(float4 a, float4 b)
{
	const float4 res = { min(a.x, b.x), min(a.y, b.y), min(a.z, b.z), min(a.w, b.w) };

	return res;
}

inline float4 max(float4 a, float4 b)
{
	const float4 res = { max(a.x, b.x), max(a.y, b.y), max(a.z, b.z), max(a.w, b.w) };

	return res;
}

void BitonicMergeKernel(float4 & a, float4 & b)
{
#if 1
	// This crashes compiler 1.10.0
	float4 bs	= b.wzyx;
#else
	// This is fine
	float4 bs	= b;
#endif

	float4 l	= min(a, bs);
	float4 h	= max(a, bs);

	float4 lp	= { l[0], l[1], h[0], h[1] };
	float4 hp	= { l[2], l[3], h[2], h[3] };

	l = min(lp, hp);
	h = max(lp, hp);

	float4 lp1 = { l[0], h[0], l[2], h[2] };
	float4 hp1 = { l[1], h[1], l[3], h[3] };

	l = min(lp1, hp1);
	h = max(lp1, hp1);

	a.x = l.x;
	a.y = h.x;
	a.z = l.y;
	a.w = h.y;

	b.x = l.z;
	b.y = h.z;
	b.z = l.w;
	b.w = h.w;
}

Thanks for possibly looking into it when you'll have spare time :)

**Comment by DeepakRajendrakumaran** [comment]
Thanks for reporting this issue. We are looking into it.
The test case can be reduced to this-
 
typedef float<2> float2;
 
float2 func(float2 &b) {
     float2 bs = b.xy;
     return bs;
}

The crash occurs when vectortype is passed in by reference and we use ‘swizzle’ to create a new vectortype from it.

**Comment by dbabokin** [comment]
Fixed.

**Comment by petrsm** [comment]
That was quick guys - thanks ! 
:)
