### ISSUE TITLE
Possibility of x4 Targets

### ISSUE THREAD

**Issue by cwfitzgerald** [ispc/ispc#1444]
What is the feasibility of having targets that go beyond `-x2`? I have a couple kernels that have basically no register pressure (due to being reductions) and I was wondering if increasing that would be possible. I know that you can set the settings in the main function of ispc, but I don't know if the other parts of the compiler are generic enough to deal with that.

**Comment by dbabokin** [comment]
Introducing new target will require some manual work for implementing library functions.

But it's quite questionable if you'll be able to have speedup from x4 target, I think. Have you profiled your kernels? What's your compute utilisation with x1 and x2 targets?

**Comment by cwfitzgerald** [comment]
If it is a non-zero amount of work, then it's definitely not worth pursuing. There was something going on with my benchmarks as my manually written intrinsic code was all over the place. Thanks for the prompt response!
