### ISSUE TITLE
Test failures  on Windows on x86-64 with -O0 and 16-bit targets

### ISSUE THREAD

**Issue by DeepakRajendrakumaran** [ispc/ispc#1454]
The tests fail with a return code -1073741819. The  code causing failure in most of these cases in 
 “bool ok(double x, double ref) { return (abs(x - ref) < 1e-6) || abs((x-ref)/ref) < 1e-6; }”

To reproduce, run attached ispc file with following options:
python run_tests.py -t avx2-i32x16 -a x86-64 -o windowsBug

[windowsBug.ispc.zip](https://github.com/ispc/ispc/files/3082147/windowsBug.ispc.zip)

The reason for the failure is the second parameter of ok function in the binary created which causes a crash when it's being unpacked

**Comment by DeepakRajendrakumaran** [comment]
Fix under review to track  in llvm - https://reviews.llvm.org/D60801

**Comment by dbabokin** [comment]
The patch for the problem was added by #1457. So I consider it fixed.
