### ISSUE TITLE
[question] How to specify which installed llvm version to use (cmake build)?

### ISSUE THREAD

**Issue by yurivict** [ispc/ispc#1465]
When ```cling``` is installed, it finds it as llvm. When both llvm80 and llvm60 are installed, it picks llvm80.

I would like to specify which llvm version to use. There should be predictability which llvm is used in the environment where many are installed,

**Comment by aneshlya** [comment]
In ISPC cmake files we use [find_package(LLVM)](https://llvm.org/docs/CMake.html#embedding-llvm-in-your-project) to find LLVM on the system. If LLVM is installed in your operating system’s normal installation prefix (e.g. on Linux this is usually /usr/) find_package(LLVM ...) will automatically find it (in particular it searches for llvm-config). If you have several installations of LLVM, prepend a system PATH with a path to binaries of required version of LLVM.

**Comment by yurivict** [comment]
> prepend a system PATH with a path to binaries of required version of LLVM.

I can do this.

FYI: the llvm project provides the executable ```llvm-config``` that is designed for the purpose of configuring other projects to use llvm. The ideal way is to provide the ```llvm-config``` path to cmake.

**Comment by dbabokin** [comment]
Yes, we use `llvm-config`. We have to use it for figuring out what specific libraries to link, for example. I'm not sure how this exactly works in CMake, as we just use "standard way" to find an LLVM package using find_package(). It finds the package and uses `llvm-config` to figure out the details about the package.

**Comment by yurivict** [comment]
Thanks!
