### ISSUE TITLE
ISPC 1.11.0 assert when compiling complex code

### ISSUE THREAD

**Issue by petrsm** [ispc/ispc#1469]
I am porting SMAA anti aliasing technique from GPU shader to CPU and latest version of ISPC fails to compile attached smaa.ispc file. This message is displayed :

"Assertion failed: castIsValid(getOpcode(), S, Ty) && "Illegal SExt", file c:\iusers\aneshlya\llvm_release\llvm-8.0\lib\ir\instructions.cpp, line 3160"

Unfortunately there is no hint which part of ISPC code is triggering this issue, so I am unable
to find workaround.

Thanks for potentially looking into this :)

[repro.zip](https://github.com/ispc/ispc/files/3123790/repro.zip)

**Comment by aneshlya** [comment]
We were able to reproduce the issue and are working on the fix. Thanks for reporting this!
