### ISSUE TITLE
ISPC 1.11.0 fails to compile this code

### ISSUE THREAD

**Issue by petrsm** [ispc/ispc#1470]
When this code is compiled with latest ispc compiler:

typedef float<2> vec2;
typedef float<4> vec4;

inline vec4 MakeVec4(vec2 a, vec2 b)
{
	const vec4 res = {a.x, a.y, b.x, b.y};

	return res;
}

export void Test()
{
	const uniform vec4 offs0 = { 0, 0, 0, 0 };
	const uniform vec4 offs1 = { 0, 0, 0, 0 };
	const uniform vec4 offs2 = { 0, 0, 0, 0 };

	{
		vec2 uv = { 0, 0 };

		vec4 offsets[3] =
		{
			uv.xyxy + offs0,
			uv.xyxy + offs1,
			MakeVec4((uv.xyxy + offs0).xz, (uv.xyxy + offs1).yw) + offs2
		};

	}
}

Following message is displayed:
"repro.ispc:26:13: Error: Assertion failed (c:\iusers\aneshlya\ispc_upstream\src\expr.cpp:4603): "m->errorCount > 0".
			MakeVec4((uv.xyxy + offs0).xz, (uv.xyxy + offs1).yw) + offs2"
            ^^^^^^^^^^^^^^^^^^^^

Message about submitting the repro case follows, so here it is :)

**Comment by aneshlya** [comment]
We were able to reproduce the issue and are working on the fix. Thanks for reporting this!
