### ISSUE TITLE
Linker crashes when linking ispc executable

### ISSUE THREAD

**Issue by schwarzschild-radius** [ispc/ispc#1479]
The following is the error I got while building ispc

Platform details:
OS: Ubuntu 16.04
compiler: clang-8
ispc branch: master

	[1/77] Linking CXX executable bin/ispc
	FAILED: bin/ispc 
	: && /usr/bin/clang++  -O3  -z noexecstack -z relro -z now -Wl,--gc-sections CMakeFiles/ispc.dir/builtins-dispatch.cpp.o CMakeFiles/ispc.dir/builtins-target-avx2-i64x4-32bit.cpp.o CMakeFiles/ispc.dir/
	builtins-target-avx2-i64x4-64bit.cpp.o CMakeFiles/ispc.dir/builtins-target-avx11-i64x4-32bit.cpp.o CMakeFiles/ispc.dir/builtins-target-avx11-i64x4-64bit.cpp.o CMakeFiles/ispc.dir/builtins-target-avx1-i64x4-32bit.cpp.o 
	CMakeFiles/ispc.dir/builtins-target-avx1-i64x4-64bit.cpp.o CMakeFiles/ispc.dir/builtins-target-avx1-32bit.cpp.o 
	CMakeFiles/ispc.dir/builtins-target-avx1-64bit.cpp.o CMakeFiles/ispc.dir/builtins-target-avx1-x2-32bit.cpp.o 
	CMakeFiles/ispc.dir/builtins-target-avx1-x2-64bit.cpp.o CMakeFiles/ispc.dir/builtins-target-avx11-32bit.cpp.o 
	CMakeFiles/ispc.dir/builtins-target-avx11-64bit.cpp.o CMakeFiles/ispc.dir/builtins-target-avx11-x2-32bit.cpp.o 
	CMakeFiles/ispc.dir/builtins-target-avx11-x2-64bit.cpp.o CMakeFiles/ispc.dir/builtins-target-avx2-32bit.cpp.o 
	CMakeFiles/ispc.dir/builtins-target-avx2-64bit.cpp.o CMakeFiles/ispc.dir/builtins-target-avx2-x2-32bit.cpp.o 
	CMakeFiles/ispc.dir/builtins-target-avx2-x2-64bit.cpp.o CMakeFiles/ispc.dir/builtins-target-sse2-32bit.cpp.o 
	CMakeFiles/ispc.dir/builtins-target-sse2-64bit.cpp.o CMakeFiles/ispc.dir/builtins-target-sse2-x2-32bit.cpp.o 
	CMakeFiles/ispc.dir/builtins-target-sse2-x2-64bit.cpp.o CMakeFiles/ispc.dir/builtins-target-sse4-8-32bit.cpp.o 
	CMakeFiles/ispc.dir/builtins-target-sse4-8-64bit.cpp.o CMakeFiles/ispc.dir/builtins-target-sse4-16-32bit.cpp.o 
	CMakeFiles/ispc.dir/builtins-target-sse4-16-64bit.cpp.o CMakeFiles/ispc.dir/builtins-target-sse4-32bit.cpp.o 
	CMakeFiles/ispc.dir/builtins-target-sse4-64bit.cpp.o CMakeFiles/ispc.dir/builtins-target-sse4-x2-32bit.cpp.o 
	CMakeFiles/ispc.dir/builtins-target-sse4-x2-64bit.cpp.o CMakeFiles/ispc.dir/
	builtins-target-generic-4-32bit.cpp.o CMakeFiles/ispc.dir/builtins-target-generic-4-64bit.cpp.o CMakeFiles/
	ispc.dir/builtins-target-generic-8-32bit.cpp.o CMakeFiles/ispc.dir/builtins-target-generic-8-64bit.cpp.o 
	CMakeFiles/ispc.dir/builtins-target-generic-16-32bit.cpp.o CMakeFiles/ispc.dir/
	builtins-target-generic-16-64bit.cpp.o CMakeFiles/ispc.dir/builtins-target-generic-32-32bit.cpp.o CMakeFiles/
	ispc.dir/builtins-target-generic-32-64bit.cpp.o CMakeFiles/ispc.dir/builtins-target-generic-64-32bit.cpp.o 
	CMakeFiles/ispc.dir/builtins-target-generic-64-64bit.cpp.o CMakeFiles/ispc.dir/
	builtins-target-generic-1-32bit.cpp.o CMakeFiles/ispc.dir/builtins-target-generic-1-64bit.cpp.o CMakeFiles/
	ispc.dir/builtins-target-knl-32bit.cpp.o CMakeFiles/ispc.dir/builtins-target-knl-64bit.cpp.o CMakeFiles/ispc.dir
	/builtins-target-skx-32bit.cpp.o CMakeFiles/ispc.dir/builtins-target-skx-64bit.cpp.o CMakeFiles/ispc.dir/
	builtins-target-skx-8-32bit.cpp.o CMakeFiles/ispc.dir/builtins-target-skx-8-64bit.cpp.o CMakeFiles/ispc.dir/
	builtins-c-32.cpp.o CMakeFiles/ispc.dir/builtins-c-64.cpp.o CMakeFiles/ispc.dir/stdlib_mask1_ispc.cpp.o 
	CMakeFiles/ispc.dir/stdlib_mask8_ispc.cpp.o CMakeFiles/ispc.dir/stdlib_mask16_ispc.cpp.o CMakeFiles/ispc.dir/
	stdlib_mask32_ispc.cpp.o CMakeFiles/ispc.dir/stdlib_mask64_ispc.cpp.o CMakeFiles/ispc.dir/parse.cc.o CMakeFiles/
	ispc.dir/lex.cpp.o CMakeFiles/ispc.dir/src/ast.cpp.o CMakeFiles/ispc.dir/src/builtins.cpp.o CMakeFiles/ispc.dir/
	src/cbackend.cpp.o CMakeFiles/ispc.dir/src/ctx.cpp.o CMakeFiles/ispc.dir/src/decl.cpp.o CMakeFiles/ispc.dir/src/
	expr.cpp.o CMakeFiles/ispc.dir/src/func.cpp.o CMakeFiles/ispc.dir/src/ispc.cpp.o CMakeFiles/ispc.dir/src/
	llvmutil.cpp.o CMakeFiles/ispc.dir/src/main.cpp.o CMakeFiles/ispc.dir/src/module.cpp.o CMakeFiles/ispc.dir/src/
	opt.cpp.o CMakeFiles/ispc.dir/src/stmt.cpp.o CMakeFiles/ispc.dir/src/sym.cpp.o CMakeFiles/ispc.dir/src/
	type.cpp.o CMakeFiles/ispc.dir/src/util.cpp.o  -o bin/ispc  -Wl,-rpath,/usr/lib/llvm-8/lib: /usr/lib/llvm-8/lib/
	libclangFrontend.a /usr/lib/llvm-8/lib/libclangDriver.a /usr/lib/llvm-8/lib/libclangSerialization.a /usr/lib/
	llvm-8/lib/libclangParse.a /usr/lib/llvm-8/lib/libclangSema.a /usr/lib/llvm-8/lib/libclangAnalysis.a /usr/lib/
	llvm-8/lib/libclangAST.a /usr/lib/llvm-8/lib/libclangBasic.a /usr/lib/llvm-8/lib/libclangEdit.a /usr/lib/
	llvm-8/lib/libclangLex.a /usr/lib/llvm-8/lib/libLLVM-8.so -lpthread -ldl -lz -ltinfo -lcurses && :
	clang: error: unable to execute command: Segmentation fault (core dumped)
	clang: error: linker command failed due to signal (use -v to see invocation)

I also get a crash report from ubuntu stating x86_64-linux-gnu-ld.bfd stopped working

**Comment by dbabokin** [comment]
Typically this kind of problems occur when LLVM being used and ISPC itself are compiled using different compilers. And we always prefer manually built LLVM for ISPC build. That's for multiple reasons, and errors like this one is one of them.
