### ISSUE TITLE
Rcp with no Newton-Raphson

### ISSUE THREAD

**Issue by JeffRous** [ispc/ispc#1481]
I'd like to have an rcp function exposed without the associated Newton-Raphson approximation attached. This would be used to build more complex operations that can be finely controlled. It should just trigger the assembly instruction with any associated loads similar to add, mul, etc.

This function should be available for all cases, not just when compiled with fast math.

[ISPC example code](https://ispc.godbolt.org/z/cII3IJ)

**Comment by dbabokin** [comment]
We do Newton-Raphson for rcp() and rsqrt(). I believe we need to implement fast version for both of them.

I think we should use `rcp_fast()` and `rsqrt_fast()` names.

Also, it makes sense to use these functions with `--opt=fast-math`. Of course, it should affect only implicitly generated `rcp()`.

@DeepakRajendrakumaran please have a look at it.

**Comment by dbabokin** [comment]
Library functions are added, though they are not used by default for division under `--opt=fast-math` - to not break existing codes.
