### ISSUE TITLE
Add a stdlib integer abs() function

### ISSUE THREAD

**Issue by jonckennedy** [ispc/ispc#1486]
There are stdlib functions for float abs(float), but nothing for integer data types.

Please provide : 

int abs(int);

which maps onto the x86 _mm256_abs_epi32() intrinsics

**Comment by dbabokin** [comment]
@jonckennedy I've tried using ternary operator in source code and it yields pabs intruction. I.e.:
```
int pabs(int num) {
    return num > 0 ? num : -num;
}
```

yields 

```
pabs___vyi: # @pabs___vyi
  vpabsd %ymm0, %ymm0
  retq
```

Compiler explorer link to play with: https://godbolt.org/z/B21Bk2

So, the question: why do we need integer abs? For symmetrical stdlib? To make it easier to trigger pabs (no need to guess if the pattern is right)?

**Comment by dbabokin** [comment]
Pinging @jonckennedy

**Comment by jonckennedy** [comment]
For symmetry - to allow calling abs() on a variable without worrying about
the type.
