### ISSUE TITLE
Add a noinline keyword

### ISSUE THREAD

**Issue by jonckennedy** [ispc/ispc#1488]
When debugging and/or profiling with tools like vtune, it is often useful to prevent functions from getting inlined, this is especially true for ISPC which agressively inlines.

This would be similar to Microsofts noinline keyword : https://docs.microsoft.com/en-us/cpp/cpp/noinline?view=vs-2019

**Comment by dbabokin** [comment]
Implemented in #1489

**Comment by DeepakRajendrakumaran** [comment]
Got fixed on llvm in the following revision- http://llvm.org/viewvc/llvm-project?view=revision&revision=363251 . Verified fix in ispc
