### ISSUE TITLE
Change syntax to regular C with typedefs/conventions

### ISSUE THREAD

**Issue by Meai1** [ispc/ispc#1490]
I dont see anything that necessarily requires an entire new language syntax. 
instead of `uniform int count` why not let me continue to have editor support and intellisense and change the syntax to C but the ispc compiler can then look at conventional stuff like, lets say `int uni_count` would be a uniform int. Or maybe typedef it, to UNIFORM_INT count; 
Whatever is most convenient but to introduce an entirely new language for something that's practically the same as C anyway is a waste in my opinion. 
You even support #ifdefs, I mean at that point what's the advantage of a foreach compared to just getting everything tooling related that C has. 
Please investigate if the syntax could be changed to be compatible with C. You dont even have to remove the old syntax, just let me write things in normal C code that can be fed into the ispc compiler and it will know what uni_int means just from the way I named the variable.

**Comment by dbabokin** [comment]
ISPC has completely different execution model compared to C. The execution model explicitly implies that it executes on vector machine. Reasoning about code execution in terms of scalar semantics is not possible in some cases.

Syntactic changes are motivated by the execution model. Specifically the concept of `uniform` and `varying`. They can not be transparently mapped to C language. They imply additional casts and error checking and affect many subtle language rules like overload resolution. Other syntactic constructs, like `foreach()`, `foreach_active()`, `foreach_unique()`, and `unmasked` are also specific to ISPC and can't be simply mapped to C.

So it's really different language, it's not C. It just looks familiar C developers.

When speaking about tooling, what do you mean specifically? IDE? You can use VSCode, which has plugin for ISPC. If you use simple editors, like vim, it also has ISPC syntax support.
