### ISSUE TITLE
documentation typo

### ISSUE THREAD

**Issue by sriravic** [ispc/ispc#1491]
In the ispc.rst documentation file, there is a typo in the following code

```
foreach_active (i) {
    ++array[index];
}
```

where the `foreach_active` s looping variable should be `index` instead of `i`

**Comment by sriravic** [comment]
ah, I believe the existing code is correct.

**Comment by RoyiAvital** [comment]
I have a question about the *Data Alignment and Aliasing* section.
Well, it says nothing about alignment.

Does ISPC assume the arrays transferred are aligned?
If yes, I guess it assumes 64 byte alignment (For AVX512)?
If not, how can I tell ISPC the data is aligned and it can use aligned load and store in the code it produces?

**Comment by dbabokin** [comment]
Yes, aligned data is expected with alignment by the architecture vector type size.

**Comment by RoyiAvital** [comment]
So it should be written explicitly in the documentation.

I am reading through it. I will try to point to more gray areas.
