### ISSUE TITLE
Document explicit vector indexing

### ISSUE THREAD

**Issue by JeffRous** [ispc/ispc#1497]
```
struct FVector4
{
	float V[4]; 
};

inline uniform FVector4 Mul3(const uniform FVector4 &A, const uniform FVector4 &B)
{
    uniform float<4> S0 = { A.V[0], A.V[1], A.V[2], A.V[3] };
    uniform float<4> S1 = { B.V[0], B.V[1], B.V[2], B.V[3] };
    uniform float<4> D =  S0 * S1;

    uniform FVector4 Result;
    Result.V[0] = D[0];
    Result.V[1] = D[1];
    Result.V[2] = D[2];
    Result.V[3] = D[3];
    return Result;
}

export void TestUniform3(uniform FVector4 Dst[], const uniform FVector4 Src0[], const uniform FVector4 Src1[], const uniform FVector4 Src2[], const uniform int Count)
{
	for(uniform int i = 0; i < Count; i++)
	{
        Dst[i] = Mul3(Src0[i], Src1[i]);
	}
}
```

is legal code. Nowhere in the documentation does it make mention that explicit vector can be indexed using [] rather than .x .y etc.

**Comment by aneshlya** [comment]
Explicit vector indexing has been already documented: https://ispc.github.io/ispc.html#short-vector-types.

> There are two mechanisms to access the individual elements of these short vector data types. The first is with the array indexing operator:
`float<4> foo;`
`for (uniform int i = 0; i < 4; ++i)
    foo[i] = i;`

**Comment by dbabokin** [comment]
I assume we can close the issue.
