### ISSUE TITLE
 bug report messages when i use extern c

### ISSUE THREAD

**Issue by xoraxrax** [ispc/ispc#1505]
```.cpp
extern "C" int32 strlen(int8* ptr) {
    int i = 0;
    while(*ptr != 0){
        i++;
    }
    return i;
}
```
> ispc 1.ispc --arch=x86 -o 1.obj

```
Warning: No --target specified on command-line. Using default system target "avx2-i32x8".
c:\iusers\aneshlya\ispc_upstream\src\func.cpp:350: Assertion failed: "type->isUnmasked || type->isExported".
***
*** Please file a bug report at https://github.com/ispc/ispc/issues
*** (Including as much information as you can about how to reproduce this error).
*** You have apparently encountered a bug in the compiler that we'd like to fix!
***

```

**Comment by pbrubaker** [comment]
With ISPC the only time you want to use extern is if you're declaring a function that will be compiled with a C/C++ compiler and linked later.

What you want to use in this case is export.

`export uniform int32 strlen(int8 uniform*uniform ptr) {
    uniform int i = 0;
    while(*ptr != 0){
        i++;
        ptr++;  // also added the pointer increment here to prevent inf loop
    }
    return i;
}`

**Comment by pbrubaker** [comment]
It should probably error that an `extern "C"` function has a body though.

**Comment by dbabokin** [comment]
That's right, we should emit an error, that ``extern "C"`` function has body. ``extern "C"`` is only for declaration for calling back to C.

**Comment by dbabokin** [comment]
Fixed.
