### ISSUE TITLE
Failures with latest llvm trunk

### ISSUE THREAD

**Issue by DeepakRajendrakumaran** [ispc/ispc#1507]
The following tests fail with latest llvm build:
       ./tests/atomics-1.ispc
	./tests/atomics-2.ispc
	./tests/atomics-9.ispc
	./tests/foreach-17.ispc
	./tests/foreach-7.ispc
	./tests/local-atomics-1.ispc
	./tests/local-atomics-2.ispc
	./tests/local-atomics-9.ispc
	./tests/phi-opts-1.ispc
	./tests/phi-opts-2.ispc
	./tests/reduce-add-float-2.ispc

The tests are failing for target=avx2-i64x4 with O2 optimization. The error is an assert in X86ISelLowering.cpp : Assertion `(HOp.getValueType() == MVT::v2f64 || HOp.getValueType() == MVT::v4f64) && "Unexpected type for h-op"' failed.
From initial investigation, seem to be  a llvm backend issue.

**Comment by dbabokin** [comment]
What target, what are the symptoms?

**Comment by DeepakRajendrakumaran** [comment]
Added details in the original bug report

**Comment by DeepakRajendrakumaran** [comment]
Got fixed in llvm in the following revision- http://llvm.org/viewvc/llvm-project?view=revision&revision=363251 . Verified fix in ispc.
