### ISSUE TITLE
An option for dumping textual form of LLVM IR

### ISSUE THREAD

**Issue by dbabokin** [ispc/ispc#1511]
Right now ISPC has ``--emit-llvm`` flag for dumping LLVM IR. It produces bitcode. It's easy to convert to textual representation by filtering through ``llvm-dis`` (if the right version is available around). But the most frequent use case is dumping LLVM IR to look at it by a human being, not to pass it to another tool. So adding an option, which would produce textual LLVM IR is desired.

I propose using ``--emit-llvm-text`` as a command line switch for emitting LLVM IR in textual form.

Note that implementation of this switch will like need to be under ``#ifndef ISPC_NO_DUMPS``.

**Comment by schwarzschild-radius** [comment]
@dbabokin `--emit-llvm` seems similar to clang's `-emit-llvm` which emits LLVM textual representation. May be it is better to add `--emit-llvm-bitcode` to emit bitcode and `--emit-llvm` to emit LLVM IR. any thoughts?

**Comment by pbrubaker** [comment]
I mostly agree.  I suggest we deprecate `--emit-llvm` with a warning message but not alter behavior, then introduce `--emit-llvm-binary` and `--emit-llvm-text` or something equivalent.

**Comment by dbabokin** [comment]
In clang ``-emit-llvm`` does both textual and binary. It depends on combination with other switches.
This command will produce bitcode:
```
clang t.c -emit-llvm -o t.bc -c
```
This command will produce textual representation:
```
clang t.c -emit-llvm -o t.ll -c -S
```
And passing the options directly to LLVM will yield textual form as well:
```
clang -cc1 t.c -emit-llvm -o t.ll
```

I think the design with ``--emit-llvm`` + ``--emit-llvm-text`` is the cleanest thing we can have given that we already have ``--emit-llvm``. Deprecating this options doesn't make much sense to me. Also note that different people would expect different spelling for binary form: ``--emit-llvm-binary`` or ``--emit-llvm-bitcode`` (bitcode looks more precise term to me).

**Comment by schwarzschild-radius** [comment]
As far as I can see there is no `-S` flag to emit assembly in ISPC but there is `--emit-asm`. So we can create `-S` as an alias option. when `--emit-llvm` is used with `-S` can dump LLVM IR and when used as plain `--emit-llvm` can dump LLVM bitcode.

**Comment by schwarzschild-radius** [comment]
As far as I can see there is no `-S` flag to emit assembly in ISPC but there is `--emit-asm`. So we can create `-S` as an alias option. when `--emit-llvm` is used with `-S` can dump LLVM IR and when used as plain `--emit-llvm` can dump LLVM bitcode.

**Comment by dbabokin** [comment]
I see your point, option unification with clang makes sense. But I would say we need to be as much compatible as possible, or do orthogonal thing. Right now, our options are almost completely different, so I would vote for keeping them different. Otherwise it would introduce more confusion than do good. Designing options from scratch today, I would probably follow what clang has. But we have what we have.

By the way, LLVM options (not clang, but LLVM compiler itself) has ``-emit-llvm`` for text and ``-emit-llvm-bc`` for bitcode.

**Comment by dbabokin** [comment]
Implemented.
