### ISSUE TITLE
Create static URL to Linux ispc binary from CI for Compiler Explorer

### ISSUE THREAD

**Issue by pbrubaker** [ispc/ispc#1515]
I chatted with Matt Godbolt after noticing that GCC/clang have a trunk "version."  I think this would be a good way to test/verify features/fixes in the ISPC development branch going forward.  He is willing to setup a daily build target in Compiler Explorer for ISPC provided we can support it.  When we were chatting we found the easiest thing for him would be a static link to the ISPC binary for Linux.

We should expose the latest version, or latest known good build of the ispc binary as a static URL for consumption by the Compiler Explorer team.  When this issue is resolved I'll let Matt know that the work on their side can begin.

**Comment by dbabokin** [comment]
After merging #1517 we have Linux artifacts. But the link to the latest build is not static, we need to figure out if there's a workaround for that.

**Comment by dbabokin** [comment]
Here's the description how to have a static link to the artifacts: https://github.com/appveyor/ci/issues/403

We should probably have a link to Linux and Windows artifacts on README page as well.

**Comment by dbabokin** [comment]
Now links work as expected. There's one nuance, looks like when new PR is merge, there's short time window when links may return an error.
