### ISSUE TITLE
__vectorcall calling convention on Windows

### ISSUE THREAD

**Issue by dbabokin** [ispc/ispc#1526]
ISPC uses default calling convention on all supported platforms. While Linux and macOS default is good enough - these calling conventions support passing vector arguments in vector registers. By on Windows default calling convention forces passing vectors through memory. __vectorcall (https://docs.microsoft.com/en-us/cpp/cpp/vectorcall?view=vs-2019) solves this problem.

I suggest switching to __vectorcall calling convention for ISPC on Windows.

There are 3 aspects here:
(1) export functions, they are not allowed to have varying argument, so it will likely not affect these functions much.
(2) internal ISPC functions (including stdlib functions) - they typically use varying arguments, but they quite frequently they are inlined.
(3) external calls from ISPC to C/C++.

I suggest switching all these use cases to use __vectorcall by default - this will simplify how implementation and documentation. We'll also need a switch to fall back to current behavior.

If using __vectorcall convention appears to be a problem in any of use case, we'll need to come up with mechanism for specifying calling convention on finer granular level.

**Comment by pbrubaker** [comment]
This should also help out Xbox One.

**Comment by dbabokin** [comment]
Right. But only for the programs, which have relatively frequent ISPC function calls.

**Comment by pbrubaker** [comment]
Isn't this already done?

**Comment by aneshlya** [comment]
`__vectorcall` convention support was added in v1.14.0
