### ISSUE TITLE
Disable optimization-sensetive performance warnings when compiling with -O0.

### ISSUE THREAD

**Issue by dbabokin** [ispc/ispc#1538]
Performance warnings about gathers/scatters, which trigger only at -O0 should be disabled at -O0 optimization level. Other performance warnings, which doesn't depend on optimization level should not be affected.

**Comment by dbabokin** [comment]
Here's an example: https://godbolt.org/z/rJP3hD

**Comment by DeepakRajendrakumaran** [comment]
Fixed here : https://github.com/ispc/ispc/commit/2a4fb229f928b66abe883aa1cdac162d0236ed6c
