### ISSUE TITLE
Improper behavior of comparison operator featuring NaN

### ISSUE THREAD

**Issue by geoffrey-jon** [ispc/ispc#1548]
According to IEEE 754 (Standard for Floating-Point Arithmetic) Section 5.11:

> Four mutually exclusive relations are possible: less than, equal, greater than, and unordered. The last case arises when at least one operand is NaN. Every NaN shall compare unordered with everything, including itself.

And https://www.gnu.org/software/libc/manual/html_node/Infinity-and-NaN.html says:

> In comparison operations, positive infinity is larger than all values except itself and NaN, and negative infinity is smaller than all values except itself and NaN. NaN is unordered: it is not equal to, greater than, or less than anything, including itself. x == x is false if the value of x is NaN. You can use this to test whether a value is NaN or not, but the recommended way to test for NaN is with the isnan function (see Floating Point Classes). In addition, <, >, <=, and >= will raise an exception when applied to NaNs.

In this simple test, I expect the value of (-nan < 0.0f) to be false: https://godbolt.org/z/G7SbJ4. But that comparison evaluates to true. 

This behavior should be fixed such that every comparison operator involving a NaN returns false.

**Comment by DeepakRajendrakumaran** [comment]
Everything other than neq should be returning false- Clang behavior for same:  https://godbolt.org/z/kts4Oh

**Comment by dbabokin** [comment]
Fixed.
