### ISSUE TITLE
How to use the generated .obj in my own project? 

### ISSUE THREAD

**Issue by warwickyu** [ispc/ispc#1558]
In windows 10, I just download the ispc.exe, i wrote a .ispc and use command line to generate a .h and .obj files(https://ispc.github.io/ispc.html). In my project, i included the .h file in it, but i don't know how to use the .obj file. Now i have a lot of issues (unresolved external symbol), can anyone help me? i want to know how to use the generated .h and .obj files in my own project?

**Comment by pbrubaker** [comment]
Are you using Visual Studio?

**Comment by warwickyu** [comment]
> Are you using Visual Studio?
> […](#)
> On Aug 19, 2019, at 7:21 PM, warwickyu ***@***.***> wrote: In windows 10, I just download the ispc.exe, i wrote a .ispc and use command line to generate a .h and .obj files(https://ispc.github.io/ispc.html). In my project, i included the .h file in it, but i don't know how to use the .obj file. Now i have a lot of issues (unresolved external symbol), can anyone help me? i want to know how to use the generated .h and .obj files in my own project? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Yes, I am using VS2017

**Comment by pbrubaker** [comment]
The simple answer is that you need to add them to the linker's input.  Here is how I setup my ISPC files in Visual Studio.  I set my ISPC files up to be compiled with with a "Custom Build Tool."

![image](https://user-images.githubusercontent.com/6944373/63315866-9ffac800-c2c1-11e9-845b-4b2289cf28bb.png)

Make sure "Link Objects" is set to true.

**Comment by dbabokin** [comment]
Hi, @warwickyu,

Have you succeeded adding ispc source to your project? Another strategy might be to use CMake, which will generate VS project files for you. We are using CMake in our examples, which you can use for your reference.

**Comment by warwickyu** [comment]
> Hi, @warwickyu,
> 
> Have you succeeded adding ispc source to your project? Another strategy might be to use CMake, which will generate VS project files for you. We are using CMake in our examples, which you can use for your reference.

Ok, i will try that strategy later. Thanks

**Comment by warwickyu** [comment]
> The simple answer is that you need to add the .OBJ files to the linker's input. It's a little complicated in Visual Studio. Here is how I setup my ISPC files to be compiled with a "Custom Build Tool" in Visual Studio.
> 
> ![image](https://user-images.githubusercontent.com/6944373/63316096-94f46780-c2c2-11e9-815e-fdcd740e01d3.png)
> 
> ![image](https://user-images.githubusercontent.com/6944373/63315866-9ffac800-c2c1-11e9-845b-4b2289cf28bb.png)
> 
> Make sure "Link Objects" is set to "Yes."

Hello, there is a new question, i know the ispc supports many kinds of width calculation, just like sse2-i32x4,sse4-i32x8,avx1-i32x8,avx2-i32x8,avx512knl-i32x16,avx512skx-i32x16, and i want to know the whether the ispc will choose the best width for us? In your experience, which one is better(fast) for modern computer?

**Comment by dbabokin** [comment]
Sorry for late response. ISPC will not choose width. For the same ISA width needs to be picked manually. Typically the best width is "native" width, i.e. 4 for sse, 8 for avx1/2 and 16 for avx512. But  it really depends on your algorithm and I would encourage you to experiment.

The reasons for different width to perform differently for different algorithms:
- wider width requires more register. If the algorithm hits the limit, spill/fill may affect performance.
- wider width may enable better latency hiding (it's similar to unrolling in some sence).
- wider width may trigger cpu frequency drop.

Other effects may affect the real performance, so you'll need to experiment with you specific code.
