### ISSUE TITLE
What's wrong with my SGEMM_tileShuffle()?

### ISSUE THREAD

**Issue by warwickyu** [ispc/ispc#1559]
When i use two methods of matrix multiplication (SGEMM_naive and SGEMM_tileShuffle), there are two different results. I just want to take matrixAt multiply matrixA, and put the result into tempMatrix. But in the result of SGEMM_tileShuffle, there are many very big big numbers? oops! i have already set the tempMatrix to zero. Are there any problems ?
![naive](https://user-images.githubusercontent.com/40454073/63328481-d2103680-c362-11e9-8467-f8878d88ff5f.PNG)
![捕获1](https://user-images.githubusercontent.com/40454073/63328485-d4729080-c362-11e9-9c93-8aba6be771bc.PNG)
![捕获2](https://user-images.githubusercontent.com/40454073/63328741-46e37080-c363-11e9-899d-2c6a30fe8a0a.PNG)
![捕获3](https://user-images.githubusercontent.com/40454073/63328745-48149d80-c363-11e9-8d91-3ab45c520bbf.PNG)

**Comment by dbabokin** [comment]
You are basically running SGEMM example with small input:
```bin/sgemm 1 3 2 3```

It will show you the same validation error that you see. The problem is that the code assumes power of 2 sizes and large enough matrices.

That's a good point that we need add to the example these checks.

**Comment by warwickyu** [comment]
> You are basically running SGEMM example with small input:
> `bin/sgemm 1 3 2 3`
> 
> It will show you the same validation error that you see. The problem is that the code assumes power of 2 sizes and large enough matrices.
> 
> That's a good point that we need add to the example these checks.

Another question, please.
Now, I have many many small matrix(3*3 or 6*6) need to multiply, but the input parameter is some vector, the first step i need to do is to change the vector to a matrix  so that i can use the SGEMM exmaples to calculate them, but you  know i need to malloc or free and pretreat them very frequently, so the benefits of ispc disapper, maybe FPU is more faster than ispc. What optimization can I do? Thanks.

**Comment by dbabokin** [comment]
I'm not sure that I understand your question. If you need to handle many small objects, you should probably allocate them in a large array/pool, so you don't pay allocation cost for every element.
Are you multiplying different small matrices by the same fixed matrix?
