### ISSUE TITLE
Quotes on command line sometimes break command line processing

### ISSUE THREAD

**Issue by ivanassen** [ispc/ispc#1562]
We noticed that adding quotes around the argument after -I (include path) seems to break the processing for the rest of the line. For example, 

`"C:\Source\Tools\hgimgcvt\/../../sdk/ispc_texcomp/ispc/win32/ispc.exe"  -O2 "C:\Source\Tools\hgimgcvt\/%(FileName).ispc" -I "C:\Source\Tools\hgimgcvt\" -o "C:\Source\Tools\hgimgcvt\Bin\%(FileName).obj" -h "C:\Source\Tools\hgimgcvt\Bin\%(Filename)_ispc.h" --arch=x86-64 --target=sse2,sse4,avx --opt=fast-math`

results in the following error messages:

```
1>CUSTOMBUILD : warning : No output file or header file name specified. Program will be compiled and warnings/errors will be issued, but no output will be generated.
1>CUSTOMBUILD : warning : No --target specified on command-line. Using default system target "avx2-i32x8".
```

While the following two work:

_no quotes around -I argument:_

`"C:\Source\Tools\hgimgcvt\/../../sdk/ispc_texcomp/ispc/win32/ispc.exe"  -O2 "C:\Source\Tools\hgimgcvt\/%(FileName).ispc" -I C:\Source\Tools\hgimgcvt\ -o "C:\Source\Tools\hgimgcvt\Bin\%(FileName).obj" -h "C:\Source\Tools\hgimgcvt\Bin\%(Filename)_ispc.h" --arch=x86-64 --target=sse2,sse4,avx --opt=fast-math
`

_-I placed at end of line:_

`"C:\Source\Tools\hgimgcvt\/../../sdk/ispc_texcomp/ispc/win32/ispc.exe"  -O2 "C:\Source\Tools\hgimgcvt\/%(FileName).ispc" -o "C:\Source\Tools\hgimgcvt\Bin\%(FileName).obj" -h "C:\Source\Tools\hgimgcvt\Bin\%(Filename)_ispc.h" --arch=x86-64 --target=sse2,sse4,avx --opt=fast-math -I "C:\Source\Tools\hgimgcvt\" `

**Comment by DeepakRajendrakumaran** [comment]
This was fixed as part of another fix - https://github.com/ispc/ispc/issues/1638

Feel free to reopen if you're still seeing this.
