### ISSUE TITLE
1499 test fails with 1.12.0

### ISSUE THREAD

**Issue by ArchangeGabriel** [ispc/ispc#1568]
While trying to upgrade to 1.12.0, I realized that test 1499 is now failing on our build system. I did not find much more details to share about the failure, but I would be happy to provide any required information.

This on Arch Linux, using LLVM/Clang 8.0.1.

**Comment by dbabokin** [comment]
It basically means non of the tests are working. What error is reported? Please try running some specific test to see on error at a time.

Could it be that system compiler that you are using is not supporting 32 bits?

**Comment by ArchangeGabriel** [comment]
Sorry if I did not express myself correctly, I meant that [this test](https://github.com/ispc/ispc/blob/master/tests/lit-tests/1499.ispc) is failing. No error message specifically, it just says that this test failed and I wasn’t able to find any output for more information. I could try to run it manually, but don’t have time to check how to do that right now.

**Comment by dbabokin** [comment]
Ah, you are running lit test, not the main test corpus (which is run with `run_tests.py`).
The reason why it fails is obvious, you are using stock version of LLVm, without proper patches. Specifically this patch is not applied: https://github.com/ispc/ispc/blob/master/llvm_patches/8_0_r362675.patch

The proper way to build ISPC is to built LLVM manually (`alloy.py -b --version=8.0`), which will ensure proper patches are in place.

Or you can live with redundant instruction in some cases. It's not that dramatic bug.

**Comment by ArchangeGabriel** [comment]
Thank you. We updated to LLVM 9.0, so the issue is now fixed.

**Comment by dbabokin** [comment]
Is there any specific reason why you prefer building from source, rather than using released binaries? Are you building ispc for some package manager?

**Comment by ArchangeGabriel** [comment]
Yes indeed, I’m building official Arch packages: https://www.archlinux.org/packages/community-staging/x86_64/ispc/
