### ISSUE TITLE
How to use ispc in a cmakeList?

### ISSUE THREAD

**Issue by warwickyu** [ispc/ispc#1569]
I have successfully build my program in MSVC using the command line.
But now i want to use ISPC in linux. So i cann't add the .OBJ files to the linker's input just like VS2017. 
The following is part of my CMakeList, and  my program is a 
Multi-project program, i use .ispc in xSFM. xSFM is not the main program. I put the .exe and .ispc in the ispcMatrix folder, and add the  add_custom_command to generate .h and .obj files, but obviously it doesn't work? Did i miss any important commands? How to use ispc in a cmakeList?
# xSFM
include_directories(${PROJECT_SOURCE_DIR}/code/include ${EIGEN_DIR} ${SECUREC_DIR}/include)
aux_source_directory(${PROJECT_SOURCE_DIR}/code/src/. XSFM_SRC)
aux_source_directory(${PROJECT_SOURCE_DIR}/code/src/ispcMatrix/. ISPC_SRC)
if(MSVC)
SET(ISPC_COMPILER ${PROJECT_SOURCE_DIR}/code/src/ispcMatrix/ispc.exe)
SET(ISPC_OPTIONS --arch=x86-64)
add_custom_command(OUTPUT simd_ispc.obj COMMAND ispc --opt=fast-math ${ISPC_SRC}/simd_ispc.ispc -o simd_ispc.obj DEPENDS simd_ispc.ispc)
add_custom_command(OUTPUT simd_ispc.h COMMAND ispc --opt=fast-math ${ISPC_SRC}/simd_ispc.ispc -o simd_ispc.h DEPENDS simd_ispc.ispc)
else(MSVC)
SET(ISPC_COMPILER ${PROJECT_SOURCE_DIR}/code/src/ispcMatrix/ispc)
SET(ISPC_OPTIONS --arch=x86-64)
add_custom_command(OUTPUT simd_ispc.o COMMAND ispc --opt=fast-math ${ISPC_SRC}/simd_ispc.ispc -o simd_ispc.o DEPENDS simd_ispc.ispc)
add_custom_command(OUTPUT simd_ispc.h COMMAND ispc --opt=fast-math ${ISPC_SRC}/simd_ispc.ispc -o simd_ispc.h DEPENDS simd_ispc.ispc)
endif(MSVC)
ADD_LIBRARY(xSFM SHARED ${XSFM_SRC})

**Comment by dbabokin** [comment]
Have you checked how CMake integration is done in out examples? Copy-pasting from there might the easiest path to working CMake.

**Comment by warwickyu** [comment]
> Have you checked how CMake integration is done in out examples? Copy-pasting from there might the easiest path to working CMake.

The cmakeList in examples is too complex for me, i found another program in github, he used ispc in his program, and the cmakeList as following:
![捕获](https://user-images.githubusercontent.com/40454073/64307964-551fc680-cfca-11e9-8033-9ed2ec7651a2.JPG)
My problem is that i use ispc in one of my project, not the main project, you know this is a multi-project program , so i don't know how to link the .obj and .h with the associated project?
