### ISSUE TITLE
Misplaced "Initializer for global variable must be a constan" error

### ISSUE THREAD

**Issue by tkoziara** [ispc/ispc#1596]
When trying to compile such code:

```
/* a simple case */
static uniform float a = 1.0;
static uniform float * uniform pa = &a; /* this fails */

/* here is what I'd really like to do */
static const uniform float b[] = {0.};
static const uniform float c[] = {0.};
static const uniform float * uniform pv[] = {NULL, b, c}; /* this also fails */
```
the following errors are reported:
bug7.ispc:3:37: Error: Initializer for global variable "pa" must be a constant. 
bug7.ispc:8:46: Error: Initializer for global variable "pv" must be a constant. 

File attached:) Thank you:)
[bug7.zip](https://github.com/ispc/ispc/files/3808585/bug7.zip)

**Comment by dbabokin** [comment]
Fixed by #1656
