### ISSUE TITLE
What is generic_defs.h

### ISSUE THREAD

**Issue by cloudhan** [ispc/ispc#1604]
I use `--target=generic-x8 --emit-c++` options to generate a cpp file. In the generated cpp file, it includes `generic_defs.h`. How can I obtain/generate this header file?

**Comment by cloudhan** [comment]
related #1252 

Seems there is no mention of `generic_defs.h` in docs.

**Comment by dbabokin** [comment]
I've did some archeological research and see that it was introduced by this commit: [8938e1444](https://github.com/ispc/ispc/commit/8938e1444)

This file should be provided by user. We provide several "reference implementations" in example folders: [examples/intrinsics](https://github.com/ispc/ispc/tree/master/examples/intrinsics)

Disclaimer: generic targets are not maintained at the moment and contain multiple known issues.

**Comment by dbabokin** [comment]
You need to use ``--c++-include-file=<file>`` to point something other than ``generic_defs.h``

**Comment by cloudhan** [comment]
OK, got it. 

As for 
> Disclaimer: generic targets are not maintained at the moment and contain multiple known issues.

I should mention that option `--emit-c++` requires a generic target

**Comment by dbabokin** [comment]
Yes, ``--emit-c++`` is part of generic targets support.

The value and use cases of generic targets are not completely clear. The only important case that I have in mind is fall-back path for targets, which are not currently supported by ISPC / open-source version of LLVM.

To make generic targets a first class citizen we need quite bit of work, but we are busy with other problems right now. If someone sees value in these targets and has spare cycles to work on them, that would be great.
