### ISSUE TITLE
armv7l Raspbian buster: Invalid bitcode signature

### ISSUE THREAD

**Issue by alanmikhak** [ispc/ispc#1612]
I observed the following error while building ispc 1.12.0 from sources using the build.sh script on a Raspberry Pi 4 Model B running Raspbian 10 (buster) OS on a 32-bit armv7l Linux kernel.

[ 32%] Generating builtins-c-32-macos-armv7.cpp
1 error generated.
/home/pi/src/github.com/ispc/ispc/llvm/bin-8.0/bin/llvm-dis: error: Invalid bitcode signature

Please see minute 4:57 of the following video on my YouTube channel for an occurrence of this specific error I observed during the build process:
https://youtu.be/4odfdd8opqs

The build.sh script completed producing an ispc binary. However, none of the ispc examples would compile with the resulting binary.

**Comment by alanmikhak** [comment]
Please see #1611 for machine information and build.sh script output

**Comment by dbabokin** [comment]
Same as #1614 - it's just a consequence of error in #1611. Fix to explicitly fail is in PR #1616.

**Comment by alanmikhak** [comment]
Thanks for the quick response. Resolving as duplicate of #1611.
