### ISSUE TITLE
armv7l Raspbian buster: warning: deprecated directive, use ‘%define parse.error verbose’

### ISSUE THREAD

**Issue by alanmikhak** [ispc/ispc#1613]
I observed the following warning while building ispc 1.12.0 from sources using the build.sh script on a Raspberry Pi 4 Model B running Raspbian 10 (buster) OS on a 32-bit armv7l Linux kernel.

[ 45%] Generating parse.cc
src/parse.yy:40.1-14: warning: deprecated directive, use ‘%define parse.error verbose’ [-Wdeprecated]
 %error-verbose
 ^~~~~~~~~~~~~~
src/parse.yy: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
Scanning dependencies of target ispc
[ 47%] Building CXX object CMakeFiles/ispc.dir/builtins-target-sse2-i32x4-32bit-unix.cpp.o

Please see minute 5:15 of the following video on my YouTube channel for an occurrence of this specific warning I observed during the build process:
https://youtu.be/4odfdd8opqs

The build.sh script completed producing an ispc binary. However, none of the ispc examples would compile with the resulting binary.

**Comment by alanmikhak** [comment]
> error

ning

**Comment by alanmikhak** [comment]
Please see #1611 for machine information and build.sh script output.

**Comment by dbabokin** [comment]
It's known issue, warning appears with bison version 3.0 and later. It's already fixed in master (commit [0c4db5bef5](https://github.com/dbabokin/ispc/commit/0c4db5bef5d18c9d60461f682aae4d8340fba5b9)).

**Comment by alanmikhak** [comment]
Verified. Not seeing this warning when executing build.sh script from master branch.
