### ISSUE TITLE
armv7l Raspbian buster: Undeclared symbol "__num_cores" when compiling examples

### ISSUE THREAD

**Issue by alanmikhak** [ispc/ispc#1614]
I observed the following error while building ispc 1.12.0 from sources using the build.sh script on a Raspberry Pi 4 Model B running Raspbian 10 (buster) OS on a 32-bit armv7l Linux kernel.

$ cd /home/pi/src/github.com/ispc/ispc/examples
$ export PATH=~/src/github.com/ispc/ispc/install/bin:$PATH
$ ispc --version
Intel(r) SPMD Program Compiler (ispc), 1.12.0 (build commit 2a3fc60c1c60008d @ 20191201, LLVM 8.0.0)

$ cmake .
:::

$ make
[  1%] Generating ao_ispc.h, ao_ispc.o
stdlib.ispc:1549:12: Error: Undeclared symbol "__num_cores". Did you mean "num_cores"? 
stdlib.ispc:1546:3: Error: Must provide return value for return statement for non-void function. 
make[2]: *** [aobench/CMakeFiles/aobench.dir/build.make:63: aobench/ao_ispc.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:90: aobench/CMakeFiles/aobench.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Please see minute 6:58 of the following video on my YouTube channel for an occurrence of this specific error I observed during the build process:
https://youtu.be/4odfdd8opqs

The ispc build.sh script completed producing an ispc binary. However, none of the ispc examples would compile with the resulting binary.

**Comment by alanmikhak** [comment]
Please see #1611 for machine information and build.sh script output.

**Comment by dbabokin** [comment]
This is because of errors in #1568 

Though there's a minor problem here, that the build didn't fail, but generated invalid ispc binary. I'll fix that.

**Comment by alanmikhak** [comment]
Resolving as duplicate of #1611. Thanks for the quick responses.
