### ISSUE TITLE
aarch64 Raspbian buster: Fatal error: can't configure release version

### ISSUE THREAD

**Issue by alanmikhak** [ispc/ispc#1615]
I observed the following error while building ispc 1.12.0 from sources using the build.sh script on a Raspberry Pi 4 Model B running 32-bit Raspbian 10 (buster) OS on a 64-bit aarch64 Linux kernel.

Trying to configure release version ERROR.
Fatal error: can't configure release version

**Comment by alanmikhak** [comment]
Machine information:

$ # Linux aarch64 kernel
$ uname -a
Linux rpi5 4.19.81-v8+ #1276 SMP PREEMPT Fri Nov 1 14:37:55 GMT 2019 aarch64 GNU/Linux

$ # Raspbian GNU/Linux 10 (buster)
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

$ # 128GB micro-SD card
$ df -H
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       126G   29G   92G  24% /
devtmpfs        1.9G     0  1.9G   0% /dev
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           2.0G  182M  1.8G  10% /run
tmpfs           5.3M  4.1k  5.3M   1% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/mmcblk0p1  265M   55M  210M  21% /boot
tmpfs           394M  4.1k  394M   1% /run/user/1000

$ # 4GB RAM
$ free -h
              total        used        free      shared  buff/cache   available
Mem:          3.7Gi       201Mi       3.0Gi       192Mi       489Mi       3.2Gi
Swap:          99Mi        69Mi        30Mi

**Comment by alanmikhak** [comment]
build.sh script output:

####################################################################
## ./scripts/build.sh details (aarch64)
####################################################################

$ ./scripts/build.sh -v 8.0
Warning: you ISPC_HOME and your current path are different! (/home/pi/src/github.com/ispc/ispc/scripts/.. is not equal to /home/pi/src/github.com/ispc/ispc)

Building LLVM. Version: 8.0. 
Using folders: llvm-8.0 build-8.0 bin-8.0 in /home/pi/src/github.com/ispc/ispc/scripts/../llvm
Trying to clone llvm from https://github.com/llvm/llvm-project.git to llvm-8.0 DONE.
Trying to switch to llvmorg-8.0.0 tag DONE.
Trying to patch LLVM with patch /home/pi/src/github.com/ispc/ispc/scripts/../llvm_patches/8_0_issue1454_windows_O0.patch DONE.
Trying to patch LLVM with patch /home/pi/src/github.com/ispc/ispc/scripts/../llvm_patches/8_0_r362675.patch DONE.
Making selfbuild and use folders build-8.0_temp and bin-8.0_temp
Trying to configure release version for selfbuild DONE.
Trying to build release version for selfbuild DONE.
Trying to install release version for selfbuild DONE.
Now we have compiler for selfbuild:   -DCMAKE_C_COMPILER=/home/pi/src/github.com/ispc/ispc/scripts/../llvm/bin-8.0_temp/bin/clang   -DCMAKE_CXX_COMPILER=/home/pi/src/github.com/ispc/ispc/scripts/../llvm/bin-8.0_temp/bin/clang++ 
Trying to configure release version ERROR.
Fatal error: can't configure release version 
Logs are in alloy_results_2019_12_01_13_24_54
-- Build type not specified: Use Release by default.
-- Found LLVM LLVM_7_0
-- LLVM_CONFIG_EXECUTABLE: /usr/lib/llvm-7/bin/llvm-config
-- CLANG_EXECUTABLE: /usr/lib/llvm-7/bin/clang
-- LLVM_DIS_EXECUTABLE: /usr/lib/llvm-7/bin/llvm-dis
-- LLVM_AS_EXECUTABLE: /usr/lib/llvm-7/bin/llvm-as
CMake Error at cmake/LLVMConfig.cmake:76 (message):
  Failed to find FileCheck
Call Stack (most recent call first):
  CMakeLists.txt:116 (include)


-- Configuring incomplete, errors occurred!
See also "/home/pi/src/github.com/ispc/ispc/build/CMakeFiles/CMakeOutput.log".

**Comment by dbabokin** [comment]
Logs in alloy_results_2019_12_01_13_24_54 should have more details, please paste here the tail of alloy_results_2019_12_01_13_24_54/alloy_build.log

**Comment by alanmikhak** [comment]
I am running build.sh script again to collect alloy_results logs. I cleaned up after the previous run so alloy_results_2019_12_01_13_24_54 listed in earlier comment is no longer available. It takes overnight for  native build to run single-threaded on my Raspberry Pi 4 model B.

**Comment by alanmikhak** [comment]
Please see below 50 lines from tail of alloy_results_2019_12_02_02_27_14/alloy_build.log from a new run:

-- Installing: /home/pi/src/github.com/ispc/ispc/llvm/bin-8.0_temp/lib/cmake/llvm/./VersionFromVCS.cmake
-- Installing: /home/pi/src/github.com/ispc/ispc/llvm/bin-8.0_temp/lib/cmake/llvm/./FindOCaml.cmake
-- Installing: /home/pi/src/github.com/ispc/ispc/llvm/bin-8.0_temp/lib/cmake/llvm/./CheckAtomic.cmake
-- Installing: /home/pi/src/github.com/ispc/ispc/llvm/bin-8.0_temp/lib/cmake/llvm/./FindLibpfm.cmake
DONE.
Now we have compiler for selfbuild:   -DCMAKE_C_COMPILER=/home/pi/src/github.com/ispc/ispc/scripts/../llvm/bin-8.0_temp/bin/clang   -DCMAKE_CXX_COMPILER=/home/pi/src/github.com/ispc/ispc/scripts/../llvm/bin-8.0_temp/bin/clang++
Command line: cmake -G "Unix Makefiles" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DCMAKE_C_COMPILER=/home/pi/src/github.com/ispc/ispc/scripts/../llvm/bin-8.0_temp/bin/clang   -DCMAKE_CXX_COMPILER=/home/pi/src/github.com/ispc/ispc/scripts/../llvm/bin-8.0_temp/bin/clang++   -DCMAKE_INSTALL_PREFIX=/home/pi/src/github.com/ispc/ispc/scripts/../llvm/bin-8.0  -DCMAKE_BUILD_TYPE=Release  -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_ENABLE_DUMP=ON   -DLLVM_ENABLE_ASSERTIONS=ON  -DLLVM_INSTALL_UTILS=ON  -DLLVM_TARGETS_TO_BUILD=AArch64\;ARM\;NVPTX\;X86 ../llvm-8.0/llvm
Trying to configure release version -- The C compiler identification is Clang 8.0.0
-- The CXX compiler identification is Clang 8.0.0
-- The ASM compiler identification is Clang
-- Found assembler: /home/pi/src/github.com/ispc/ispc/scripts/../llvm/bin-8.0_temp/bin/clang
-- Check for working C compiler: /home/pi/src/github.com/ispc/ispc/scripts/../llvm/bin-8.0_temp/bin/clang
-- Check for working C compiler: /home/pi/src/github.com/ispc/ispc/scripts/../llvm/bin-8.0_temp/bin/clang -- broken
CMake Error at /usr/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/home/pi/src/github.com/ispc/ispc/scripts/../llvm/bin-8.0_temp/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/pi/src/github.com/ispc/ispc/llvm/build-8.0/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/make" "cmTC_9494f/fast"
    /usr/bin/make -f CMakeFiles/cmTC_9494f.dir/build.make CMakeFiles/cmTC_9494f.dir/build
    make[1]: Entering directory '/home/pi/src/github.com/ispc/ispc/llvm/build-8.0/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_9494f.dir/testCCompiler.c.o
    /home/pi/src/github.com/ispc/ispc/scripts/../llvm/bin-8.0_temp/bin/clang    -o CMakeFiles/cmTC_9494f.dir/testCCompiler.c.o   -c /home/pi/src/github.com/ispc/ispc/llvm/build-8.0/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_9494f
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9494f.dir/link.txt --verbose=1
    /home/pi/src/github.com/ispc/ispc/scripts/../llvm/bin-8.0_temp/bin/clang      CMakeFiles/cmTC_9494f.dir/testCCompiler.c.o  -o cmTC_9494f
    /usr/bin/ld: unrecognised emulation mode: aarch64linux
    Supported emulations: armelf_linux_eabi armelfb_linux_eabi
    clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [CMakeFiles/cmTC_9494f.dir/build.make:87: cmTC_9494f] Error 1
    make[1]: Leaving directory '/home/pi/src/github.com/ispc/ispc/llvm/build-8.0/CMakeFiles/CMakeTmp'
    make: *** [Makefile:121: cmTC_9494f/fast] Error 2




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:39 (project)


-- Configuring incomplete, errors occurred!
See also "/home/pi/src/github.com/ispc/ispc/llvm/build-8.0/CMakeFiles/CMakeOutput.log".
See also "/home/pi/src/github.com/ispc/ispc/llvm/build-8.0/CMakeFiles/CMakeError.log".
ERROR.

**Comment by alanmikhak** [comment]
Looked for llvm CMakeOutput.log and CMakeError.log mentioned in alloy_results log but there is not much left in the llvm directory:

$ ls /home/pi/src/github.com/ispc/ispc/llvm
bin-8.0
$ ls /home/pi/src/github.com/ispc/ispc/llvm/bin-8.0/
$

**Comment by dbabokin** [comment]
I can reproduce the issue. Looks like we are building clang with wrong options, so it doesn't properly support aarch64. I need to find a recipe how to properly to build clang to target aarch64.

**Comment by alanmikhak** [comment]
I came across a similar issue when trying to build ispc 1.12.1dev from master branch on my FriendlyElec Nano Pi M4 running the FriendlyDesktop on Ubuntu 18.04 on aarch64 Linux kernel.

$ git diff cmake/GenerateBuiltins.cmake 
diff --git a/cmake/GenerateBuiltins.cmake b/cmake/GenerateBuiltins.cmake
index f55cb6fe..aa5373a5 100644
--- a/cmake/GenerateBuiltins.cmake
+++ b/cmake/GenerateBuiltins.cmake
@@ -219,7 +219,7 @@ function(builtin_to_cpp bit os_name arch supported_archs supported_oses resultFi
     else()
         add_custom_command(
             OUTPUT ${output}
-            COMMAND ${CLANG_EXECUTABLE} ${target_flags} -w -m${bit} -emit-llvm -c ${inputFilePath} -o - | (\"${LLVM_DIS_EXECUTABLE}\" - || echo "builtins.c compile error")
+            COMMAND ${CLANG_EXECUTABLE} ${target_flags} -w -m${bit} -emit-llvm -I/usr/include/aarch64-linux-gnu/ -c ${inputFilePath} -o - | (\"${LLVM_DIS_EXECUTABLE}\" - || echo "builtins.c compile error")
                 | \"${Python3_EXECUTABLE}\" bitcode2cpp.py c --runtime=${bit} --os=${os_name} --arch=${target_arch} --llvm_as ${LLVM_AS_EXECUTABLE}
                 > ${output}
             DEPENDS ${inputFilePath} bitcode2cpp.py

$ ./scripts/build.sh -v 8.0
Warning: you ISPC_HOME and your current path are different! (/home/pi/src/github.com/ispc/ispc/scripts/.. is not equal to /home/pi/src/github.com/ispc/ispc)

Building LLVM. Version: 8.0. 
Using folders: llvm-8.0 build-8.0 bin-8.0 in /home/pi/src/github.com/ispc/ispc/scripts/../llvm
Trying to clone llvm from https://github.com/llvm/llvm-project.git to llvm-8.0 DONE.
Trying to switch to llvmorg-8.0.1 tag DONE.
Trying to patch LLVM with patch /home/pi/src/github.com/ispc/ispc/scripts/../llvm_patches/8_0_9_0_Fix_for_1595.patch DONE.
Trying to patch LLVM with patch /home/pi/src/github.com/ispc/ispc/scripts/../llvm_patches/8_0_issue1454_windows_O0.patch DONE.
Trying to patch LLVM with patch /home/pi/src/github.com/ispc/ispc/scripts/../llvm_patches/8_0_r362675.patch DONE.
Making selfbuild and use folders build-8.0_temp and bin-8.0_temp
Trying to configure release version for selfbuild DONE.
Trying to build release version for selfbuild ERROR.
Fatal error: can't build release version for selfbuild 
Logs are in alloy_results_2019_12_08_17_19_43
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type not specified: Use Release by default.
-- Found LLVM LLVM_6_0
-- LLVM_CONFIG_EXECUTABLE: /usr/lib/llvm-6.0/bin/llvm-config
-- CLANG_EXECUTABLE: /usr/lib/llvm-6.0/bin/clang
-- LLVM_DIS_EXECUTABLE: /usr/lib/llvm-6.0/bin/llvm-dis
-- LLVM_AS_EXECUTABLE: /usr/lib/llvm-6.0/bin/llvm-as
CMake Error at cmake/LLVMConfig.cmake:76 (message):
  Failed to find FileCheck
Call Stack (most recent call first):
  CMakeLists.txt:132 (include)


-- Configuring incomplete, errors occurred!
See also "/home/pi/src/github.com/ispc/ispc/build/CMakeFiles/CMakeOutput.log".

**Comment by alanmikhak** [comment]
Based on more observations of FileCheck error in issue #1611 while building ispc 1.14.0dev on other aarch64 machines, the FileCheck error occurs when the system runs out of memory while building LLVM. Enabling a large enough swap file, at least 2GB on a Raspberry Pi 4 Model B with 4GB of RAM, should resolve this issue with ispc 1.14.0dev.

Closing.
