### ISSUE TITLE
AMD CPU support

### ISSUE THREAD

**Issue by NPCompress** [ispc/ispc#1619]
Is it possible to add AMD znver1 & znver2 architecture support?

**Comment by dbabokin** [comment]
It's not a big deal to add Zen CPU definitions. By the way we already have one AMD definition for btver2 (which the CPU used in PS4).

Note that the main effect comes from ISA being used, not from CPU tuning. Most of users don't use ``--cpu``.

Anyway, pull requests are welcome.
