### ISSUE TITLE
ISPC crash using soa > programCount

### ISSUE THREAD

**Issue by JeffRous** [ispc/ispc#1627]
ISPC crashes on trunk with the following code on avx2-i32x4 (or any other 4-wide mode) and works on 8-wide targets.

https://ispc.godbolt.org/z/5CScFf

**Comment by DeepakRajendrakumaran** [comment]
The crash happens in llvm while running sroa opt pass. This crash seem to have  been suppressed with a recent fix - https://bugs.llvm.org/show_bug.cgi?id=42585 (I've not tested this yet)

But looking at the IR/ispc code, I'm not sure we are actually creating correct LLVM IR either. Looking into this.

**Comment by DeepakRajendrakumaran** [comment]
Reduced IR to reproduce the crash - https://godbolt.org/z/wCgJmN . Running the IR there locally with opt and -sroa reproduces the crash.
We are bitcasting <4 x float>* to <8 x float>*
this is a direct result of the original ispc code where we typecast -
*((uniform FVector8 *uniform)&S0) = *((uniform FVector8 *uniform)&A);

**Comment by DeepakRajendrakumaran** [comment]
Fixed in trunk.
