### ISSUE TITLE
Missing const pointer overloads for aos_to_soaX

### ISSUE THREAD

**Issue by est77** [ispc/ispc#1631]
Sample code fragment:

```c
const uniform float* uniform src = src_pixels;
for (uniform unsigned int i = 0; i < width; i += programCount)
{
    float r, g, b, a;
    aos_to_soa4(&src[i], &r, &g, &b, &a);
}
```

fails to compile with the following error:

Error: Unable to find any matching overload for call to function "aos_to_soa4". 
Passed types: (const uniform float * uniform, varying float * uniform, varying float * uniform, varying float * uniform, varying float * uniform) 

casting the first argument to (uniform float* uniform) fixes the error.

**Comment by DeepakRajendrakumaran** [comment]
There are a couple of issues here
1. Our algorithm for finding matching function doesn't correctly identify matching function with const pointer argument
2. Even after matching the function, our type conversion has trouble realizing this is a valid conversion.

Have an initial fix but needs to check different scenarios to ensure it doesn't break anything.

**Comment by DeepakRajendrakumaran** [comment]
Closing this as fixed - https://github.com/ispc/ispc/commit/9422b4649ed87cfaf3c4b3e50c7f4bddbedaa756

Reopen if not.
