### ISSUE TITLE
@<filename> doesn't support quotes arguments

### ISSUE THREAD

**Issue by Unit2Ed** [ispc/ispc#1638]
To workaround issues with command-lines being too long, I'm using @<filename>-style compiler invocation. Unfortunately this doesn't work well with arguments that contain spaces - eg `-I`.

This is my reduced sample that demonstrates the problem:

```
"C:\MyProject\Source\Test.ispc"
-h "C:\MyProject\Source\Test.ispc.generated.h"
--arch=x86_64
--target=avx2,avx,sse4,sse2
-I "C:\MyProject\Third Party\Source"
```
Produces the following output:
```
C:\MyProject\Third Party\ispc>ispc.exe "@C:\MyProject\Build\Test.ispc.response"
Multiple input files specified on command line: ""C:\MyProject\Source\Test.ispc"" and "Party\Source"".
```

ispc is splitting the last argument in two - `-I "C:\MyProject\Third` and `Party\Source"`.

When written onto the command-line normally this isn't an issue because the OS/C-runtime takes care of splitting the arguments into individual strings, keeping quoted parts together.

**Comment by dbabokin** [comment]
We'll definitely need to fix that. But I assume if we fix an issue with number of arguments, this will not block you, right?

**Comment by Unit2Ed** [comment]
Unfortunately the amount of command-line I need to pass is 53KB, which exceeds the Windows limit of 32KB. At the moment an @ file is the only option I have available.

I'm working to reduce the amount, but it requires some major structural changes to the project to get a decent win.

**Comment by dbabokin** [comment]
@Unit2Ed #1641 should fix the problem. Could you please try the latest build and confirm that it works for you?

**Comment by Unit2Ed** [comment]
@dbabokin Yep, that's fixed it - thanks for the quick turnaround!
