### ISSUE TITLE
Question about headers

### ISSUE THREAD

**Issue by kingofthebongo2008** [ispc/ispc#1645]
Hello,
How ispc can spill out the headers that it includes.
I need it to write a custom MsBuild task which tracks the dependencies of the files.
The examples of integration of ispc with msbuild can be improved i guess.
What do you think in general about this issue?

**Comment by dbabokin** [comment]
Are these ispc options not enough?
```
    [-MMM <filename>]			Write #include dependencies to given file.
    [-M]				Output a rule suitable for `make' describing the dependencies of the main source file to stdout.
    [-MF <filename>]			When used with `-M', specifies a file to write the dependencies to.
    [-MT <filename>]			When used with `-M', changes the target of the rule emitted by dependency generation.
```

What is default solution that you would use with C/C++ compilers?

**Comment by kingofthebongo2008** [comment]
all good, thank you

**Comment by dbabokin** [comment]
Please reopen if you have more questions or these switches are not enough.
