### ISSUE TITLE
Can't include paths with white space in response file

### ISSUE THREAD

**Issue by RDurandEpic** [ispc/ispc#1650]
I'm running a command that has a high number of include paths out of necessity so I am trying to use a response file. The problem is some of these paths will be to paths in C:\Program Files (x86)\ and the response file doesn't support arguments with white space so those paths don't work. Rather than hack in special cases when generating the response file to not add those paths and instead include them normally on the command line, can this be corrected? I was pretty floored to find out this isn't a thing that is supported.

**Comment by dbabokin** [comment]
Try the latest build: https://ci.appveyor.com/api/projects/ispc/ispc/artifacts/build%2Fispc-trunk-windows.zip?job=Environment%3A%20APPVEYOR_BUILD_WORKER_IMAGE%3DVisual%20Studio%202017%2C%20LLVM_VERSION%3Dlatest

This supposed to be fixed already. Originally reported in https://github.com/ispc/ispc/issues/1638

**Comment by RDurandEpic** [comment]
Thanks, I had grabbed the latest from https://ispc.github.io/downloads.html, didn't think to check for a new build via their CI.

**Comment by RDurandEpic** [comment]
Maybe I'm just blind, is there a Mac build somewhere as well? I need Linux, Mac, and Windows.

**Comment by dbabokin** [comment]
Not yet, we haven't enabled Mac build in CI yet (planning to do that shortly).

I can build the package for you manually (with macOS and iOS support).

**Comment by RDurandEpic** [comment]
That would be great! Much appreciated!

**Comment by dbabokin** [comment]
Here's the link for macOS binaries (targeting macOS + iOS): https://drive.google.com/open?id=1RBV7YAtL0jE9hufm3YZ7_ZFaRpbYV4WJ
