### ISSUE TITLE
extract/insert functions are missing for bool type

### ISSUE THREAD

**Issue by dbabokin** [ispc/ispc#1659]
We need the following functions in stdlib:
```
uniform bool extract(bool x, uniform int i);
bool insert(bool x, uniform int i, uniform bool v);
```

**Comment by dbabokin** [comment]
Fixed by #1700

**Comment by dbabokin** [comment]
Reopening - need to fix documentation. @DeepakRajendrakumaran

**Comment by DeepakRajendrakumaran** [comment]
Just this - https://github.com/ispc/ispc/pull/1716 or something else needed?

**Comment by dbabokin** [comment]
We can close now.
