### ISSUE TITLE
In LLVM 11.0+ optimization breaks LLVMVectorIsLinear

### ISSUE THREAD

**Issue by aschrein** [ispc/ispc#1673]
[This optimization](https://github.com/llvm/llvm-project/blob/1badf7c33a5d01900c77646f750e2ea11ad8bf5a/llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp#L1313) is triggered on LLVM 11.
```c++
// A+B --> A|B iff A and B have no bits set in common.
if (haveNoCommonBitsSet(LHS, RHS, DL, &AC, &I, &DT))
  return BinaryOperator::CreateOr(LHS, RHS);
```
```asm
%iter_val24 = add <4 x i32> %smear_counter23, <i32 0, i32 1, i32 2, i32 3>
; is transformed into
%iter_val24 = or <4 x i32> %smear_counter23, <i32 0, i32 1, i32 2, i32 3>
```
And lVectorIsLinear does not handle bop->getOpcode() == llvm::Instruction::Or which leads to gathers being generated.
In LLVM proving that two values have no bits in common involves quite a lot of code. I propose just changing the order of optimizations as a temporal remedy:
```c++
// At src/opt.cpp:517
// From
       if (g->opt.disableGatherScatterOptimizations == false && g->target->getVectorWidth() > 1) {
            optPM.add(llvm::createInstructionCombiningPass(), 210);
            optPM.add(CreateImproveMemoryOpsPass());
        }
// To
        if (g->opt.disableGatherScatterOptimizations == false && g->target->getVectorWidth() > 1) {
            optPM.add(CreateImproveMemoryOpsPass());
            optPM.add(llvm::createInstructionCombiningPass(), 210);
        }
```

**Comment by aschrein** [comment]
>> In LLVM proving that two values have no bits in common involves quite a lot of code
Actually this code is exported and could be reused. I'll look if we could leverage it.

**Comment by DeepakRajendrakumaran** [comment]
https://github.com/DeepakRajendrakumaran/ispc/commits/llvm11 fixes a few other cases. This si not the final change and still needs some addition. Will update issue here once change is final.

**Comment by dbabokin** [comment]
@DeepakRajendrakumaran is #1683 fixing all known issues? I think we can close this issue.

**Comment by DeepakRajendrakumaran** [comment]
Yep..this particular issue should be fixed. I did not see any warnings as of last week.
