### ISSUE TITLE
'const float<3>&' parameter causes compiler assertion 'exprType != NULL' to fail

### ISSUE THREAD

**Issue by MrAnderssonSwe** [ispc/ispc#1711]
The following two functions compile fine in version 1.12.0 but triggers an assert when compiled using trunk.

```
inline float foo(const float<3>& v)
{
	return v.x + v.y + v.z;
}

inline float<3> bar(const float<3>& v)
{
	//return v * foo(v); // Compiles
	return 2.0f * v * foo(v); // Doesn't compile
}
```
_Command line_
ispc.exe -O2 --arch=x86-64 --opt=disable-assertions --opt=force-aligned-memory --opt=fast-math --math-lib=default --target=avx2-i32x8 Bug.ispc -o Bug.obj -h Bug.h

_Output_
Bug.ispc:9:9: Error: Implicit conversion from type "const varying float" to "const varying float<3> &" for * not possible.
 return 2.0f * v * foo(v); // Doesn't compile
        ^^^^^^^^

Bug.ispc:9:9: Error: Assertion failed (C:\projects\ispc\src\expr.cpp:1961): "exprType != NULL".
 return 2.0f * v * foo(v); // Doesn't compile

**Comment by dbabokin** [comment]
Fixed.
