### ISSUE TITLE
Compile time crash when processing initialization by &array[x]

### ISSUE THREAD

**Issue by dbabokin** [ispc/ispc#1717]
Reproducer:
```c
static uniform int arr[256];

static void foo(uint32 r) {
    int *pEr = &arr[r];
}
```

Bug starts after this commit https://github.com/ispc/ispc/commit/e1191d04f0200449966354fcd5e3153f33b8e7f5

**Comment by DeepakRajendrakumaran** [comment]
Basically, the problem here was that were not checking if the index expression was a constant before using it.

**Comment by dbabokin** [comment]
Fixed.
