### ISSUE TITLE
Binary releases for old versions

### ISSUE THREAD

**Issue by mattgodbolt** [ispc/ispc#1735]
Hi,

I run and administrate Compiler Explorer and we have scripts to install `ispc` of all versions we support. As I was upgrading to 1.13.0 I noticed the installation for all previous versions (previously hosted at `https://sourceforge.net/projects/ispcmirror/files/v{name}/ispc-v{name}-linux.tar.gz/download`) are now gone.

Although we have these installed already, it would be really useful if we could have a place to pick up the older releases, should we ever need to reinstall, or should anyone ever want to run a local copy of the site. (see https://github.com/mattgodbolt/compiler-explorer-image/blob/master/bin/yaml/ispc.yaml for our installation configuration).

Thanks, Matt

**Comment by cloudhan** [comment]
Here you are, for example v1.12.0
https://github.com/ispc/ispc/releases/download/v1.12.0/ispc-v1.12.0b-linux.tar.gz
you can find them at [release page](https://github.com/ispc/ispc/releases)

**Comment by dbabokin** [comment]
Correct, we've moved our downloads to github release, so old versions are available there as well.

@mattgodbolt thank you for updating to v1.13 on Compiler Explorer!

**Comment by mattgodbolt** [comment]
Fantastic! Thanks folks, will update my installation scripts accordingly!
