### ISSUE TITLE
soa qualifier on nested structures in export functions generates invalid header

### ISSUE THREAD

**Issue by floeffler** [ispc/ispc#1738]
Hey guys,

I found a little bug in the generation of the header file when using the soa qualifier in an export function on a nested structure. The bug can be easily reproduced with the small piece of code:

```
struct vec3f {
	float x, y, z;
};

struct linear_space {
	vec3f vx;
	vec3f vy;
	vec3f vz;
};

export void generate_linear_spaces(soa<16> linear_space& spaces) {

	foreach(i = 0 ... 16) {
		// fill spaces
	}
}
```

The generated header code contains the following invalid definition:
```
struct vec3f_SOA16 {
    float x[16];
    float y[16];
    float z[16];
};
struct linear_space_SOA16 {
    struct vec3f vx_SOA16;
    struct vec3f vy_SOA16;
    struct vec3f vz_SOA16;
};
```
It's just a little issue. the _SOA16 name extension is added to the member variables instead of the member type. I've test it with ISPC 1.13.0 and 1.12.0. Both have the same behavior. I know there are several ways to avoid this, however, it would be really nice if you could fix it for the next version.

**Comment by dbabokin** [comment]
Nice catch, we'll fix that.
