### ISSUE TITLE
ISPC 1.13 fails to compile sources which 1.12 compiles fine

### ISSUE THREAD

**Issue by petrsm** [ispc/ispc#1747]
Attached are the files which compiles fine with ISPC 1.12, but with 1.13 following error is printed:
Assertion failed: castIsValid(getOpcode(), S, Ty) && "Illegal SExt", file D:\users\aneshlya\llvm\llvm-10.0\llvm\lib\IR\Instructions.cpp, line 3326

Thanks for looking into it :)
[repro.zip](https://github.com/ispc/ispc/files/4577056/repro.zip)

**Comment by DeepakRajendrakumaran** [comment]
This was introduced by the bool changes and is specific to vector of varying bools.
This in IR is 'array of vectors ' and we try toTrunc/SeXT  these during load/store

**Comment by DeepakRajendrakumaran** [comment]
https://godbolt.org/z/ypycU-

This is a fairly simple case which needs to have a test added.
