### ISSUE TITLE
Assertion `V.getNode() && "Getting TableId on SDValue()"' failed.

### ISSUE THREAD

**Issue by Vsevolod-Livinskij** [ispc/ispc#1767]
ISPC fails with
> \>$ispc --target=avx2-i32x16 -o func.o func.ispc
 ispc: /llvm-10.0/llvm/lib/CodeGen/SelectionDAG/LegalizeTypes.h:137: llvm::DAGTypeLegalizer::TableId llvm::DAGTypeLegalizer::getTableId(llvm::SDValue): Assertion `V.getNode() && "Getting TableId on SDValue()"' failed.

Reproducer:
```c++
extern uniform bool arr_4 [17];
export void test(uniform int64 var_1, uniform bool var_15) {
    foreach(i_0 = var_1...16U)
        arr_4 [i_0] = !(varying bool) reduce_min(180) ? 5923697687793782713ULL : (varying bool) var_15;
}
```

ISPC version:
1.14.0dev (build commit 763adc5a026a3d07 @ 20200526, LLVM 10.0.0)

**Comment by DeepakRajendrakumaran** [comment]
This is a llvm codegen crash with O2 opt. It's fine with O0. Might possibly be a llvm thing. Have to confirm.

**Comment by DeepakRajendrakumaran** [comment]
This has already been fixed in llvm trunk - https://reviews.llvm.org/D76994

@dbabokin  you want me to go ahead and port the patch?

**Comment by dbabokin** [comment]
Yes.
