### ISSUE TITLE
Uniform and varying types have different rounding rules.

### ISSUE THREAD

**Issue by Vsevolod-Livinskij** [ispc/ispc#1768]
ISPC uses different rounding approaches for uniform and varying types. Uniform types are rounded to 0 and varying types are rounded to minus inf. It happens in case of negative values that have a remainder. 

> \>$ispc foo.ispc -o foo.o --target=avx2-i32x4 && clang++ main.cpp foo.o && ./a.out
-1
[-2,-2,-2,-2]

Reproducer:
foo.ispc
```c++
uniform int i = -13;

export void foou() {
    uniform int inp = i;
    uniform int res = inp / 12;
    print("%\n", res);

}

export void foov() {
    varying int inp = i;
    varying int res = inp / 12;
    print("%\n", res);
}
```

main.cpp
```c++
extern "C" { void foou(); void foov(); };

int main() {
    foou();
    foov();
}
```

ISPC version:
1.14.0dev (build commit 763adc5a026a3d07 @ 20200526, LLVM 10.0.0)

**Comment by DeepakRajendrakumaran** [comment]
The reason for this happening is us using the fast division algorithm in '__fast_idiv' for varying and constant folding for uniform. In this case,ideally the fast div should also have returned -1

**Comment by dbabokin** [comment]
The point is that __fast_idiv algorithm seem to have a bug.

**Comment by DeepakRajendrakumaran** [comment]
https://gmplib.org/~tege/divcnst-pldi94.pdf - this is the paper with the algorithm. We seem to be using the division algorithm that rounds to -infinity. So,
-13/12 = -2
13/12 = 1
-26/12 = 2
-23/12 = 1

So, the algorithm is working as designed.

**Comment by DeepakRajendrakumaran** [comment]
The problem we have is that the algorithm rounds to -infinity while the normal
sdiv -13, 12 yields -1 since it rounds differently

**Comment by dbabokin** [comment]
The paper has two algorithms - rounding to 0 (section 5) and to -inf (section 6). I guess we need to use rounding towards 0. We should not deviate from hardware instructions.

**Comment by dbabokin** [comment]
Also, it worth checking if not implementing this algorithm in FE would trigger this transformation in BE. This kind of optimizations really belongs to BE, I would expect BE to do it for us.

**Comment by DeepakRajendrakumaran** [comment]
That's my understanding too- that BE handles it anyway. I disabled the fast_div path and checked the assembly created with O2. the backend created 'idiv' only when dividend is not a constant.  I'll verify this with Craig.

**Comment by dbabokin** [comment]
This needs a benchmarks measuring performance of the division by a constant (in benchmarks/01_trivial folder).
