### ISSUE TITLE
Define types in a separate ispc file

### ISSUE THREAD

**Issue by lili2012** [ispc/ispc#1789]
I want to define some struct types in one file and include it in both ispc file and c++ files. Could I do that? What is the best practice to share self define types between ispc file and c++ files

**Comment by dbabokin** [comment]
The recommended way to handle it is to define types in .ispc file and generate C++ header with exported data types (see ``-h`` switch for ``ispc``).

Technically you can include the same header to both *.ispc and *.cpp, but you'll need to handle the difference between languages yourself (for example, ensure that type are properly qualified with ``uniform`` for ispc).
