### ISSUE TITLE
ISPC can't resolve stdlib call.

### ISSUE THREAD

**Issue by Vsevolod-Livinskij** [ispc/ispc#1801]
ISPC has some troubles with standard library calls (min, max, and probably others) for avx512skx-i16x32 and avx512skx-i8x64. Everything works fine for other architectures. 
Error:
>\>$ ispc foo.ispc --target=avx512skx-i16x32 -woff
foo.ispc:2:5: Error: Multiple overloaded functions matched call to function "min". 
        Passed types: (const uniform int16, const uniform unsigned int16) 
        Candidate: /*safe*/ /*cost=1*/ uniform unsigned int16(uniform unsigned int16, uniform unsigned int16) 
        Candidate: /*safe*/ /*cost=1*/ uniform int16(uniform int16, uniform int16) 
    min(18517, 36195);
    ^^^

Reproducer:
```c++
void foo() {
    min(18517, 36195);
}
```

ISPC version:
1.14.0dev (build commit fb8e7e82117f20a5 @ 20200620, LLVM 10.0.0) + da679386632e25bfb9d82de7f4cd9b9d88e8c937

**Comment by dbabokin** [comment]
For i8 and i16 targets constants are treated slightly differently. For i8 target if the constant is less than ``0x7f``, it's treated as ``int8``, if it's less than ``0xff``, it's ``unsigned int8``. Constant are not truncated, but their type is treated differently. Hence, there might be problems with overloads, as we see in this case. Pay attention to this piece of error:
> Passed types: (const uniform int16, const uniform unsigned int16)

This is quite tricky part of language definition.

**Comment by dbabokin** [comment]
Just in case, the logic to parse integer constants and determine their types is here: https://github.com/ispc/ispc/blob/master/src/lex.ll#L659
