### ISSUE TITLE
[GCC/Linux] Building fails because of clang only compile flag

### ISSUE THREAD

**Issue by DarkDefender** [ispc/ispc#1828]
I'm trying to build ispc with GCC 9.2.0, however it fails with:
`x86_64-pc-linux-gnu-g++: error: unrecognized command line option ‘-fno-strict-float-cast-overflow’; did you mean ‘-fno-sanitize=float-cast-overflow’?`

After googling the flag, this seems to be a clang only flag at the moment.
I'm guessing this could be solved with a simple "if clang" check.

**Comment by dbabokin** [comment]
Thank you for the report.

Typically we recommend building ISPC with clang, as LLVM is an integral part of ISPC anyway. Moreover, to build ISPC release-grade binaries we strongly recommending using LLVM built by our scripts (and using it for building ISPC itself).

Nevertheless, PRs are welcome to fix the build with GCC.
