### ISSUE TITLE
aos_to_soa2/soa_to_aos2 for floats and doubles.

### ISSUE THREAD

**Issue by pbrubaker** [ispc/ispc#1836]
This need came up on Twitter today as well as in some of the work I'm doing with another game developer using Complex Numbers and FFTs.  It'd be handy to have for both floats and doubles, but a float version would be the highest priority.

https://twitter.com/noel_austin/status/1288131255360528393

**Comment by dbabokin** [comment]
Possible implementation: https://ispc.godbolt.org/z/arxKzK

**Comment by DeepakRajendrakumaran** [comment]
Adding a general implementation(I assume you mean option to choose any soa width) would be ideal but I can't see how that's possible with the current stdlib implementation. I'm going to add aos_to_soa2/soa_to_aos2 implementation for now. But will revisit the generic implementation later if possible.

@dbabokin  Do you agree that generic implementation might be hard or do you see a way around it?

**Comment by dbabokin** [comment]
Generic implementation would assume that we either have a library of all cases, or have a way to synthesize the arbitrary implementation. We are not there yet.

**Comment by dbabokin** [comment]
Fixed by #1972.
