### ISSUE TITLE
Why there were two function generated

### ISSUE THREAD

**Issue by CaoZhongZ** [ispc/ispc#1840]
Quick question, why there were two symbols generated from a single function. What is the difference between them.

```
export void update(uniform float values[],
    uniform int iterations[],
    uniform int num_values) {
  for (int i = programIndex; i < num_values; i += programCount) {
    int iters = iterations[i];
    while (iters-- > 0)
      values[i] *= values[i];
  }
}
```

I get:
_update___un_3C_unf_3E_un_3C_uni_3E_uni
_update

**Comment by pbrubaker** [comment]
When a function is marked 'export' two blocks of code are generated for linking.  One for calling from within ISPC and one for calling as a C calling convention.

If you were to remove the 'export' from the function definition one of the generated blocks of code would disappear.

**Comment by pbrubaker** [comment]
If you want to further refine the assembly for viewing add 'unmasked' to the function definition and that will remove the masked versions of the loops/functions.  This will make it easier comprehend the generated code.

**Comment by dbabokin** [comment]
Mangled version takes extra "mask" argument, so it can be called from masked context.

**Comment by MkazemAkhgary** [comment]
Is there a way to specify that export function is only called externally (from c++) to reduce code size? or does the extra block of code some how get removed automatically?

**Comment by dbabokin** [comment]
> Is there a way to specify that export function is only called externally (from c++) to reduce code size? or does the extra block of code some how get removed automatically?

No, two versions are generated by default and we don't have control to remove internal version. But his should not be a problem, as linker typically removes the functions that are not called.

Note that internal version is needed to preserve masked semantic when calling it from inside ISPC.
