### ISSUE TITLE
Can I disable the empty mask check?

### ISSUE THREAD

**Issue by CaoZhongZ** [ispc/ispc#1848]
vpcmpgtd	ymm8, ymm7, ymm12
	vmovmskps	ecx, ymm8
	test	cl, cl
	je	LBB5_9

If I understood it wrong, please point me where to read 😅

**Comment by dbabokin** [comment]
Details? (source code, command line options)

**Comment by CaoZhongZ** [comment]
export void copy_from_1d_array(
    float *uniform dst, uniform int d_width,
    float *uniform src, uniform int w_off, uniform int s_width) {

  for (int pid = programIndex; pid < d_width; pid += programCount) {
    int p_off = pid + w_off;

    dst[pid] = (p_off >= 0 || p_off < s_width) ? src[p_off] : 0;
  }
}

Like this, I want to copy a line at arbitrary offset, even negative. Anything outside the line became 0 to the destination.

**Comment by dbabokin** [comment]
From the first glance the claim looks reasonable, but I don't have time at the moment to look more carefully. @DeepakRajendrakumaran could you please have a look?

**Comment by CaoZhongZ** [comment]
Oh I just want to know is there any optimization switch or something I could have a quick try.

**Comment by dbabokin** [comment]
I don't we have a switch, which can fix that.

**Comment by CaoZhongZ** [comment]
Ok, thanks
