### ISSUE TITLE
/Users/ispc/ispc/src/main.cpp(372): FATAL ERROR: Unhandled signal sent to process; terminating.

### ISSUE THREAD

**Issue by RobBugel** [ispc/ispc#1849]
LS,

with the ispc compiler with command : 

$ ispc -O2 icvRGB2rgb565.ispc -o icvRGB2rgb565.o -h icvRGB2rgb565.h --target sse4-i32x4

I got the following error:

icvRGB2rgb565.ispc:7:18: Performance Warning: Gather required to 
        load value. 
    src_soa[i] = src_aos[i];
                 ^^^^^^^^^^

icvRGB2rgb565.ispc:7:5: Performance Warning: Scatter required to 
        store value. 
    src_soa[i] = src_aos[i];
    ^^^^^^^^^^

icvRGB2rgb565.ispc:11:16: Performance Warning: Gather required 
        to load value. 
           + ((src_soa[i].g << 3) & 0x07E0)
               ^^^^^^^^^^^^

icvRGB2rgb565.ispc:12:8: Performance Warning: Gather required to 
        load value. 
    +  (src_soa[i].b >> 3);
       ^^^^^^^^^^^^

/Users/ispc/ispc/src/type.cpp:940: Assertion failed: "m->errorCount > 0".
***
*** Please file a bug report at https://github.com/ispc/ispc/issues
*** (Including as much information as you can about how to reproduce this error).
*** You have apparently encountered a bug in the compiler that we'd like to fix!
***
/Users/ispc/ispc/src/main.cpp(372): FATAL ERROR: Unhandled signal sent to process; terminating.
Abort trap: 6

my input file icvRGB2rgb565.ispc is:
```
typedef struct rgb { uint8 r, g, b; } t_rgb;

export void 
  icvRGB2565(uniform t_rgb src_aos[], soa<4> t_rgb src_soa[], uniform uint16 dst[], uniform int count) 
{
  foreach (i = 0 ... count) {
    src_soa[i] = src_aos[i];
  }
  foreach (i = 0 ... count) { 
    dst[i] = ((src_soa[i].r << 8) & 0xF800)
           + ((src_soa[i].g << 3) & 0x07E0)
	   +  (src_soa[i].b >> 3);
  }
} 
```

I was searching how to get rid of the gathering and catering warnings, but did not succeed on that.
any suggestions?

I want to convert openCV RGB images to 16bit rgb565 images SIMD can help a lot but does not fit well with alignment and filling ...

Rob Bugel 
email: rblichtert@gmail.com

**Comment by DeepakRajendrakumaran** [comment]
Thanks for reporting this. The soa array type triggers an assert while creating the header file - https://godbolt.org/z/7P8rcE

The reason for this is soa type shows up as unbounded and we flag that. The reason for that is we are looking for varying structs which cannot be exported. I'm not quite sure on how to handle this though for soa - initial intuition is we should allow this but need to confirm.
