### ISSUE TITLE
ispc crashes at following:

### ISSUE THREAD

**Issue by already5chosen** [ispc/ispc#1872]
```c
struct s { double d; };
export uniform double foo(uniform s& x, uniform double y) {
  return x - y + y;
}
```

I was running on x86-64/Win7/ivybridge, but it looks like the crash is not related to particular platform
Version:
Intel(r) Implicit SPMD Program Compiler (Intel(r) ISPC), 1.14.1 (build date Aug 28 2020, LLVM 10.0.1)
Supported Visual Studio versions: Visual Studio 2015 and later.

**Comment by dbabokin** [comment]
I see it failing compilation, as expected: [https://godbolt.org/z/3xMqEK](https://godbolt.org/z/3xMqEK)

Is it really crashing or failing compialtion?

**Comment by DeepakRajendrakumaran** [comment]
@dbabokin We do assert after printing error with an error message
'Please file a bug report at https://github.com/ispc/ispc/issues'

 which is not ideal.

**Comment by dbabokin** [comment]
Ok, then it's a crash. I can't reproduce it on Linux, will have a look on Windows.

**Comment by dbabokin** [comment]
Ouch, I see. It's a crash while reporting a compiler error. We'll need to fix it. Thanks for the report.
