### ISSUE TITLE
Compilation error: fatal error: 'clang/Basic/TargetInfo.h' file not found 

### ISSUE THREAD

**Issue by ovilla** [ispc/ispc#1888]
Hi,

I am following exactly these steps  https://github.com/ispc/ispc/wiki/Building-ISPC  but I am encountering the following error.

```
[ 61%] Building CXX object CMakeFiles/ispc.dir/src/main.cpp.o
[ 61%] Building CXX object CMakeFiles/ispc.dir/src/module.cpp.o
/home/ovilla/ispc/src/module.cpp:66:10: fatal error: 'clang/Basic/TargetInfo.h' file not found
#include <clang/Basic/TargetInfo.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

It appears that the missing include file is not in the dependencies for `module.cpp`
```
ovilla@ubuntu:/home/ovilla/ispc/build$ grep include -R CMakeFiles/*  | grep module.cpp | grep TargetInfo.h
<<<nothing>>>
```

The file however exists:
```
ovilla@ubuntu:/home/ovilla/ispc/build$ find /home/ovilla/ispc/llvm  | grep clang/Basic/TargetInfo.h
/home/ovilla/ispc/llvm/llvm-10.0/clang/include/clang/Basic/TargetInfo.h
```

```
ovilla@ubuntu:/home/ovilla/ispc/build$ env | grep _HOME
ISPC_HOME=/home/ovilla/ispc
LLVM_HOME=/home/ovilla/ispc/llvm
```

I am not sure what is wrong exactly.
Thanks,

--Oreste

**Comment by DeepakRajendrakumaran** [comment]
Hi,

Have a couple of questions-
1. Do you have an install directory for llvm?
2. Can you add the llvm install directory to PATH? and rerun cmake again?

**Comment by ovilla** [comment]
Thanks for the prompt answer.

I have used `alloy.py -b --version=10.0` and installed llvm inside `/home/ovilla/ispc/llvm` (i.e. by setting `export LLVM_HOME=/home/ovilla/ispc/llvm`)

```
ovilla@ubuntu:/home/ovilla/ispc/llvm$ ls -la
total 20
drwxr-xr-x  5 ovilla dip 4096 Oct 15 14:24 .
drwxr-xr-x 24 ovilla dip 4096 Oct 15 17:11 ..
drwxr-xr-x  7 ovilla dip 4096 Oct 15 14:43 bin-10.0
drwxr-xr-x 18 ovilla dip 4096 Oct 15 14:44 build-10.0
drwxr-xr-x 22 ovilla dip 4096 Oct 15 14:21 llvm-10.0
```

The `clang/Basic/TargetInfo.h` file is indeed inside that tree:

```
ovilla@ubuntu:/home/ovilla/ispc/build$ find /home/ovilla/ispc/llvm  | grep clang/Basic/TargetInfo.h
/home/ovilla/ispc/llvm/llvm-10.0/clang/include/clang/Basic/TargetInfo.h
/home/ovilla/ispc/llvm/bin-10.0/include/clang/Basic/TargetInfo.h
```

however inside `build/CMakeFiles/ispc.dir/flags.make` I don't see any CXX_INCLUDE pointing there:
```
ovilla@ubuntu:/home/ovilla/ispc/build$ grep CXX_INCLUDE CMakeFiles/ispc.dir/flags.make
CXX_INCLUDES = -I/home/ovilla/ispc/llvm/llvm-10.0/llvm/include -I/home/ovilla/ispc/llvm/build-10.0/include -I/include -I/home/ovilla/ispc/src -I/home/ovilla/ispc/build/.
```

I would have expected also `-I/home/ovilla/ispc/llvm/llvm-10.0/clang/include`  or `-I/home/ovilla/ispc/llvm/bin-10.0/include/` to be in CXX_INCLUDES, but it is not.


I have also done `export PATH=/home/ovilla/ispc/llvm/bin-10.0/bin/:$PATH` as well, but that does not seem to be the issue.

**Comment by ovilla** [comment]
Just for testing purposes, I have added manually `-I/home/ovilla/ispc/llvm/bin-10.0/include/` to CXX_INCLUDES inside `build/CMakeFiles/ispc.dir/flags.make` and everything compiled.

I believe some dependencies to clang/include (not llvm/include) is missing when cmakes generates those files.

**Comment by DeepakRajendrakumaran** [comment]
Interesting. Thanks for the feedback .
Yes, you are correct- CXX_INCLUDES should have '....bin-10.0/include' in there. When you run cmake for ispc, can you explicitly specify CXX and CC. Something like 'CC=clang CXX=clang++ cmake  ..'

I was initially wondering if not having the PATH set was making cmake choose a system compiler installation etc.

**Comment by ovilla** [comment]
I believe the correct clang is used (unless below I should see ...bin-10.0 instead of ...build-10.0).
```
ovilla@ubuntu:/home/ovilla/ispc/build$ CC=clang CXX=clang++ cmake -DCMAKE_INSTALL_PREFIX=$ISPC_HOME/bin ../
-- Build type not specified: Use Release by default.
-- Found LLVM LLVM_10_0
-- LLVM_CONFIG_EXECUTABLE: /home/ovilla/ispc/llvm/build-10.0/bin/llvm-config
-- CLANG_EXECUTABLE: /home/ovilla/ispc/llvm/build-10.0/bin/clang
-- CLANGPP_EXECUTABLE: /home/ovilla/ispc/llvm/build-10.0/bin/clang++
-- LLVM_DIS_EXECUTABLE: /home/ovilla/ispc/llvm/build-10.0/bin/llvm-dis
-- LLVM_AS_EXECUTABLE: /home/ovilla/ispc/llvm/build-10.0/bin/llvm-as
-- FILE_CHECK_EXECUTABLE: /home/ovilla/ispc/llvm/build-10.0/bin/FileCheck
-- Detected LLVM version: 10.0.1
-- GIT_BINARY: /usr/bin/git
-- M4 macro processor: /usr/bin/m4
-- ISPC will be built with support of linux for x86;arm
-- Enabling target: linux / i686
-- Enabling target: linux / armv7
-- Enabling target: linux / x86_64
-- Enabling target: linux / aarch64
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ovilla/ispc/build
```

However the error is still there. Just for some reason, `/home/ovilla/ispc/llvm/bin-10.0/include` is not added to the CXX_INCLUDES.

**Comment by DeepakRajendrakumaran** [comment]
Yep, that makes sense. It needs to be bin-10.0 instead of ...build-10.0. The reason being the installation directory(bin-10.0 in this case) has the includes etc which are needed whereas the build directory doesn't

**Comment by ovilla** [comment]
Yes, that was the issue, build-10.0 was also in the PATH and that was confusing cmake. 
Thanks a lot for the help. I will close the issue.
