### ISSUE TITLE
Is there a way to change the compilerPath in the ISPC language server? 

### ISSUE THREAD

**Issue by kelayamatoz** [ispc/ispc#1890]
First of all, thanks for sharing this repo!

I have a question about using ISPC language server in [vscode](https://marketplace.visualstudio.com/items?itemName=intel-corporation.ispc&ssr=false#version-history): When starting this plugin on Mac, I got the following errors:
```bash
[Error - 2:52:59 PM] [ispc] - Path to compiler does not exist.  "c:\devtools\bin\ispc.exe"
[ispc] - compilerTarget is set to "host".
[Error - 2:52:59 PM] [ispc] - Path to compiler does not exist.  "c:\devtools\bin\ispc.exe"
[ispc] - compilerArchitecture is set to host.
[Error - 2:52:59 PM] [ispc] - Path to compiler does not exist.  "c:\bin\ispc.exe"
[ispc] - compilerPath is set to c:\bin\ispc.exe.
```

It seems to me that these errors can be removed by letting users set where ISPC is located (for example, Mac doesn't have c:\ type of directory). Is there a way that I can set the compiler path directly for the ISPC language server? 

Thanks a lot!

**Comment by pbrubaker** [comment]
Yes.  In vscode settings search for “ispc” you should see it.

Cheers,

Pete

**Comment by kelayamatoz** [comment]
Awesome! Thanks a lot!
