### ISSUE TITLE
Request: Prebuilt LLVM 11.0 on dbabokin/llvm-project site for building ISPC on Windows..

### ISSUE THREAD

**Issue by oscarbg** [ispc/ispc#1897]
Hi,
@dbabokin provides useful prebuilt LLVM library for Linux, Windows and MacOS for building ISPC on:
https://github.com/dbabokin/llvm-project
but seems latest release is still 10.0:
https://github.com/dbabokin/llvm-project/releases/tag/llvm-10.0-ispc-dev
it's useful as it contains the targets useful for building LLVM..
this is for me specially useful on Windows where current prebuilt LLVM 11.0 binaries (and older too) at:
https://releases.llvm.org/download.html#11.0.0
doesn't have all required .lib files for building ISPC..
so just asking for updated 11.0 files..
in fact recent docker commit (https://github.com/ispc/ispc/commit/306120d2c6de129278f0a219c56f89a54a3a60f0) contains a 
rebuild-llvm11.yml showing how to build a equivalent llvm-11.0.0-win.vs2019-Release+Asserts-x86.arm.wasm.zip file..
thanks..
EDIT: opening the issue here as is not possible on dbabokin/llvm-project being a fork of LLVM..

**Comment by dbabokin** [comment]
I'm working on it. I had a problem with aarch64 machine, so it's not completed.
I'll proceed with all other builds for now.
And yes, that's the right place to request it. It's on dbabokin/llvm-project is I was experimenting with this approach, and just not yet moved it to ispc/llvm-project.

**Comment by dbabokin** [comment]
Try it and please let me know if you see any issues with it:
https://github.com/dbabokin/llvm-project/releases/tag/llvm-11.0-ispc-dev

**Comment by oscarbg** [comment]
seem ok..
thanks!
