### ISSUE TITLE
Anonymous structs cause undefined error in ISPC

### ISSUE THREAD

**Issue by mergian** [ispc/ispc#1921]
Hey

When I try to compile the following example, ISPC crashes without any meaningful error message (see below).

## Code
```cpp
typedef struct {
    varying float x;
    varying int8 y;
} float_int8_t;

uniform float_int8_t init(float x, int8 y) {
    uniform float_int8_t out = {x, y};
    return out;
}
```

## ISPC Output
```
/usr/local/src/ispc/src/module.cpp:862: Assertion failed: "m->errorCount > 0".
***
*** Please file a bug report at https://github.com/ispc/ispc/issues
*** (Including as much information as you can about how to reproduce this error).
*** You have apparently encountered a bug in the compiler that we'd like to fix!
***
/usr/local/src/ispc/src/main.cpp(372): FATAL ERROR: Unhandled signal sent to process; terminating.
Aborted (core dumped)
```

The code compiles, when the first line is changed to ```typedef struct float_int8 {```.

**Comment by dbabokin** [comment]
Thanks for the bug report!

**Comment by DeepakRajendrakumaran** [comment]
This is a symbol table lookup issue with anonymous structs. In the symbol table we save the type as
uniform struct { $**anon0varying** float x; varying int8 y; }(varying float, varying int8)

Then when we try to match the type, we look for
uniform struct { $**anon1varying** float x; varying int8 y; }(varying float, varying int8)

**Comment by DeepakRajendrakumaran** [comment]
The reason for this is, everytime we create a new strucType for an anonymous struct, it gets created with a new name (https://github.com/ispc/ispc/blob/main/src/type.cpp - line 1561)- we have a counter and names them anon + counter.

Problem occurs when we try to match type using this 'anonymous name'. We originally added one name to the lookUp table and then tries to match with a  newly created anonymous struct name.
