### ISSUE TITLE
Scope of Typedefs

### ISSUE THREAD

**Issue by tay10r** [ispc/ispc#1929]
I noticed https://github.com/ispc/ispc/blob/0d42497c5cc5fce794ef614308cd558e22d238c2/src/sym.h#L272
Leads to this being legal
```c
void foo() {
  typedef int Number;
}
void bar() {
  Number a = 4;
}
```
Which is usually not legal (not legal in C or C++) because types are scoped. This isn't causing me any trouble personally, I'd just like to know if it's something that should get fixed or kept for the sake of backwards compatibility.

**Comment by dbabokin** [comment]
Nice catch. Looks like simplification, which causes deviation from C/C++. Would be good to have this fixed. I don't think that this will causes many regressions on existing code.

**Comment by tay10r** [comment]
Alright, I'll start working on a patch.
