### ISSUE TITLE
ispc compile time - reduce time spend on temporary function.

### ISSUE THREAD

**Issue by DeepakRajendrakumaran** [ispc/ispc#1937]
`__keep_funcs_live` is a temporary function created to prevent `pseudo_` and related library implementations from being optimized away so that they can be used by the optimization passes.

Flame graph of compile time shows that llvm passes spend time optimizing this temporary function(15-20 ms)

**Comment by DeepakRajendrakumaran** [comment]
There are llvm generic llvm optimizations like 'InstCombine' running on these + ISPC implemented passes like 'Replace Pseudo Memory"

**Comment by DeepakRajendrakumaran** [comment]
To disable generic LLVM passes from running on these and thus reduce compile time, following function attributes were tried - minSize and optnone(has to be used only for noinline). These were tested for 2 files  and results are below:


                                   | test01.ispc |   |                             | 01_aossoa.ispc |  

                            |   | Run 1 | Run 2 | Run 3 |             | Run 1 | Run 2 | Run 3

Master
  | ExecuteCompiler | 312.75 | 311.877 | 317.793 |   | 703.737 | 709.902 | 707.271

noinline_optnone 
  | ExecuteCompiler | 295.28 | 293.203 | 299.749 |   | 694.073 | 693.538 | 693.142
 
minsize
  | ExecuteCompiler | 307.761 | 303.321 | 307.257 |   | 704.539 | 701.797 | 707.472

**Comment by DeepakRajendrakumaran** [comment]
Comparing run_tests time (2 runs_ - looks like we are saving some time.

With changes - 00h02m24sec, 00h02m24sec
On master - 00h02m32sec, 00h02m32sec

**Comment by DeepakRajendrakumaran** [comment]
To reduce compile time on ispc specific passes is a little more complicated. The hasOptNone attribute is set for O0 optimization as well. As so, we cannot skip these passes when hasOptNone attribute is set. Alternate option is specifically to check for "__keep_func_live" and skip it - that's a little too hacky for my taste and frankly no sure is needed for way smalled time saving compared to generic llvm passes. So, opting to not do anything for these as of now.

**Comment by dbabokin** [comment]
Fixed by #1938
