### ISSUE TITLE
BFloat16 support?

### ISSUE THREAD

**Issue by CaoZhongZ** [ispc/ispc#1940]
Is it possible to support bf16 data type? : )

**Comment by dbabokin** [comment]
I guess the essence of the request is to support hardware instructions operating on `bf16`, as going through emulation route is less of an interest. What specific use of `bf16` are you interested in?

**Comment by CaoZhongZ** [comment]
Actually you got me on the question. So I think about it for a while.

The first level is like half-float, support affine transformation. Simply load, operate (in float?) and store. Save memory bandwidth etc.

Second level I was going through gemm example in ispc directory, and i'll come back to you when I know what exactly I want : )

**Comment by aneshlya** [comment]
Bfloat16 support is tracked in a separate feature request (https://github.com/ispc/ispc/issues/2361) so I'm closing this one.
