### ISSUE TITLE
CentOS 7 does not have flex 2.6

### ISSUE THREAD

**Issue by xkszltl** [ispc/ispc#1960]
v1.15.0 wants flex 2.6, but CentOS 7 only have 2.5.37.
The previous release was fine.

<img width="793" alt="image" src="https://user-images.githubusercontent.com/5203025/103408208-78498e80-4b9c-11eb-871f-203af5622fd4.png">

Any specific feature you need from 2.6?

**Comment by xkszltl** [comment]
Given the large installation base on CentOS 7 and recently death of CentOS 8, support for old flex is still needed.

**Comment by dbabokin** [comment]
It's the requirement not to produce `register` keyword, which we are going to impose when move to C++17.

You can either remove this version check from `CMakeLists.txt` (which should be fine for now). Or build newer flex, as I did here: https://github.com/ispc/ispc/blob/main/docker/centos7/Dockerfile#L65

**Comment by xkszltl** [comment]
I'm OK with compiling flex myself but I think for the broader community it's better to automate that as part of default build when needed, so that it works out of the box.

**Comment by dbabokin** [comment]
Yeah, I see your point. But we are not considering CentOS7 as a common *build* platform for ISPC. We considering it as a baseline for *running* release binaries, through.
