### ISSUE TITLE
unsigned integer to floating point conversion performance warning is unnecessary on some targets.

### ISSUE THREAD

**Issue by pbrubaker** [ispc/ispc#1963]
ISPC sometimes warns about conversion from unsigned integer to floating point when it is unnecessary.

```
<source>:3:25: Performance Warning: Conversion from unsigned int to 
        float is slow. Use "int" if possible 
    varying float foo = src[programIndex];
                        ^^^^^^^^^^^^^^^^^
```

We probably don't need it at all for AVX512.  In AVX2 it looks like `vcvtdq2ps` is generated for 8-bit and 16-bit integers, signed and unsigned - so the warning doesn't need to be present on those types.

Also, in converting from `int64` and `uint64` to `float` the compiler doesn't generate a warning about possible data loss.  Just the perf warning.

Example Code:

https://ispc.godbolt.org/z/cGWdzn

**Comment by DeepakRajendrakumaran** [comment]
Issue1- perf warning
From initial digging, it's not needed at all for avx512 as Pete mentioned above
For avx2 and sse- it might be needed for uint -> floating point conversions. For uint8 and uint16 -> float, there is no need for warning as we use the signed cvt (cvtdq2ps) anyway

Issue 2 - lack of data loss warning.
This is more intriguing. It makes sense that we print a warning for this.  I took a peek at what clang is doing for int64_t -> float conversion to mimic cpp behaviour and surprisingly don't see a warning there either- https://godbolt.org/z/GP84M9. Have to check this further

**Comment by DeepakRajendrakumaran** [comment]
Neon targets do not requite warning at all since they have separate singed/unsigned support - https://godbolt.org/z/4e1rGY
