### ISSUE TITLE
Add aos_to_soa2() and soa_to_aos2() to the standard library.

### ISSUE THREAD

**Issue by pbrubaker** [ispc/ispc#1965]
I've had a request from an ISV to add `aos_to_soa2` and `soa_to_aos2` to the standard library for built in types.  @JeffRous has supplied an implementation in ISPC but it would be nice if we had it as part of the stdlib.

https://ispc.godbolt.org/z/arxKzK

**Comment by pbrubaker** [comment]
I didn't realize that I had already opened an issue for this earlier.  I even searched the list to make sure an issue wasn't already open.  Feel free to merge the two and close one.

https://github.com/ispc/ispc/issues/1836

**Comment by dbabokin** [comment]
Closing this one.
