### ISSUE TITLE
v1.15 tarball sha256 changed?

### ISSUE THREAD

**Issue by carlocab** [ispc/ispc#1980]
Homebrew recently attempted an ARM build of ispc. However, Homebrew CI returned the following [error](https://github.com/Homebrew/homebrew-core/runs/1692564747?check_suite_focus=true#step:6:177):

```
==> Downloading https://github.com/ispc/ispc/archive/v1.15.0.tar.gz
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.7.3-27-g99a7e21\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 11.1\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://github.com/ispc/ispc/archive/v1.15.0.tar.gz
Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/b6bcf0c5a84e890a58d7cdcabb536e15aefbc883ba2902cd23d885155c160914--ispc-1.15.0.tar.gz
==> Verifying checksum for 'b6bcf0c5a84e890a58d7cdcabb536e15aefbc883ba2902cd23d885155c160914--ispc-1.15.0.tar.gz'.
Error: SHA256 mismatch
Expected: 788f44abefa508644384307c9ea69ef311ce5d4cfcb513b89e56d08f04d0d4be
  Actual: 2658ff00dc045ac9fcefbf6bd26dffaf723b059a942a27df91bbb61bc503a285
```

The expected `sha256` was recorded when Homebrew upgraded `ispc` to 1.15 in https://github.com/Homebrew/homebrew-core/commit/3b99fa7ccdb9eea4dd95a9be0b724f0225233007. 

I can update the recorded `sha256`. However, Homebrew CI will come back to me with the following error:
```
ispc:
  * stable sha256 changed without the url/version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
```
Can I confirm that nothing is amiss here?

**Comment by dbabokin** [comment]
After tagging v1.15.0 release I discovered a bug that affected macOS build and rewrote the trunk with the fix. I've noted in [ReleaseNotes](https://github.com/ispc/ispc/releases/tag/v1.15.0) that macOS build was updated.

Good to see that changed SHA was noticed :) sorry for the inconvenience, please update the SHA.

**Comment by SMillerDev** [comment]
Please note that the [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do. 😁

**Comment by dbabokin** [comment]
I think git-scm used to have more strong wording for retagging and push force :) Anyway, I think it was reasonable, given that the problem was severe and spotted early. Sorry for inconvenience.

**Comment by carlocab** [comment]
FYI, given that we use the tarball at https://github.com/ispc/ispc/archive/v1.15.0.tar.gz, retagging your release affected not only your macOS users, but anyone using the non-platform-specific tarball.

The correct thing to do here really was probably to just tag a new version. Version information is supposed to communicate to users that meaningful changes have been made; when you make meaningful changes but don't increment the version... well, that's just really poor communication. You could remove the 1.15 tarball if you were worried about users continuing to use it because they weren't paying attention.
