### ISSUE TITLE
ispc test failures on llvm trunk.

### ISSUE THREAD

**Issue by DeepakRajendrakumaran** [ispc/ispc#1998]
soa_to_aos3() tests are failing for avx1 targets on llvm trunk. This is an llvm bug

see bugzilla for - https://bugs.llvm.org/show_bug.cgi?id=48908

llc creates incorrect code for corei7-avx cpu. This bug seem to be limited to llvm trunk and on avx1 target.

**Comment by dbabokin** [comment]
Note that we'll need the fix in LLVM 12.0 as well.

**Comment by DeepakRajendrakumaran** [comment]
Fixed on LLVM trunk and fix verified with ISPC for LLVM trunk. Will wait for fix to be added to 12.0 in coming days.

**Comment by dbabokin** [comment]
Seems to pass on 12.0 now: https://github.com/ispc/ispc/actions/runs/547165071
