### ISSUE TITLE
How can we determine programmatically on which target the code runs ?

### ISSUE THREAD

**Issue by ColinChargyBentley** [ispc/ispc#2010]
Hi,
I have trouble deciding for which target I should run ISPC for (the value of --target when compiling my program).  Do you have hints for that (I've seen none in the documentation) ? I suppose providing all the possible targets is not a such a good idea... For what I understand, each CPU (and in the future GPU) has a specific target (although I can run other compliant targets). If that's right, is there any table to show equivalence between CPU and ISPC targets ?

If I have a feature tracking mechanism on my program (which bring back to me info from the different program executions, ie from my end-users), is there any code I could include in my program to determine the local target ? It could allow me to determine the targets I should ask ISPC to build for depending of the target my users really uses.
Regards,
Colin Chargy

**Comment by dbabokin** [comment]
The target triple consist of ISA, the base type most used in the code, and the number of elements in the vector. For example, avx2-i32x8 will produce the code with AVX2 instructions (hence it will not run on silicon not capable of executing AVX2 instructions), i32 indicates that it's optimized for handling 32 bit data (both floats and integers), and the vector will contain 8 elements (i.e. it will consume the whole ymm register, which is 256 bit).

If multiple targets are passed to the compiler, it will produce code for several targets and will pick in the runtime which one fit better based on ISA. This means that two targets with the same ISA cannot be used in multi-targets mode.

So, when targeting wide range of consumer devices it makes sense to have several targets.

What target to chose for specific ISA? I.e. what to pick between avx2-i32x4, avx2-i32x8, avx2-i32x16, avx2-i8x32, etc? The only right answer is to try them all and measure which one works better for specific kernel. But typically it's the default one (i.e. avx2-i32x8 in this case). Sometimes half-pump (avx2-i32x4) or double-pumped (avx2-i32x16) work better for specific cases or specific target hardware. i8/i16 targets are typically needed when the algorithm are dealing with bytes and short ints. But the advice is alway to measure the perfomance.

>If I have a feature tracking mechanism on my program (which bring back to me info from the different program executions, ie from my end-users), is there any code I could include in my program to determine the local target ? It could allow me to determine the targets I should ask ISPC to build for depending of the target my users really uses.

We have [check_isa.cpp](https://github.com/ispc/ispc/blob/main/check_isa.cpp) for checking ISA locally, but it's not exposed as ISPC function. But you can include it in your project and run it as C++ function. I would expect most of modern CPUs to be AVX2 capable, but still there are some SSE4 CPUs around. Also, modern Intel CPUs are AVX512 capable for some algorithms this ISA may provide very significant boost versus AVX2 - so make sense to use AVX512 as well.

So, my default answer would be to start from `--target=sse4-i32x4,avx2-i32x8,avx512skx-i32x8` and experiment with performance on different target CPUs. Picking between avx512skx-i32x8 and avx512skx-i32x16 is a bit tricky, as x8 is frequently preferable on current Xeons, while x16 has more chances on client Icelake and TigerLake CPUs (this would require much longer description to explain it in more details).

**Comment by ColinChargyBentley** [comment]
Hi @dbabokin ,
Thank you very much for this very detailed explanation! It's helpful and crystal-clear!
I do suggest you add the check_isa.cpp part and the "What target to chose for specific ISA?" part to the official documentation, since I may not be the only one wondering.
Best regards,
Colin Chargy
