### ISSUE TITLE
VSCode extension doesn't install correctly on Windows

### ISSUE THREAD

**Issue by ChrisG0x20** [ispc/ispc#2017]
I've tried to install the vscode extension via the GUI and on the command line. I'm not sure what the permission problem is about. I've tried running it as administrator.

> code --install-extension intel-corporation.ispc-1.1.0.vsix
Installing extensions...
(node:28300) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
EPERM: operation not permitted, open 'c:\Users\xxxxx\.vscode\extensions\intel-corporation.ispc-1.1.0\package.json'
Failed Installing Extensions: file:///c%3A/Downloads/intel-corporation.ispc-1.1.0.vsix

**Comment by dbabokin** [comment]
CC @pbrubaker

**Comment by pbrubaker** [comment]
Hey @ChrisG0x20 I think I solved this with the last release, can you give it a shot again?

**Comment by ChrisG0x20** [comment]
Thanks for taking a look. It got further this time, but it appears to be looking for the ispc compiler under a *nix /bin path rather than a Windows C:\Program Files path:

```
WARN: server does not support a notification '$/setTraceNotification'
[Info  - 1:57:34 PM] [ispc] - maxNumberOfProblems is set to 100.
[Info  - 1:57:34 PM] [ispc] - compilerTarget is set to "host".
[Info  - 1:57:34 PM] [ispc] - compilerArchitecture is set to x86-64.
[Info  - 1:57:34 PM] [ispc] - compilerCPU is set to icelake-client.
[Info  - 1:57:34 PM] [ispc] - compilerTargetOS is set to windows.
[Error - 1:57:34 PM] [ispc] - Path to compiler does not exist.  "c:\bin\ispc.exe"
[Info  - 1:57:34 PM] [ispc] - compilerPath is set to c:\bin\ispc.exe.
[Info  - 1:57:34 PM] [ispc] - file:///e:/Projects/ispc_test/simple.ispc opened.
[Info  - 1:57:34 PM] [ispc] - compiler started.

Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at ISPCLanguageServer.Compiler.CompileProc() in C:\projects\depot\users\pbrubake\ispc-languageserver-csharp\server\ispc_languageserver\Compiler.cs:line 99
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
[Info  - 1:57:34 PM] Connection to server got closed. Server will restart.
```

**Comment by pbrubaker** [comment]
Yeah, you'll have to specify where the compiler is installed on your system.  Go to File->Peferences->Settings and in the search bar type "ispc".

You should see a bunch of settings for the extension, edit the "Compiler Path" setting and change it to the fully qualified path to the compiler executable.

![image](https://user-images.githubusercontent.com/6944373/121959667-eed8e380-cd19-11eb-9fd6-067d6c51eb66.png)

**Comment by pbrubaker** [comment]
@ChrisG0x20 let me know if that solves the issue for you and we'll close this ticket.  Cheers!

**Comment by ChrisG0x20** [comment]
Thanks. I appears to be working now. I have to setup a valid project file before I can get any further.
