### ISSUE TITLE
#pragma unroll produces different code than unrolling by hand

### ISSUE THREAD

**Issue by zzzoom** [ispc/ispc#2036]
After reading the latest release notes, I tried the code in issue #1320 again, hoping for it to get optimized:

```ispc
int32 gang_scan(int32 v) {
    #pragma unroll
    for (uniform int s = 1; s < programCount; s *= 2) {
        v += shift(v, -s);
    }
    return v;
}

int32 gang_scan_manual_unroll(int32 v) {
    v += shift(v, -1);
    v += shift(v, -2);
    v += shift(v, -4);
    return v;
}
```

The asm produced by `#pragma unroll` couldn't optimize the shift the way it did when unrolled by hand.

Output: https://godbolt.org/z/j9o7oq

**Comment by dbabokin** [comment]
This is a tricky case, thanks for bringing it in.

What happens here is the following. `shift()` stdlib function is implemented differently depending whether the shift amount argument is a constant or not. In the manual unroll case it's obviously a constant and the `shift()` function call is got replaced by LLVM `shuffle` instruction (it's done by [ReplaceStdlibShiftPass](https://github.com/ispc/ispc/blob/main/src/opt/ReplaceStdlibShiftPass.h)). In case of loop unroll, `ReplaceStdlibShiftPass` is run before unrolling and hence it's unable to catch that it's a complete unroll and arguments are constant. So we have a problem.

So we have 3 phases that need to be properly ordered to this get optimized:
- unrolling (should happen before shift), and then
- shift optimization, and then
- inlining (it should not happen before shift, so "regular" stdlib version is not inlined).

Right now we do it in the following order:
- shift optimization
- inlining
- unrolling

Reshuffling this order will have significant impact on the optimizations. But it's not necessarily bad, I suggest experimenting with it. But we need to switch to the new pass manager first.
