### ISSUE TITLE
Ubuntu package

### ISSUE THREAD

**Issue by mcandre** [ispc/ispc#2077]
Could we get an official PPA for ispc, with update-alternatives integration?

**Comment by dbabokin** [comment]
Ubuntu supports two package managers - `apt` and `snap`. Would it work for you if we add ISPC to `snap`?

**Comment by nurmukhametov** [comment]
ISPC is distributed as a part of Intel® oneAPI that has an official PPA, see instructions to use it in README [here](https://github.com/ispc/ispc#intel-oneapi-distribution). Snap package was also added recently, see README [here](https://github.com/ispc/ispc#linux-snap-store).
