### ISSUE TITLE
Segmentation fault with large arrays

### ISSUE THREAD

**Issue by adhithadias** [ispc/ispc#2095]
I am executing the simple example that is included in ISPC compiler repository (this repository). I have changed it a bit to simplify it. The code can be accessed here: 

https://gist.github.com/adhithadias/c8e8617f8b55deaf448c2b8afab79377

When I change the array size to something larger than 268435456 (2^31 / 8) the code gives a segmentation fault.
I also tried with int and float. The segmentation fault happens when the array size is larger than 2^31 / 4 = 536870912 value. 
I also tried changing the simple ispc function to contain vin like this --> **uniform double * uniform vin**
I also changed the for loop to **for (int64 index = 0; index < count; index++) {**
Still, I got the same behaviour with segmentation faults.

Changing the function arguments to **uniform double * vin** and **double * vin** gave compilation errors.

I am wondering if the address space accessible for a single array bounded by 32-bit address space. If not, how do I resolve the above issue?

**Comment by kraszkow** [comment]
Hi @adhithadias ,
could you try to build it without any optimization in ISPC?

To do that change in CMakeLists.txt in examples simple directory this line: 

> set (ISPC_FLAGS -O2) 

to

> set (ISPC_FLAGS -O0)

**Comment by adhithadias** [comment]
Hi @kraszkow ,
It solved the addressing issue. Thank you for the reply.
