### ISSUE TITLE
Need parser support for 64-bit constants

### ISSUE THREAD

**Issue by mmp** [ispc/ispc#21]
Currently integer constants are treated as int32 types and floating-point constants are treated as float32s.  The parser should be extended to support 64-bit int and double constants as well, though the type promotion code should probably be updated so that an ostensibly double-precision constant like "2.0" doesn't cause type promotion to double if everything else in the expression is float32 (vs "2.0f").  At minimum, there should be a warning if this does happen.

**Comment by nurmukhametov** [comment]
Double precision floating point constants are supported since ISPC 1.5.0 (#584).
