### ISSUE TITLE
Please include only clang-capp.so instead of several libraries

### ISSUE THREAD

**Issue by luyatshimbalanga** [ispc/ispc#2104]
Fedora 32 and up uses libclang-cpp.so library to build some packages including ispc. It will be great to use that only according to the [changes on Fedora 32](https://fedoraproject.org/wiki/Changes/Stop-Shipping-Individual-Component-Libraries-In-clang-lib-Package) with this highlight:
```
The libclang-cpp.so shared object was added in clang 9.0 and now gives us an alternative shared library option that is supported by the upstream project and makes it possible for Fedora packages to stop using the component libraries. 
```

Here is an extract from an applied patch
```
From 22bbf8efc0deeb62cd706f1c2fee97201eb7427a Mon Sep 17 00:00:00 2001
From: Tom Stellard <tstellar@redhat.com>
Date: Fri, 13 Dec 2019 00:39:17 +0000
Subject: [PATCH] Link against libclang-cpp.so

---
 CMakeLists.txt | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/CMakeLists.txt b/CMakeLists.txt
index bd3483ab..edc97376 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -281,7 +281,7 @@
     list(APPEND ISPC_TARGETS wasm-i32x4)
 endif()
 
-set(CLANG_LIBRARY_LIST clangFrontend clangDriver clangSerialization clangParse clangSema clangAnalysis clangAST clangBasic clangEdit clangLex)
+set(CLANG_LIBRARY_LIST clang-cpp)
 set(LLVM_COMPONENTS engine ipo bitreader bitwriter instrumentation linker option)
 
 if (${LLVM_VERSION_NUMBER} VERSION_GREATER_EQUAL "10.0.0")
-- 
2.20.1
```

**Comment by dbabokin** [comment]
We still do not recommend building ISPC against "system" version of LLVM libs. ISPC needs a patched version of LLVM, which is built specifically for ISPC, to be a fully functional and bug free.

**Comment by dbabokin** [comment]
Is there a way for us to provide a correct recipe for building ISPC for official Fedora package?

Starting this release we build releases with Intel GPU support by default. This means much more complicated dependencies and build process. Also custom version of LLVM backend becomes more important.

**Comment by luyatshimbalanga** [comment]
> Is there a way for us to provide a correct recipe for building ISPC for official Fedora package?

Here is: https://src.fedoraproject.org/rpms/ispc/blob/rawhide/f/ispc.spec from https://src.fedoraproject.org/rpms/ispc

**Comment by nurmukhametov** [comment]
It is resolved by https://github.com/ispc/ispc/pull/2422
