### ISSUE TITLE
Fatal error during generation in version 1.16.0 release

### ISSUE THREAD

**Issue by larsbohn** [ispc/ispc#2116]
Hi!

There seems to be a bug in version 1.16.0 release.

Reproducer snippet:

`void func(int& param_inout)
{
    while(param_inout-- > 0)
    {
    }
}
`
Will lead to _FATAL ERROR: Unhandled signal sent to process; terminating._

Best regards,
Lars

**Comment by dbabokin** [comment]
Confirmed. Looks like we are not handling correctly missing statement in while loop.

**Comment by larsbohn** [comment]
Hi!

Thanks for picking this up.

It seems to be related to the reference argument and the ++/-- ops. Also happens in older versions:

https://ispc.godbolt.org/z/G81raP4eW

`void func(int& param_inout)
{
    if(param_inout++ < 0)
    {
        param_inout++;
    }
}
`

**Comment by DeepakRajendrakumaran** [comment]
It's not a  simple null check error. We are trying to create incorrect IR and it crashes in LLVM.
