### ISSUE TITLE
Question about leftpacking

### ISSUE THREAD

**Issue by kingofthebongo2008** [ispc/ispc#2118]
Hello,
Here on this presentation from insomniac, they describe two patterns
LeftPack, used for filtering and shifting variable amounts of bits.
https://www.gdcvault.com/play/1022248/SIMD-at-Insomniac-Games-How

Is there something similar in ispc already? May be one can implement them manually.
Thanks.

**Comment by dbabokin** [comment]
Left packing is `packed_store_active` (here for more details: https://ispc.github.io/ispc.html#packed-load-and-store-operations).

I had no chance to watch the whole video, so I'm not sure what kind shift by variable amount of bit is meant. Do you need to shift all element of SIMD vector by the same (variable) amount of bits? Do you need to shift every SIMD vector element by different (corresponding to each SIMD lane) amount of bits? Do you need to shift between SIMD elements?

**Comment by kingofthebongo2008** [comment]
![Capture](https://user-images.githubusercontent.com/1145201/125078924-b7b4e280-e0cb-11eb-957f-e962bd9d7d2b.PNG)

**Comment by kingofthebongo2008** [comment]
![Capture-a](https://user-images.githubusercontent.com/1145201/125078943-bc799680-e0cb-11eb-9aee-b7b2c8541fdc.PNG)

**Comment by kingofthebongo2008** [comment]
This is the problem that he describes and what LeftPack does, based on the mask.

**Comment by kingofthebongo2008** [comment]
This is a common pattern for filtering.

**Comment by kingofthebongo2008** [comment]
And the second one. Shifting by varible amount of bits.

**Comment by kingofthebongo2008** [comment]
![Capture-b](https://user-images.githubusercontent.com/1145201/125079613-812b9780-e0cc-11eb-9f20-81393942700a.PNG)

**Comment by kingofthebongo2008** [comment]
Quote from the presentation.

The next problem we’ll look at is that of dynamically generating a mask of the N lower set bits. We’d need a mask like this to isolate some variable number of bits in each SIMD lane. This can come up when you’re working with fixedpoint data which has been encoded with varying precision, or when doing certain other tricks with IEEE floats.
In scalar code this is pretty easy, to isolate n bits we simply shift 1 to the left by n steps and subtract 1 to get our mask.
This same approach works in some other SIMD instruction sets, but SSE doesn’t have a shift instruction that can shift each lane by a different amount.

**Comment by kingofthebongo2008** [comment]
So my question is where should i look for ispc to implement these patterns, since they are quite useful.

**Comment by dbabokin** [comment]
For shift left by variable amount there are instructions in AVX2 and AVX512, but not in SSE4.

The beauty of ISPC is that you don't need to know about code generation tricks to use them, you just need to express vector semantics in the source code. And either ISPC stdlib / optimizer or LLVM backend will take case about it.

Here's you can see how `(1<<n) - 1` is code generated for SSE4, AVX2, and AVX512: https://godbolt.org/z/7EvT6bEvG

Note that SSE4 version is not what you expect to see probably. It's LLVM backend, which did this unexpected transformation. But I bet it's correct and works better than straightforward approach.

To see an LLVM IR, if you happen to what to inspect it, add `--emit-llvm-text` to compiler switches.

**Comment by dbabokin** [comment]
For `packed_store_active`, check [documentation](https://ispc.github.io/ispc.html#packed-load-and-store-operations) first, if you need code examples, you can check the benchmark that we have that measures its performance versus "emulation" approach: https://github.com/ispc/ispc/blob/main/benchmarks/01_trivial/05_packed_load_store.ispc#L12

For `packed_store_active()` we generate emulation when no native instructions available and the instruction when it's available.

**Comment by dbabokin** [comment]
I'm closing the issue, feel free to reopen and/or add more questions here.

**Comment by kingofthebongo2008** [comment]
Thank you
