### ISSUE TITLE
multiple definition of `__cast_mask_to_i32' when linking multiple .ispc modules to a single exe since ver 1.14.1

### ISSUE THREAD

**Issue by memcache0** [ispc/ispc#2128]
I'm using MingW with ISPC on Windows 10. It is a strange combination but works fine for me. However, since version 1.14.1, if my exe links multiple .ispc modules, the linker failed with message "multiple definition of `__cast_mask_to_i32'".  It is fine if ver 1.14.0 or earlier versions used.

Compiler: MingW
ISPC verion: 1.14.1+
Condition: multiple .ispc modules are linked in a single exe project.
Error: multiple definition of `__cast_mask_to_i32'

I guess the function __cast_mask_to_i32 is marked as global since 1.14.1, then GCC linker for Windows will refuse to link if multiple __cast_mask_to_i32 are found in multiple object files.

**Comment by pbrubaker** [comment]
This is still occurring in 1.18.0.  See: #2320 2320
