### ISSUE TITLE
Feature Request: output dwarf debug info on Windows

### ISSUE THREAD

**Issue by memcache0** [ispc/ispc#2129]
I'm using MinGW with ispc on Windows 10. It is a strange combination but works fine for me. However, the Codeview debug information produced by ISPC cannot be recognized by MinGW. Thus it is difficult to debug it with GDB. So could you please support to output dwarf debug info on Windows?

**Comment by dbabokin** [comment]
That's really not a typical use case, but seems that we can do that without much efforts, as LLVM should support that.

I would hate creating new switches for such specific use case, but we can trigger DWARF debug info if `--dwarf-version` is used on Windows. Right now that would be ignored.

As a side note - using WSL on Windows might be a good alternative. I tried it myself recently and it worked surprisingly well.

**Comment by memcache0** [comment]
It's great if --dwarf-version can be supported on Windows. Thanks!

**Comment by nurmukhametov** [comment]
> It's great if --dwarf-version can be supported on Windows. Thanks!

#2631 triggers the DWARF usage on Windows when `--dwarf-version=<n>` provided.
