### ISSUE TITLE
Lit test 1323.ispc fails with LLVM trunk

### ISSUE THREAD

**Issue by dbabokin** [ispc/ispc#2134]
Reproducible on macOS and Linux, haven't tried it on Windows.

**Comment by aneshlya** [comment]
The test is failing due to different alignment for struct bool2:
Before llvm trunk the structure was defined in header file as:
`__declspec( align(4) ) struct bool2 { bool v[2]; };`
Using llvm trunk:
`__declspec( align(1) ) struct bool2 { bool v[2]; };`

**Comment by dbabokin** [comment]
Alignment of varying bool has changed from 4 to 1, so header doesn't match anymore. This seem to be caused by this commit: llvm/llvm-project@bdd55b2

**Comment by dbabokin** [comment]
The problem was not in LLVM change, though they triggered different behavior. The problem is that `LLVMType()` was used to evaluate alignment during header generation, instead of `LLVMStorageType()`. The difference between these two is only for `bool` type, which translates as `i1` by `LLVMType()` and as `i8` by `LLVMStorageType()`.
