### ISSUE TITLE
ISPC Texture Compression and clang's new-llvm-pass-manager causes corruption during conversion

### ISSUE THREAD

**Issue by hypnosnhendricks** [ispc/ispc#2138]
We use ISPC to generate ASTC images. Recently, we turned on Clang's new pass manager.
This resulted in corruption in our generated ASTC images. 

![image](https://user-images.githubusercontent.com/43652836/129084825-ae44801d-8d37-4376-b89d-c4ae9fa64603.png)

The pink blocks are the issue we are seeing.

**Comment by hypnosnhendricks** [comment]
Here is our conversion code:
`
void CompressBlocksASTC(const rgba_surface* src, uint8_t* dst, astc_enc_settings* settings) {
  assert(src->height % settings->block_height == 0);
  assert(src->width % settings->block_width == 0);

  assert(settings->block_height <= 8);
  assert(settings->block_width <= 8);

  int tex_width = src->width / settings->block_width;
  int programCount = ispc::get_programCount();

  std::vector<float> block_scores(tex_width * src->height / settings->block_height);

  for (int yy = 0; yy < src->height / settings->block_height; yy++)
    for (int xx = 0; xx < tex_width; xx++) {
      block_scores[yy * tex_width + xx] = std::numeric_limits<float>::infinity();
    }

  int mode_list_size = 3334;
  int list_size = programCount;
  std::vector<uint64_t> mode_lists(list_size * mode_list_size);
  std::vector<uint32_t> mode_buffer(programCount * settings->fastSkipTreshold);

  for (int yy = 0; yy < src->height / settings->block_height; yy++)
    for (int _x = 0; _x < (tex_width + programCount - 1) / programCount; _x++) {
      int xx = _x * programCount;
      atsc_rank(src, xx, yy, mode_buffer.data(), settings);

      for (int i = 0; i < settings->fastSkipTreshold; i++)
        for (int k = 0; k < programCount; k++) {
          if (xx + k >= tex_width)
            continue;

          uint32_t offset = (yy << 16) + (xx + k);
          uint32_t mode = mode_buffer[programCount * i + k];
          int mode_bin = mode >> 20;
          uint64_t* mode_list = &mode_lists[list_size * mode_bin];

          if (*mode_list < programCount - 1) {
            int index = int(mode_list[0] + 1);
            mode_list[0] = index;

            mode_list[index] = (uint64_t(offset) << 32) + mode;
          } else {
            mode_list[0] = (uint64_t(offset) << 32) + mode;

            astc_encode(src, block_scores.data(), dst, mode_list, settings);
            memset(mode_list, 0, list_size * sizeof(uint64_t));
          }
        }
    }

  for (int mode_bin = 0; mode_bin < mode_list_size; mode_bin++) {
    uint64_t* mode_list = &mode_lists[list_size * mode_bin];
    if (mode_list[0] == 0)
      continue;
    mode_list[0] = 0;

    astc_encode(src, block_scores.data(), dst, mode_list, settings);
    memset(mode_list, 0, list_size * sizeof(uint64_t));
  }
}
`

**Comment by dbabokin** [comment]
I need more context to understand the problem.

Are you saying that you are using "custom-built ISPC with enabled new pass manager" to compile `ISPC Texture Compressor` and it produces incorrect result?

How are you enabling new pass manger and where? In ISPC trunk we have not enabled new pass manager yet.

**Comment by hypnosnhendricks** [comment]
Correct, we are custom building the ISPC code ourselves, using the BUCK build system. The codebase managed by this build system is pretty vast. Our infrastructure engineers recently enabled this flag across the enterprise codebase ( hundreds of libs, programs, services). When they did this, we started getting reports of the visual artifacts in our texture assets from clients. We tracked it down to this flag being enabled and are working with infra to disable this flag for the ISPC library. I wanted to bring it to the attention of this group.

**Comment by hypnosnhendricks** [comment]
Oh, I think I put this on the wrong github, it should be on https://github.com/GameTechDev/ISPCTextureCompressor

**Comment by dbabokin** [comment]
Well, I still have a question if you build `ISPC` itself as part of your infrastructure?

It's really not a good idea do build ISPC yourself with the version of LLVM / clang libraries that were not recommended and tested by us. There's little to no sense of using some not recommended LLVM libraries for ISPC build - they will not make things better (neither from security or performance prospective), but very, very likely introduce regressions.

**Comment by hypnosnhendricks** [comment]
No, I apologize. I meant to post this to the ISPC-Texture-Compression github project and wrongly thought it was part of this github project, as I didn't realize it was a separate project. We don't build the actual ISPC compiler itself, we use the prebuilt executables. 
Its the code in ISPC-Texture-Compression, namely the function posted above & the ones it calls in the same file, that is having bad code generation when being complied with clang optimized path and the new pass manager flag.

We are not sure yet exactly what the bad code is and will need to compare the assembly generated. I'll close this out and repost it to the right github project.
