### ISSUE TITLE
ISPC crashes when struct member is named `d2`

### ISSUE THREAD

**Issue by pbrubaker** [ispc/ispc#2148]
I have a struct where if one member is named `d2` ISPC crashes with a fatal error.  If I rename that member to `dn2` or anything else it works fine.  Search for the define `SHOW_ISPC_BUG` in the attached Godbolt link for the location.

https://ispc.godbolt.org/z/zPMG8vPK7

**Comment by dbabokin** [comment]
Here's reduced reproducer:
```c
#define SHOW_ISPC_BUG 1

struct S {
#if SHOW_ISPC_BUG
    float		d2;
#else
    double		dn2;
#endif
};

export void foo(uniform S& dst) {
#if SHOW_ISPC_BUG
    dst.d2 = 1;
#else
    dst.dn2 = 2;
#endif
}
```

This bug was fixed by #2113, specifically by this commit: https://github.com/ispc/ispc/commit/3c77a95fa3786048103fe1e49aabe1afba653aef

This rule was incorrect: `(\.[0-9]*[dD][-+]?[0-9]+)`

I'll add a regression test and will close the issue.
