### ISSUE TITLE
Building on Jetson Nano : ARM64 Ubuntu 18.04 ?

### ISSUE THREAD

**Issue by nyue** [ispc/ispc#2153]
I am trying to build ispc on my Jetson Nano which as an ARM64 chip running Ubuntu 18.04

The llvm that ships with it is 

```
$ llvm-config --version
6.0.0
```

What are the requirements for building ispc on it ? Has anyone built one successfully ?

Cheers

**Comment by dbabokin** [comment]
You'll need to build llvm yourself:
`alloy.py -b --version=12.0 --selfbuild`
You can also add `--vebose` to have a clue what's going on. It will take a while. Make sure you have enough storage.

Or you can download pre-built binary that we use in our CI (aarch64, Ubuntu 16.04): https://github.com/ispc/llvm-project/releases/download/llvm-12.0-ispc-dev/llvm-12.0.1-ubuntu16.04aarch64-Release-x86.arm.wasm.tar.xz

**Comment by nyue** [comment]
I have chosen to use the pre-built binary, however, now I am encountering a different error

```
[  1%] Generating builtins-cpp-32-linux-armv7.cpp
In file included from builtins/builtins-c-cpu.cpp:69:
In file included from /usr/include/unistd.h:25:
/usr/include/features.h:424:12: fatal error: 'sys/cdefs.h' file not found
#  include <sys/cdefs.h>
           ^~~~~~~~~~~~~
1 error generated.
/home/picocluster/systems/llvm/bin-12.0/bin/llvm-dis: error: file too small to contain bitcode header
/home/picocluster/systems/llvm/bin-12.0/bin/llvm-as: <stdin>:1:1: error: expected top-level entity
builtins-c-*.cpp compile error
^
CMakeFiles/ispc.dir/build.make:114: recipe for target 'builtins-cpp-32-linux-armv7.cpp' failed
make[2]: *** [builtins-cpp-32-linux-armv7.cpp] Error 1
make[2]: *** Deleting file 'builtins-cpp-32-linux-armv7.cpp'
CMakeFiles/Makefile2:137: recipe for target 'CMakeFiles/ispc.dir/all' failed
make[1]: *** [CMakeFiles/ispc.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by dbabokin** [comment]
These are missing packages, see:
- https://github.com/ispc/ispc/blob/main/.travis.yml#L62
- https://github.com/ispc/ispc/blob/main/.travis.yml#L65

**Comment by nyue** [comment]
Thank you @dbabokin , I am now able to build ispc on my Jetson Nano.
