### ISSUE TITLE
Compiling stdlib.ispc to LLVM bitcode

### ISSUE THREAD

**Issue by seanbaxter** [ispc/ispc#2193]
How can I compile stdlib.ispc into an LLVM bitcode file? I don't want an application or any export functions. I want a bitcode file with the elementary functions, lowered for AVX-2, that I can link with another bitcode file using the LLVM internalizer.

```
$ ispc stdlib2.ispc -DISPC_MASK_BITS=32 
Warning: No output file or header file name specified. Program will be compiled and warnings/errors will 
        be issued, but no output will be generated. 
Warning: No --target specified on command-line. Using default system target "avx2-i32x8". 
stdlib2.ispc:116:23: Error: syntax error, unexpected identifier, expecting ',' or ';'. 
static inline float16 float16bits(unsigned int16 a) {
                      ^^^^^^^^^^^

stdlib2.ispc:652:5: Error: syntax error, unexpected identifier. 
    da[programIndex] = dst;
    ^^

stdlib2.ispc:670:10: Error: Redefinition of variable "sa" is illegal. (Previous definition at 
        stdlib2.ispc:650.) 
    void * uniform sa[programCount];
         ^^^^^^^^^
```

There are thousands of errors. It seems like ispc frontend has some preconditions that it satisfies when injecting this file internally. I saw that there is special treatment for the filename stdlib.ispc, so I renamed it stdlib2.ispc and tried building, and it issues the same errors.

**Comment by dbabokin** [comment]
Not that simple :) I'll try to help, but there might be some duck-taping needed on your side.

First of all, `stdlib.ispc` is just a "front-end" for standard library with the core "meat" being defined as builtin functions in LLVM IR.

I assume you need `avx2-i32x8` target, which is 8-wide target with 32 bit mask per element (so it's optimized to work with 32 bit wide types) and using AVX2 ISA.

So you need `stdlib.ispc` + `builtins/target-avx2-i32x8.ll`. But it's not a real `.ll` file, it's `m4` file that needs to be pre-processed to become a real .ll file. You can do that, but you still need to compile `stdlib.ispc` to something that you can consume.

And probably the easiest you can do is the following:
```sh
ispc --target=avx2-i32x8 dummy.ispc --emit-llvm-text --off-phase=104:last -O0 -o stdlib_avx2_i32x8.ll
```

Create a dummy `dummy.ispc`. The command line above compiles this dummy file by injecting to it `stdlib.ispc` and all requires builtin definitions and then suppresses any optimizations or dead-code elimination (`--off-phase=104:last` switch). So you will get LLVM Ir that you need in `stdlib_avx2_i32x8.ll`.

Note that most likely the functions to work with memory are not useful for you (gather/scatter stuff), as we emit "pseudo" version of these functions and later on lower them to real gather/scatters. And we mostly avoid using LLVM IR gather/scatter (partially for historic reasons, partially for the reason that they are not always good enough). This part will likely require duck taping on your side.

Let me know how this works for you.

PS I'll convert this "issue" to "discussion", hope it will not screw up the link to it.
