### ISSUE TITLE
Crash on vmovaps on Apple Silicon M1 in Rosetta translated execution

### ISSUE THREAD

**Issue by alanmikhak** [ispc/ispc#2197]
I observed the following crash in an ispc kernel running in Rosetta translated execution. Xcode debugger reports the crash is due to an EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, =0x0). Console crash report says it is due to Code 4 Illegal Instruction: 4.

Please see attached screenshots of Xcode and Console as well as the source code of my logabsfv_ispc() kernel.

![2021-11-22-console-crash-report-for-ispc-kernel-under-Rosetta-on-Apple-Silicon-M1-Mac-Mini](https://user-images.githubusercontent.com/12685415/142889413-803c0449-d5db-49e6-82df-9589ceb74407.gif)
![2021-11-22-crash-in-ispc-kernel-under-Rosetta-on-Apple-Silicon-M1-Mac-Mini](https://user-images.githubusercontent.com/12685415/142889415-ab5e9519-915e-4e92-a7c0-170075c7c6ad.gif)
![2021-11-22-logabsfv_ispc()](https://user-images.githubusercontent.com/12685415/142889420-be9a9f09-9f2f-4d9d-8ff0-e31ab04bfe58.gif)

**Comment by alanmikhak** [comment]
I natively compiled my command line program logabsCompute using pre-built ispc-1.16.1 binaries on Apple Silicon M1 Mac Mini (2020) on macOS Monterey 12.0.1 with Xcode 13.1 opened in Rosetta to capture the crash call stack. I also ran the resulting x86_64 binary in Terminal app opened with Rosetta to capture the Console crash report.

![2021-11-22-ispc--version](https://user-images.githubusercontent.com/12685415/142893802-9faa2768-4a8c-42a8-9516-8fd55ecb01c4.gif)
![2021-11-22-Mac-Mini-M1-system-info](https://user-images.githubusercontent.com/12685415/142893806-c65bdd8a-1f08-447e-832f-499bcf8d7d0f.gif)
![2021-11-22-Terminal-app-Get-Info-Open-Using-Rosetta](https://user-images.githubusercontent.com/12685415/142893807-e888b1db-a289-46a6-9200-f012f9766945.gif)

**Comment by dbabokin** [comment]
Yep, that's correct. Here's except form [here](https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment):
> Rosetta translates all x86_64 instructions, but it doesn’t support the execution of some newer instruction sets and processor features, such as AVX, AVX2, and AVX512 vector instructions. If you include these newer instructions in your code, execute them only after verifying that they are available.

Which means that you cannot execute AVX/AVX2/AVX512 code using Rosetta. And looks like you are trying to execute it unconditionally (without auto-dispatch and SSE version, which seem to be supported).

Nevertheless, if you'd like to run on M1, you should just compile for AArch64 / NEON and it will run natively.

**Comment by alanmikhak** [comment]
I did implement the sysctlbyname() check in logabsCompute to disable ispc code execution when running under Rosetta after observing the crash. The program now only executes translated c++ code until I finish porting its c++ and ispc code to native execution. However, I would still be interested in measuring the performance difference of its ispc execution between native x86_64, translated x86_64, and native arm64 without AVX/AVX2/AVX512.

**Comment by alanmikhak** [comment]
Thanks for addressing the issue I reported. Closing since it seems to be as designed.

**Comment by alanmikhak** [comment]
I removed the "--target=avx" option from ispc command to let ispc choose the target. In the case of Rosetta on M1 Mac Mini, ispc chose "sse4-i32x4". On x86_64 Mac Mini, ispc chose "avx2-i32x8".

**Comment by dbabokin** [comment]
That's sounds right, Rosetta seem to support SSE4, so compiler picking `sse4-i32x4` looks reasonable.
