### ISSUE TITLE
LLVM assertion hits under linux when building aobench_instrumented example

### ISSUE THREAD

**Issue by mmp** [ispc/ispc#22]
ispc -O2 --fast-math --instrument ao.ispc -o objs/ao_ispc.o -h objs/ao_ispc.h
ispc: MCELFStreamer.cpp:43: virtual void llvm::MCELFStreamer::EmitLabel(llvm::MCSymbol_): Assertion `Symbol->isUndefined() && "Cannot define a symbol twice!"' failed.
make: *_\* [objs/ao_ispc.h] Segmentation fault

This only happens under Linux, but seems to happen with both LLVM2.9 and LLVM dev tot.  Need to determine if this is an LLVM bug that should be filed or if ispc is doing something wrong.

**Comment by aneshlya** [comment]
This bug is outdated and not reproduced anymore.
