### ISSUE TITLE
Linux dev version download link broken

### ISSUE THREAD

**Issue by inducer** [ispc/ispc#2240]
If I go to https://ispc.github.io/downloads.html and click on "Linux (64 bit) ispc binary and examples (v1.18.0dev)", I get

```
{"message":"Build job with specified name not found or access denied."}
```

**Comment by dbabokin** [comment]
Good catch. It was broken by the latest PR #2238 when we moved the build image from Ubuntu 16.04 to 18.04 (and the link contains the image name).

**Comment by dbabokin** [comment]
Here's the actual commit that fixed the link: https://github.com/ispc/ispc.github.com/commit/f907e8143cdc86753f74f49cc68179503aad5aca

**Comment by inducer** [comment]
Thanks!
