### ISSUE TITLE
Missing constants from stdlib.ispc

### ISSUE THREAD

**Issue by qcoh** [ispc/ispc#2284]
#### Steps to reproduce 
Compile the following code (`missing_constant.ispc`):

```
export void test_random(uniform int output[]) {
	output[0] = INT32_MAX;
}
```

with

```
ispc missing_constant.ispc --target=avx2
```
(different targets produce the same result, e.g. "sse4", "avx", ...)

#### Current behaviour
The compilation fails with the error:

```
missing_constant.ispc:2:14: Error: Undeclared symbol "INT32_MAX". 
 output[0] = INT32_MAX;
             ^^^^^^^^^
```

#### Expected behaviour
I would expect the constant `INT32_MAX` to be available from stdlib.ispc (see [here](https://github.com/ispc/ispc/blob/737c3d7c67edb2fe4c0d9c54fe8a027ee05b2a4e/stdlib.ispc#L81)).

#### Other comment
According to the [documentation](https://github.com/ispc/ispc/blob/737c3d7c67edb2fe4c0d9c54fe8a027ee05b2a4e/docs/ispc.rst?plain=1#L3611-L3613), the standard library should be available unless explicitly disabled. If this does not include constants, this could be mentioned in the documentation.

#### Environment
Ubuntu 20.04 with ispc 1.17.0:

```
$ ispc --version
Intel(r) Implicit SPMD Program Compiler (Intel(r) ISPC), 1.17.0 (build commit 7ad8429369a4d5ce @ 20220128, LLVM 12.0.1)
```

**Comment by dbabokin** [comment]
These defines are for the use inside of stdlib only, so they are not visible outside of the stdlib. The point about clarifying this in the documentation is fair.

What really happens, is that stdlib is parsed separately and then linked to the ISPC program in the form of LLVM IR, where defines are already resolved.

We should either:
- clarify this in the documentation
- introduce these macros definitions in a proper way, so they are available in the user's code (like other constant defined [here](https://ispc.github.io/ispc.html#the-preprocessor))

**Comment by qcoh** [comment]
Thanks for the explanation, makes a lot of sense! I missed this part of the documentation so feel free to close.

If you consider extending the list of macro definitions, there might be other interesting ones, e.g. FLT_MAX, RAND_MAX, ...

**Comment by nurmukhametov** [comment]
These constants have been supported since v1.24.0 (PR https://github.com/ispc/ispc/pull/2850)
