### ISSUE TITLE
Wrong number of arguments to `alloy.py:validation_run():L657`

### ISSUE THREAD

**Issue by e3m3** [ispc/ispc#2298]
Issue:
```python
Stability validation run

Exception: build_LLVM() takes 11 positional arguments but 14 were given
```

Step to reproduce:
*   Run `./alloy.py -r --only=stability` after a fresh build of `ispc:main`.

**Comment by dbabokin** [comment]
This part of `alloy.py` functionality has rotten, as it was not used for quite some time. I think we should remove it (rebuilding LLVM as part of the testing). So it should build LLVM and tests ISPC separately - with `-b` and `-r` modes, but not mix this.

To test already built ISPC binary you need to use `alloy.py -r --only="stability current"` now

**Comment by pbrubaker** [comment]
Closing as inactive, if this is still an issue please reopen.
