### ISSUE TITLE
F:\trees\UE5\Engine\Source\ThirdParty\Intel\ISPC\ispc-1.16.1\src\main.cpp(392): FATAL error : Unhandled signal sent to process; terminating.

### ISSUE THREAD

**Issue by Sxinnner** [ispc/ispc#2300]
F:\trees\UE5\Engine\Source\ThirdParty\Intel\ISPC\ispc-1.16.1\src\main.cpp(392): FATAL error : Unhandled signal sent to process; terminating.

Impossible for me to compile a working Unreal Editor 5

**Comment by dbabokin** [comment]
It should be reported to UE, not to ISPC - even though it's ISPC used as a third party component in UE, I don't know how ISPC is compiled in UE and how it's invoked to reproduce the error. I suggest reporting this problem to Epic or give sufficient details to reproduce this isolated environment. Closing this issue for now.
