### ISSUE TITLE
D:\Epic Games\UnrealEngine-release\Engine\Intermediate\Build\Win64\UnrealEditor\Development\Engine\SharedPCH.Engine.ShadowErrors.cpp(2): fatal error C1001: Internal compiler error.

### ISSUE THREAD

**Issue by Sxinnner** [ispc/ispc#2301]
D:\Epic Games\UnrealEngine-release\Engine\Intermediate\Build\Win64\UnrealEditor\Development\Engine\SharedPCH.Engine.ShadowErrors.cpp(2): fatal error C1001: Internal compiler error.

**Comment by dbabokin** [comment]
I'm not sure how this is related to ISPC, it's compilation of some C++ file.
