### ISSUE TITLE
fatal error: 'level_zero/ze_ddi.h' file not found

### ISSUE THREAD

**Issue by yurivict** [ispc/ispc#2316]
Version 1.18.0 fails to build:
```
In file included from /wrkdirs/usr/ports/devel/ispc/work/ispc-1.18.0/ispcrt/tests/mock_tests/ispcrt_mock_main.cpp:5:
/wrkdirs/usr/ports/devel/ispc/work/ispc-1.18.0/ispcrt/tests/level_zero_mock/ze_mock.h:12:10: fatal error: 'level_zero/ze_ddi.h' file not found
#include <level_zero/ze_ddi.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

The configure stage succeeded.

I think the package ```level-zero``` is expected by the build but isn't checked by configure.

OS: FreeBSD 13

**Comment by aneshlya** [comment]
`level-zero` is needed for ISPC Runtime for GPU, but GPU targets are not supported on FreeBSD. You can turn off the GPU build of ISPC Runtime by using -`DISPCRT_BUILD_GPU` in CMake configure command.
And we need to turn off ISPC Runtime build for GPU on FreeBSD by default in CMake.

**Comment by pbrubaker** [comment]
Closing as resolved.  If this isn't resolved please reopen.
