### ISSUE TITLE
Using ISPC for large boolean array operations 

### ISSUE THREAD

**Issue by touisteur** [ispc/ispc#2319]
Hi,

Is there a way to have ISPC work on arrays of booleans instead of float, half, int, etc. I need to implement quite complex processing mixing many 1-bit signals and I was looking for examples on how to do that with ISPC. Is there some optimization in place for arrays with components sized 1-bit?

Thanks for your help.

**Comment by pbrubaker** [comment]
Not 1-bit, 8-bit is as low as you can pack into varying types.  However depending on how long your arrays are, you could load them as integers in a varying type and operate on them with bitwise instructions.

What are you trying to do?  Are these 1-bit booleans for flow control, or are you just interested in how many are set?  Or which indices are set?

**Comment by touisteur** [comment]
Hi thanks for the answer.

These are multiple presence indicator signals I have to correlate together: shift left/right, combine together through boolean expressions (and, or...), fill/dilate, transform into rle and back... It seemed the spmd model would be a good fit for this pipeline, but I understand it is very niche.

**Comment by pbrubaker** [comment]
No problem.  We are looking at adding the ability to add 128, 256 and 512b integers so that you can use bitwise ops on those types directly.  It sounds like that may benefit you here.

**Comment by pbrubaker** [comment]
I'm closing this issue as I believe the question is resolved.  Please reopen if you have further questions!
