### ISSUE TITLE
Investigate outputting the PDB debugging format for Windows targets.

### ISSUE THREAD

**Issue by pbrubaker** [ispc/ispc#2322]
LLVM added support for the PDB format back in 2017, and it has improved much since then.  Other front end teams (such as Unity Burst Compiler) have been using it to great success for a number of years.  I think this could improve the debugging experience with Visual Studio and vscode with MSVC tools.

http://blog.llvm.org/2017/08/llvm-on-windows-now-supports-pdb-debug.html

**Comment by nurmukhametov** [comment]
As I see in my experiments, `ISPC` has no problem with emitting PDB. I tested it both with MSVC and Clang on Windows. Both setups generated PDB file for me that were OK to debug application in Visual Studio debugger. 

The only issue I encountered was with the following `CMake` project when building with `MSVC` compiler:
```cmake
project(pdb_example ISPC C)
add_executable(example dummy.c ex.ispc)
```

For Debug configuration, `cmake` doesn't apply `/DEBUG` linker flag that results in no PDB file has been generated.

But adding the following line fixes that:
```cmake
target_link_options(example PRIVATE /DEBUG)
```

**Comment by pbrubaker** [comment]
Hey @nurmukhametov has a change been created for the cmake changes?

**Comment by nurmukhametov** [comment]
> Hey @nurmukhametov has a change been created for the `CMake` changes?

I am not sure I follow what `CMake` changes you are referring to.

**Comment by pbrubaker** [comment]
Sorry, it seemed like there might need to be changes made to CMake's built-in support of ISPC.  Is that not the case?

**Comment by nurmukhametov** [comment]
Closing this as I see no issues with outputting PDB as I said here: https://github.com/ispc/ispc/issues/2322#issuecomment-1686763170. Feel free to create a new issue or reopen this with a specific issues regarding PDB debug formats.
