### ISSUE TITLE
typedef struct with same name doesn't work

### ISSUE THREAD

**Issue by emoon** [ispc/ispc#2351]
Give the following code https://godbolt.org/z/3ha18KEaG
```
typedef struct Foo {
    int a;
} Foo;   
```
Doesn't work in ISPC, but is fully legal in C/C++. The way C/C++ handles this is that struct names and typedefs are in different namespaces thus this works, while ISPC reports `Error: Multiple types provided for declaration`

**Comment by aganm** [comment]
I need this too. I want to use the same header file containing my struct definitions between my C code and my ISPC code, such that I don't need to duplicate all my structs between C and ISPC, simply reusing the same header for both. One solution is to rename the struct from the typedef, but still, this should work without renaming.
