### ISSUE TITLE
Allow disabling of static ispcrt library

### ISSUE THREAD

**Issue by StefanBruens** [ispc/ispc#2385]
Currently, both static and dynamic libraries are always built.

As the static library is referenced in the exported targets (`ispcrt_Exports-<BuildType>.cmake`), e.g.:
```
list(APPEND _cmake_import_check_files_for_ispcrt::ispcrt_static "${_IMPORT_PREFIX}/lib64/libispcrt_static.a" )
```
it is not sufficient to just delete the library file, as the CMake config would become invalid.

**Comment by aneshlya** [comment]
Fixed by https://github.com/ispc/ispc/pull/2391
