### ISSUE TITLE
llvm-config: unknown component name: arm

### ISSUE THREAD

**Issue by Xiong-JS** [ispc/ispc#2397]
Hello, I have the following problems in the process of `cmake ..`
`-- Build type not specified: Use Release by default.`
`-- Found LLVM LLVM_12_0`
`-- LLVM_CONFIG_EXECUTABLE: /usr/local/elk/bisheng-compiler-2.1.0/bin/llvm-config`
`-- CLANG_EXECUTABLE: /usr/local/elk/bisheng-compiler-2.1.0/bin/clang`
`-- CLANGPP_EXECUTABLE: /usr/local/elk/bisheng-compiler-2.1.0/bin/clang++`
`-- LLVM_DIS_EXECUTABLE: /usr/local/elk/bisheng-compiler-2.1.0/bin/llvm-dis`
`-- LLVM_AS_EXECUTABLE: /usr/local/elk/bisheng-compiler-2.1.0/bin/llvm-as`
`-- Detected LLVM version: 12.0.0`
`CMake Warning at cmake/FindLLVM.cmake:134 (message):`
`  LLVM was built without assertions enabled (-DLLVM_ENABLE_ASSERTIONS=OFF).`
 ` This disables dumps, which are required for ISPC to be fully functional.`
`Call Stack (most recent call first):`
`  CMakeLists.txt:216 (include)`

`-- GIT_BINARY: /usr/bin/git`
`fatal: not a git repository (or any of the parent directories): .git`
`-- M4 macro processor: /usr/bin/m4`
`-- ISPC opaque pointers mode is OFF`
`llvm-config: unknown component name: arm`
`CMake Error at cmake/FindLLVM.cmake:119 (message):`
`  Failed running`
`  /usr/local/elk/bisheng-compiler-2.1.0/bin/llvm-config;--libfiles;engine;ipo;bitreader;bitwriter;instrumentation;linker;option;frontendopenmp;arm;aarch64`
`Call Stack (most recent call first):`
 ` cmake/FindLLVM.cmake:156 (run_llvm_config)`
`  CMakeLists.txt:346 (get_llvm_libfiles)`

`-- Configuring incomplete, errors occurred!`
`See also "/root/ispc-ispc-4ec7d7d/build/CMakeFiles/CMakeOutput.log".`

Could you tell me how to solve it

**Comment by dbabokin** [comment]
Same is in https://github.com/ispc/ispc/issues/2390 - you need to get LLVM, which is built in a proper configuration - either with `alloy.py` script, or download a pre-built binary.

To build LLVM with `alloy.py` you can do that for example with following command: `alloy.py -b --version=15.0 --selfbuild`

**Comment by pbrubaker** [comment]
Closing as resolved, if this didn't solve your issue please reopen.
