### ISSUE TITLE
ISPC uses SSE4.2 instructions on SSE4.1 platforms

### ISSUE THREAD

**Issue by UnityBartPieters** [ispc/ispc#2402]
**Summary**

It seems ISPC is generating SSE4.2 instructions that get used on a SSE4.1 platform, resulting in a crash on Penryn CPUs that support 4.1 but not 4.2. 

In ispc.cpp line 732 it is noted that ISPC does not output SSE 4.2 instructions: 

`// Penryn is here because ISPC does not use SSE 4.2`

Yet when running ISPC-generated code on the Intel SDE emulator, it detects the use of `pcmpgtq`. On a client machine with Penryn architecture, it causes a crash. 

Might I be doing something wrong?

**SDE Output** 
`sde-external-9.0.0-2021-11-07-win\sde.exe -pnr -- bc7etest.exe
TID 0 SDE-ERROR: Executed instruction not valid for specified chip (PENRYN): 0x7ff84b19009e: pcmpgtq xmm1, xmm5
Image: E:\BugFixes\bc7e\compress_bc7e.dll+0x1009e
Function: bc7e_compress_block_init___
Instruction bytes are: 66 0f 38 37 cd`

Tested with most recent ISPC and a couple of versions all the way back to v1.12.0, on Windows.

**Repro steps** 
- Compile [https://github.com/BinomialLLC/bc7e/blob/main/bc7e.ispc](https://github.com/BinomialLLC/bc7e/blob/main/bc7e.ispc) with target sse4.
- Use listed example program (below) that links to the library
- Emulate the executable using Intel SDE on Penryn architecture. 
- SDE outputs error

**Test file** 
```#include <stdlib.h>
#include <stdint.h>

#include "bc7e.h"

#pragma comment(lib, "compress_bc7e.dll.lib")

int main(const char* argv[], int argc)
{
	bc7elib_compress_block_init();

	bc7e_compress_block_params settingsBc7e{};
	bc7elib_compress_block_params_init_basic(&settingsBc7e, true);

	size_t blocksPerRow = 1024;

	size_t bufferSize = blocksPerRow * 4 * 4 * 4;
	char* buffer = (char*)malloc(bufferSize);

	unsigned long long* result = (unsigned long long*) malloc(blocksPerRow * 16);

	for (int i = 0; i < 10; ++i)
	{
		for (int j = 0; j < bufferSize; ++j)
			buffer[j] = rand();


		bc7elib_compress_blocks(blocksPerRow, result, (const uint32_t*)buffer, &settingsBc7e);
	}

	return 0;
}

**Comment by pbrubaker** [comment]
Did you try passing `--cpu=penryn` in the command line options?

**Comment by UnityBartPieters** [comment]
Hey @pbrubaker, thanks, I tried and that works, but we are compiling for multiple targets using `--target=sse2,sse4,avx2` and combining multiple targets with specifying the cpu type is unsupported. I get the following error: 
`Error: Illegal to specify cpu type when compiling for multiple targets.` 

Can I specify that the sse4 target should use penryn (sse4.1) at most, or that sse2 should be used for penryn?

**Comment by pbrubaker** [comment]
No not currently.  That's unfortunate.  Let me discuss this with some folks and I'll get back to you.  I think currently the only way to be able to to do that would be to roll your own auto-dispatch.  That would require compiling your source multiple times, and you checking CPUID.

It wouldn't be that difficult as ISPC isn't doing anything special under the hood.  It's just an if-else chain.

**Comment by dbabokin** [comment]
For SSE4 targets we really using Nehalem is a default CPU: [link to the source code](https://github.com/ispc/ispc/blob/672904aaf91690a8f76ce86a7ce7e319e7cb5e2f/src/ispc.cpp#LL897C5-L897C5).

I'm not sure if it was specified anywhere that we treat SSE4 as SSE4.1. Is it really important nowadays? Penryn is 2007 CPU.

We can change the default is you really need it.

**Comment by UnityBartPieters** [comment]
Hi @dbabokin, thanks for looking into this. 

I could be reading the behavior wrong, but what I am seeing is that the auto dispatch is choosing target sse4 on Penryn, yet the generated sse4 code is sse4.2 which is incompatible with Penryn (supporting 4.1), causing a crash on Penryn, in our case, the Unity Editor. To me, it seems that for Penryn, the target should be set at sse2, as the generated sse4 code is incompatible. So I think this is a bug in the dispatch code for Penryn. 

I guess because it is such an old architecture and the incompatible output might be kernel-specific, it hasn't been noticed yet?

**Comment by pbrubaker** [comment]
Sorry Bart, we're all on vacation for the holiday.  I'll get together with Dmitry when we are back and talk about this more.  One possible solution could be to have an SSE4 target and an SSE4.2 target.

**Comment by UnityBartPieters** [comment]
Thanks pbrubaker, no problem. 

Something like you suggested would work. We would probably use the SSE4.2, SSE2 and AVX target. Penryn CPUs would then fall back to SSE2. Given it's such an old architecture, that wouldn't be too bad. It might also make sense to have the SSE4 target default to 4.2 and introduce a SSE4.1 just for Penryn, but you know best what makes most sense.

**Comment by pbrubaker** [comment]
Hey @dbabokin do you think we can revisit and consider this one for the next release?

**Comment by UnityBartPieters** [comment]
Hey all, just wanted to mention that I hope this is picked up for the next release. As soon as this bug is fixed we will update the Unity editor. We have users experiencing crashes on Penryn because of this. Thanks for looking into this.

**Comment by dbabokin** [comment]
Yes, we consider it for 1.20.

**Comment by UnityBartPieters** [comment]
Hi all, 

@pbrubaker , I just tried the v1.20.0dev binaries provided on the main page. Not sure if these include the aforementioned bug fix, but I am seeing 4.1 targets, so I assume it does. 

I do still see the same behavior as before: the auto dispatcher is selecting sse4.2 target on Penryn while Penryn doesn’t support 4.2, it does not fall back to sse2 target on Penryn. I tried with targets "sse2" and "sse4.1-i8x16" and those work. I assume if a target isn't available, it falls back to one that works for that architecture. So I don't see Penryn fall back to sse2 when all it has are sse2 and sse4.2 targets.

**Comment by dbabokin** [comment]
@UnityBartPieters you are correct that `1.20.0dev` includes the fix.

The fix does the following:
- introduces `sse4.2-*` targets, which are aliased to `sse4-*` targets and the trigger SSE4.2 (not good for Penryn)
- introduces `sse4.1-*` targets, which trigger SSE4.1 (good for Penryn)
- auto-dispatch code doesn't differentiate between `sse4.1-*` and `sse4.2-*`, so in the list of target you can have only one of them.

This means that with `1.20.0` (dev or release when it happens), you will need to update the list of targets `sse4-i32x4` => `sse4.1-i32x4`. Note that you don't need SSE2 for Penryn, as it will substantially degrade performance.

Please let me know if this doesn't work for you and you really need us to change the default and alias `sse4-*` to `sse4.1-*` targets instead of 4.2.

**Comment by UnityBartPieters** [comment]
First of all, I’m very grateful for the work you’ve put into this :).

Allow me to give some context on how we’re thinking.

A solution like this would force us to lower the implementation for newer CPUs from 4.2 to 4.1, because of this very old architecture. I've measured and performance drops with something like 1.5% going from 4.2 to 4.1. We can't add both 4.1 and 4.2 implementations, it wouldn't work if I understand you correctly, and the binary footprint would be too large to justify. Penryn is very old, so it would be unfortunate if this CPU would force newer CPUs down to 4.1. If we would have our own dispatcher, we would choose to have Penryn fall back to sse2 and just take the performance loss on that very old platform. We don't abandon Penryn, but realistically, such a performance drop is what it takes to keep things running.

I keep thinking though that ultimately the dispatcher is at fault. It still chooses the wrong target for Penryn (4.2) and causes subsequent crashes. We use the auto dispatcher because it just works and it saves us the effort of writing our own. So super happy to be able to use the dispatcher. It would be wonderful to have the dispatcher to work properly. If that’s not possible, then we’ll probably downgrade 4.2 to 4.1 and take the 1.5% performance drop on sse4 platforms.

**Comment by dbabokin** [comment]
Thank you very much for detailed description of the problem that you have - it really, really helps implementing the right solution! In #2506 I enabled dispatcher to distinguish between SSE4.1 and SSE4.2 chips. The limitation to have only either of them still remains though, but this is intentional as I don't want to break existing build systems.

The perf difference between 4.2 and 4.1 is really surprising. I believe that it's not due to different ISA, but due to different scheduling, which fits better the target microarchitecture. But nevertheless - 1.5% is a lot, if it's just due to different compiler switch.

[check_dispatch.ispc](https://github.com/ispc/ispc/blob/ca5f78703c30d75c68532217bb0905c0c0498cac/tests/lit-tests/check_dispatch.ispc) demonstrates how it works, if you need examples.
