### ISSUE TITLE
use clang-cpp.so instead of several individual libraries

### ISSUE THREAD

**Issue by luyatshimbalanga** [ispc/ispc#2418]
Since LLVM 9.0, upstream recommends to use clang-cpp.so instead of several individual library as seen on CMakeList.txt on the following line:

```
set(CLANG_LIBRARY_LIST clangFrontend clangDriver clangSerialization clangParse clangSema clangAnalysis clangAST clangBasic clangEdit clangLex)
if (${LLVM_VERSION_NUMBER} VERSION_GREATER_EQUAL "15.0.0")
    list(APPEND CLANG_LIBRARY_LIST clangSupport)
endif()
```
. 
The effective line is simply:
`set(CLANG_LIBRARY_LIST clang-cpp)`

which covers all range of LLVM version starting from 9.0. See the rationale on https://fedoraproject.org/wiki/Changes/Stop-Shipping-Individual-Component-Libraries-In-clang-lib-Package where Fedora Linux already supported it since release 32.

**Comment by ArchangeGabriel** [comment]
FTR, we do exactly the same in Arch.

**Comment by nurmukhametov** [comment]
As I see, the change you suggested also implies dynamic linking of clang-cpp. Probably, this is not we really want (@dbabokin, @aneshlya correct me if I am wrong).

I would suggest a slightly different fix (#2422). For every individual library, it searches at first static one then clang-cpp.

**Comment by ArchangeGabriel** [comment]
Sounds good, I will test it once a solution for https://github.com/ispc/ispc/issues/2419 is found.

**Comment by aneshlya** [comment]
@ArchangeGabriel , @luyatshimbalanga just for my understanding - do you always build ISPC with LLVM/Clang shared libraries, not static ones? Do these LLVM/Clang libraries are standard LLVM package or you build it with ISPC `alloy.py`?

**Comment by ArchangeGabriel** [comment]
Always shared and standard packages from the distro, yes.

**Comment by luyatshimbalanga** [comment]
Like @ArchangeGabriel mentioned, shared and standard LLVM package.
