### ISSUE TITLE
reduce compile times

### ISSUE THREAD

**Issue by mmp** [ispc/ispc#242]
It currently takes ~1.5s to compile rt.ispc for a single target on a laptop; this seems high.

A good chunk of the problem is that we don't do global DCE until after running the various passes that convert scatters to vector stores and such--and this in turn is just so that the declarations of the __pseudo_\* functions are available to those passes.  This means that we do a lot of work on a lot of code that doesn't matter.  If rt.ispc has just enough of the stdlib inside it and is compile with --nostdlib, it's 2.4x faster (~0.65s).

One option would be to package the stdlib into bits and require #includes to get its pieces as needed for a particular source file--#include <atomics.h>, etc.  Another option would be to just do global DCE early and then re-declare the pseudo functions as needed by later optimization passes.  The first is more disruptive to users, but on the other hand is more in tune with C...

**Comment by aneshlya** [comment]
I think that [redesign targets](https://github.com/ispc/ispc/pull/2743) solves this problem. 
@nurmukhametov , what do you think? Can we close this issue?

**Comment by nurmukhametov** [comment]
> I think that [redesign targets](https://github.com/ispc/ispc/pull/2743) solves this problem. @nurmukhametov , what do you think? Can we close this issue?

Yes, sure.
