### ISSUE TITLE
Can't find OpenMp_C

### ISSUE THREAD

**Issue by Xiong-JS** [ispc/ispc#2420]
`[root@host-10-208-232-136 build]# cmake -DCMAKE_INSTALL_PREFIX=/absolute/path/to/ispc ..`
`-- The C compiler identification is Clang 13.0.0`
`-- The CXX compiler identification is Clang 13.0.0`
`-- Detecting C compiler ABI info`
`-- Detecting C compiler ABI info - done`
`-- Check for working C compiler: /absolute/path/to/bin-13.0/bin/clang - skipped`
`-- Detecting C compile features`
`-- Detecting C compile features - done`
`-- Detecting CXX compiler ABI info`
`-- Detecting CXX compiler ABI info - done`
`-- Check for working CXX compiler: /absolute/path/to/bin-13.0/bin/clang++ - skipped`
`-- Detecting CXX compile features`
`-- Detecting CXX compile features - done`
`-- Build type not specified: Use Release by default.`
`-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11")`
`-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.10")`
`-- Found LLVM LLVM_13_0`
`-- LLVM_CONFIG_EXECUTABLE: /absolute/path/to/bin-13.0/bin/llvm-config`
`-- CLANG_EXECUTABLE: /absolute/path/to/bin-13.0/bin/clang`
`-- CLANGPP_EXECUTABLE: /absolute/path/to/bin-13.0/bin/clang++`
`-- LLVM_DIS_EXECUTABLE: /absolute/path/to/bin-13.0/bin/llvm-dis`
`-- LLVM_AS_EXECUTABLE: /absolute/path/to/bin-13.0/bin/llvm-as`
`-- FILE_CHECK_EXECUTABLE: /absolute/path/to/bin-13.0/bin/FileCheck`
`-- Detected LLVM version: 13.0.0`
`-- GIT_BINARY: /usr/bin/git`
`fatal: not a git repository (or any of the parent directories): .git`
`-- M4 macro processor: /usr/bin/m4`
`-- Found Python3: /usr/bin/python3.7 (found version "3.7.9") found components: Interpreter`
`-- Found BISON: /usr/bin/bison (found suitable version "3.6.4", minimum required is "3.0")`
`-- Found FLEX: /usr/bin/flex (found suitable version "2.6.4", minimum required is "2.6")`
`-- ISPC will be built with support of linux for arm`
`-- Enabling target: linux / armv7`
`-- Enabling target: linux / aarch64`
`-- Found Curses: /usr/lib64/libcurses.so`
`-- ISPC Runtime will be built with support of OpenMP tasking model on CPU`
`CMake Error at /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):`
 **`Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)`**
`Call Stack (most recent call first):`
  `/usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)`
  `/usr/local/share/cmake-3.20/Modules/FindOpenMP.cmake:537 (find_package_handle_standard_args)`
 ` ispcrt/CMakeLists.txt:78 (find_package)`

`-- Configuring incomplete, errors occurred!`
`See also "/root/ispc-1.18.0/build/CMakeFiles/CMakeOutput.log".`
`See also "/root/ispc-1.18.0/build/CMakeFiles/CMakeError.log".`

When compiling ispc, occurre the OpenMP not found_ C error. I have installed openmpi and libomp. Do I need to add any additional commands

**Comment by aneshlya** [comment]
OpenMP is not needed anymore starting from ISPC v1.20.0. 
Closing the issue.
