### ISSUE TITLE
Unnecessary Gather Instruction Generation

### ISSUE THREAD

**Issue by FreddieWitherden** [ispc/ispc#2468]
Consider the following snippet:
```c
#define SOA_IX(a, v, nv) ((((a) / TARGET_WIDTH)*(nv) + (v))*TARGET_WIDTH + (a) % TARGET_WIDTH)

export void simple(uniform float vin[], uniform float vout[]) {
    foreach (index = 0 ... TARGET_WIDTH) {
        // Load the appropriate input value for this program instance.
        float v1 = vin[SOA_IX(index, 0, 3)];
        float v2 = vin[SOA_IX(index, 2, 3)];

        // And write the result to the output array.
        vout[index] = v1 + v2;
    }
}
```
which should resolve to a pair of loads, an add, and a store.  However, on ISPC 1.19 with x86 this translates into a pair of gather instructions and an associated performance warning.  The associated constants are:
```
.LCPI1_0:
        .long   0                               # 0x0
        .long   4                               # 0x4
        .long   8                               # 0x8
        .long   12                              # 0xc
        .long   16                              # 0x10
        .long   20                              # 0x14
        .long   24                              # 0x18
        .long   28                              # 0x1c
.LCPI1_1:
        .long   64                              # 0x40
        .long   68                              # 0x44
        .long   72                              # 0x48
        .long   76                              # 0x4c
        .long   80                              # 0x50
        .long   84                              # 0x54
        .long   88                              # 0x58
        .long   92 
```
which corresponds to contiguous loads.  There is also a performance warning about varying division being expensive.  Here, however, it is easy enough to see the division is by a power of two and hence inexpensive.

**Comment by aneshlya** [comment]
The optimization which replaces gathers with loads should happen in ISPC `ImproveMemoryOps` pass. However it doesn't happen now because [lVectorIsLinear](https://github.com/ispc/ispc/blob/main/src/llvmutil.cpp#L1287) method (which is used to determine if the vector of offset is linear) doesn't support the pattern used in this example (`srem`, `sdiv`, `or` instructions can't be processed now) . So the pattern matching should be extended to cover this case.

```
%smear_counter10 = shufflevector <8 x i32> %smear_counter_init9, <8 x i32> undef, <8 x i32> zeroinitializer
  %iter_val11 = or <8 x i32> %smear_counter10, <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %div_index_load12_ = sdiv <8 x i32> %iter_val11, <i32 8, i32 8, i32 8, i32 8, i32 8, i32 8, i32 8, i32 8>
  %mul_add_mul_div_index_load12____ = mul <8 x i32> %div_index_load12_, <i32 24, i32 24, i32 24, i32 24, i32 24, i32 24, i32 24, i32 24>
  %mod_index_load13_ = srem <8 x i32> %iter_val11, <i32 8, i32 8, i32 8, i32 8, i32 8, i32 8, i32 8, i32 8>
  %add_mul_add_mul_div_index_load12_____mod_index_load13_ = add <8 x i32> %mul_add_mul_div_index_load12____, %mod_index_load13_
  %mul__add_mul_add_mul_div_index_load12_____mod_index_load13_ = shl <8 x i32> %add_mul_add_mul_div_index_load12_____mod_index_load13_, <i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2>
  %vin_load_offset_load99 = tail call <8 x float> @__pseudo_gather_base_offsets32_float(i8* %vin_load_ptr2int_2void, i32 1, <8 x i32> %mul__add_mul_add_mul_div_index_load12_____mod_index_load13_, <8 x i32> <i32 -1, i32 -1, i32 -1, i32 -1, i32 -1, i32 -1, i32 -1, i32 -1>), !filename !6, !first_line !7, !first_column !8, !last_line !7, !last_column !9
```
Alternatively we may introduce another pass which can do gathers->loads optimization closer to the end of optimization pipeline ( we need GVN and IndVarSimplify passes to optimize offsets construction code sequence to simple constant DataVector).

**Comment by dbabokin** [comment]
`lVectorIsLinear` does reasoning about linearity of the value. With the assumption that linear varying value `x` starts with a value divisible by `TARGET_WIDTH`, we can reason that `x / TARGET_WIDTH` has the same values in all lanes. I.e. `{4,5,6,7} / 4` = `{1,1,1,1}`. Similarly with the reminder - the resulting value should be linear: `{4,5,6,7} % 4` = `{0,1,2,3}`. But the catch is the assumption that the first value is divisible by `TARGET_WIDTH`. So we cannot just extend `lVectorIsLinear`.

Also, it worth to note that `foreach` doesn't guarantee any specific iteration order and specifically that it's iterated in chunks of `TARGET_WIDTH` starting from the first value. Even though the iteration is done this way.

Nevertheless, the complain that vector loads are not used is very much valid, as the do iterated in chunks of `TARGET_WIDTH` with aligned borders and we can figure it out after all the simplifications. So looks like we need to either re-shuffle our optimization passes or add a new later pass to catch this.
