### ISSUE TITLE
ISPC corrupt callstack vs '--no-omit-frame-pointer' option

### ISSUE THREAD

**Issue by petrsm** [ispc/ispc#2473]
Hi !
As reported here:
https://github.com/ispc/ispc/issues/2345

code generated by ISPC produces 'corrupt' callstacks which affect debugging and profiling. I was experimenting
with --no-omit-frame-pointer option and I found out, that it does not affect generated code at all.
After some googling, I found this: 
https://reviews.llvm.org/D71863

and it is mentioned there, that 

"function attributes ``no-frame-pointer-elim`` and  ``no-frame-pointer-elim-non-leaf`` have been replaced by ``frame-pointer``"

it seems to be the reason why there is no change in generated code and I hope that it has potential to fix callstacks
as well :-)

Would it be possible to use 'frame-pointer' instead of 'no-frame-pointer-elim' ? I wanted to try it, but I am struggling with
building ISPC from sources on Windows.

Thanks !

**Comment by dbabokin** [comment]
The fix is in PR and Windows build will be ready soon in Appveyor here: https://ci.appveyor.com/project/ispc/ispc/builds/46635293

Please check if it works as expected for you.

And thanks a lot for thorough investigation! It helps a lot!

**Comment by petrsm** [comment]
Thanks for quick fix ! 

Unfortunately after testing it, it seems, that corrupt callstacks are caused by something else.
I managed to build ISPC locally and tinkered with it for a while, but no matter what I do,
callstacks are broken.
