### ISSUE TITLE
Improve ISPC source compilation process

### ISSUE THREAD

**Issue by rkaric** [ispc/ispc#2480]
There is currently no documentation available which explains how to compile the ISPC compiler from source reliably.

Here are two possible solutions:

1. Update CMake scripts to download and install any dependencies on a given platform (i.e. Cygwin/GnuWin32 on Windows).
3. Add a how-to build from source document, either on the website or in the README, which lists steps and dependencies for a given platform.

**Comment by aneshlya** [comment]
@rkaric , have you seen [ISPC Development Guide](https://github.com/ispc/ispc/wiki/ISPC-Development-Guide#user-content-2_Building_ISPC)? We're trying to keep it up-to-date.

**Comment by rkaric** [comment]
I did not see that page when I was going through, thank you!
