### ISSUE TITLE
/usr/include/features.h:461:12: fatal error: 'sys/cdefs.h' file not found

### ISSUE THREAD

**Issue by yimuchuanye** [ispc/ispc#2525]
The error log as :
[  1%] Generating stdlib_mask8_ispc.cpp
[  2%] Generating builtins-cpp-32-linux-armv7.cpp
In file included from builtins/builtins-c-cpu.cpp:69:
In file included from /usr/include/unistd.h:25:
/usr/include/features.h:461:12: fatal error: 'sys/cdefs.h' file not found
#  include <sys/cdefs.h>
           ^~~~~~~~~~~~~
1 error generated.
/thfs1/home/nudtxiaotj/wql18/ys/llvm/llvm-14.0/bin-14.0/bin/llvm-dis: error: file too small to contain bitcode header
/thfs1/home/nudtxiaotj/wql18/ys/llvm/llvm-14.0/bin-14.0/bin/llvm-as: <stdin>:1:1: error: expected top-level entity
builtins-c-*.cpp compile error
^
make[2]: *** [CMakeFiles/ispc.dir/build.make:120: builtins-cpp-32-linux-armv7.cpp] Error 1
make[2]: *** Deleting file 'builtins-cpp-32-linux-armv7.cpp'
make[1]: *** [CMakeFiles/Makefile2:467: CMakeFiles/ispc.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

I find the way to solve this problem:
1，check native architecture: dpkg --print-architecture. Assuming that it's arm64 (i.e. aarch64)
2，check foreign architecture: dpkg --print-foreign-architectures.,
3，If foreign architecture list doesn't contain armhf, add it: sudo dpkg --add-architecture armhf.
4，Install libc6-dev: sudo apt-get update && sudo apt-get install libc6-dev libc6-dev:armhf

but I don't have the root .  How can I solve this problem?

**Comment by dbabokin** [comment]
What's your OS and hardware architecture?

**Comment by yimuchuanye** [comment]
Linux and AArch64
