### ISSUE TITLE
ISPC 1.20.0 ICE while parsing invalid code

### ISSUE THREAD

**Issue by mikemccarty-vertex** [ispc/ispc#2539]
See `nonexistent_data` reference at https://ispc.godbolt.org/z/aq7GvocqW

**Comment by nurmukhametov** [comment]
It is duplicate of https://github.com/ispc/ispc/issues/2514. It was fixed soon after release 1.20 by https://github.com/ispc/ispc/pull/2515.
After that ISPC reports an error:
```
./t.ispc:14:5: Error: 'uniform struct Stuff' has no member named "nonexistent_data"
    retval.nonexistent_data = 0;
    ^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by dbabokin** [comment]
The bug is indeed fixed, but godbolt "ispc (trunk)" still crashing, which appears to be godbolt problem not updating "ispc (trunk)". I've filed the issue: https://github.com/compiler-explorer/compiler-explorer/issues/5195

**Comment by mikemccarty-vertex** [comment]
Any idea when the next release will be?  This bug is quite annoying.

**Comment by dbabokin** [comment]
We plan for mid-August
