### ISSUE TITLE
How to use .obj  to NDK  project?

### ISSUE THREAD

**Issue by flowerdancedatou** [ispc/ispc#2563]
I search by google....... the docment of building in NDK is less...........Poor little thing. Can help me, give me a light.

**Comment by dbabokin** [comment]
I'm not familiar with Android development and how NDK projects work, but ISPC is no different than C++ for this matter. `*.o` or `*.obj` produced by ISPC should be linked to the rest of the project in the same way as C++ object files.

**Comment by aneshlya** [comment]
If you're looking for instruction how to build Android cmd app using NDK build, here is a good [instruction ](https://www.intel.com/content/dam/develop/external/us/en/documents/building-an-android-command-line-application-using-the-ndk-build-tools-593986.pdf) using Intel(R) C++ Compiler. Not sure if is still actual though. If yes, you can modify Android.mk file to invoke ISPC.

**Comment by flowerdancedatou** [comment]
Thank u. I slove the problem using 【--targe-os = android】 ,and using cmake archive the .o to static lib.
