### ISSUE TITLE
Why O2 opt is not working in Andorid ?

### ISSUE THREAD

**Issue by flowerdancedatou** [ispc/ispc#2565]
ispc XX.ispc  -o XX.o -O2 --opt=fast-math --arch=aarch64 --target=neon --target-os=android --addressing=64
when **off** Android NDK O2 opt  :
**D/AO: SMID microseconds 238776 lane count4
D/AO: No SMID microseconds 264090 lane count4**

when **open** Android NDK O2 opt         :
**D/AO: SMID microseconds 238162 lane count4
D/AO: No SMID microseconds 29478 lane count4**
externalNativeBuild {
            cmake {
                cFlags '-O2'
                cppFlags '-std=c++17  -O2'
                arguments "-DANDROID_ARM_NEON=ON -DANDROID_STL=c++_static"
            }
        }

**Comment by dbabokin** [comment]
It's hard to tell what's going on without more details (what `XX.ispc` is doing and what is no-SIMD version is doing, i.e. it might be vectorized by the compiler as well).

Note also that ISPC is doing `-O2` by default. I.e. if you want to compare `-O0` vs `-O2` you need to pass `-O0` explicitly.
