### ISSUE TITLE
standardize on bit-sized mask elements with generic target

### ISSUE THREAD

**Issue by mmp** [ispc/ispc#259]
We should probably just specify that the mask with generic targets is a gang-sized vector of i1 values; this is what is generally most appropriate, and it'd be nice to let the front-end work with this assumption.

Currently, some of the examples and tests that use "launch" crash due to using a vector of i32s for the mask with the sse4 target in the sse4.h implementation, while the front-end is only allocating enough space to store a vector of i1s.

**Comment by pbrubaker** [comment]
Closing as generic targets are no longer supported.
