### ISSUE TITLE
Missing `struct` tags in header when referring to builtin vector types

### ISSUE THREAD

**Issue by MarijnS95** [ispc/ispc#2650]
Compile the following file to a C header with `ispc repro.ispc -h repro.h` (on ISPC v1.21):

`repro.ispc`:
```cpp
struct Test {
    uint<2> size;
};

export void use(uniform Test &test) {
}
```

Results in the following header file (preprocessor noise omitted for brevity):

```c
#ifdef _MSC_VER
__declspec( align(16) ) struct uint32_t2 { uint32_t v[2]; };
#else
struct uint32_t2 { uint32_t v[2]; } __attribute__ ((aligned(16)));
#endif

struct Test {
    uint32_t2  size; // error: must use 'struct' tag to refer to type 'uint32_t2'
};

extern void use(struct Test &test);
```

It seems ISPC went "out of its way" to flatten the generic `uint` vector down to a type that C could understand (i.e. no C++ `template` for the element count), but a C compiler will complain here that uses of `uint32_t2` have to be prefixed with the `struct` tag (unless it were defined with a `typedef`). Note that the `struct` tag _is added_ for the use of `struct Test` within the exported function.

Since the documentation at https://ispc.github.io/ispc.html references C/C++ a lot, is it expected that this header is parsable by a C compiler, and how should this be fixed? It is currently hampering us from generating proper Rust bindings with `bindgen` which requires "pure C": https://github.com/Twinklebear/ispc-rs/issues/27

**Comment by nurmukhametov** [comment]
Thanks for reporting that. Yes, `ispc` needs to emit `struct uint32_t2 size`. PR #2651 should resolve that.

**Comment by MarijnS95** [comment]
@nurmukhametov thanks, that's fast!

Seems like you noticed there was a `&` C++ reference instead of a raw pointer; is that something that should be translated to a raw pointer for the C-like header bindings or not?

**Comment by nurmukhametov** [comment]
I don't have definitive opinion about translating references to raw pointers. From one side, it is kind of meaningless, because C ABI glues together ISPC/C/C++ (is there such thing as a reference in it?). From the other side, it looks quite logical to do that at least for this simple example. But, I may miss some bigger picture here. @aneshlya, @dbabokin, @e3m3 what do you think?

**Comment by aneshlya** [comment]
> @aneshlya, @dbabokin, @e3m3 what do you think?

References are not legal in standard C. I think we should generate a C-compliant header.
It would be good to create a separate issue for it.

**Comment by MarijnS95** [comment]
@aneshlya thanks, opened #2652 for it!
