### ISSUE TITLE
Transform reference types to pointer types when generating C header

### ISSUE THREAD

**Issue by MarijnS95** [ispc/ispc#2652]
The header generated by `ispc -h` is supposed to be C-compliant (https://github.com/ispc/ispc/issues/2650#issuecomment-1708859970), but when using references in ISPC (which should be ABI-compatible with raw pointers) they are emitted as C++ references in the header. Is this expected?

```cpp
struct Test {
  uint &my_data;
};

export void use(uniform Test &test) {}
```

Run `ispc repro.ispc -h repro.h` to generate:

```cpp
struct Test {
    uint32_t &my_data;
};

extern void use(struct Test &test);
```

Transforming them does make for a degraded experience in C++ I think, but a (verbose!) middle ground can be found with `#if defined(__cplusplus)` which is already used around `extern "C"` blocks for example.

**Comment by nurmukhametov** [comment]
For context, commit https://github.com/ispc/ispc/commit/fd03ba7586bbb9e54ddc21b8c6f42e90c9bd4b88 changed a raw pointer to a reference in function declarations for headers.

It looks like the proper fix has to generate a header with both declarations: one with reference (for `C++`), other with a raw pointer (for `C`), something like this:
```c++
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
#if defined(__cplusplus)
    extern void use(struct Test &test);
#else
    extern void use(struct Test *test);
#endif /* use function declaration */
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus
```

**Comment by MarijnS95** [comment]
Yup, as suggested I think a duplicated way based on `#if defined(__cplusplus)` might work. Perhaps even of the form:

```cpp
extern void use(
#if defined(__cplusplus)
    struct Test &test,
#else
    struct Text *test,
);
```

So that it's duplicating less... But it also explodes if you have many `&` args, so perhaps not worth it.
