### ISSUE TITLE
M4 requirements?

### ISSUE THREAD

**Issue by starseeker** [ispc/ispc#2657]
Hi!  I'm looking into the toolchain necessary to build ISPC, and I was wondering if it's necessary to have GNU m4 available, or whether a different m4 implementation like OpenBSD's would suffice?

In particular, I'm curious what m4 is normally used on Windows?

**Comment by aneshlya** [comment]
We usually use m4 from Cygwin installation. AFAIK we never tried other m4 versions, so I can't say if OpenBSD's would work for you.

**Comment by starseeker** [comment]
Unfortunately, I can confirm it doesn't:

```
om4: target-avx-common-16.ll at line 12: incr: argument is invalid: indir(i).
                 < i32 -1, 
```

I was hoping to find a viable m4 that could readily be built from sources on Windows... OpenBSD's implementation would have been simpler, but if GNU m4 is the only game in town I can try to tackle that.  Am I correct in assuming that trying to make ISPC's m4 compatible with other implementations isn't of particular interest to the ISPC project?

**Comment by aneshlya** [comment]
> Am I correct in assuming that trying to make ISPC's m4 compatible with other implementations isn't of particular interest to the ISPC project?
That's right. GNU m4 implementation works fine for us and we're not interested to make ISPC m4 files compatible with other implementations.

**Comment by starseeker** [comment]
Understood - I'll take a look at GNU m4.
