### ISSUE TITLE
ispc v1.21.0 binary release links against libtbb.so.2

### ISSUE THREAD

**Issue by mwestphal** [ispc/ispc#2662]
ispc v1.21.0 binary release links against libtbb.so.2

```
 ldd ispc-v1.21.0-linux/lib64/libispcrt_device_cpu.so
        linux-vdso.so.1 (0x00007ffcd1c91000)
        libtbb.so.2 => not found
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fb8c9000000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fb8c96a3000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fb8c967e000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fb8c8c00000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007fb8c97c2000)
```

Definitely unexpected, libtbb.so.2 cant be considered a standard lib to be available on any system

On my system (Arch Linux), I have `libtbb.so(.12)(.10)`

**Comment by aneshlya** [comment]
ISPC Runtime depends on libtbb.so.2 for several releases already.
You may try ISPC binary for oneAPI https://github.com/ispc/ispc/releases/download/v1.21.0/ispc-v1.21.0-linux-oneapi.tar.gz. It is linked against libtbb.so.12 from oneTBB: https://www.intel.com/content/www/us/en/developer/tools/oneapi/onetbb.html#gs.5m9dgy.

Alternatively you can build ISPC Runtime using any task system you want (or don't use it completely):
```
cd ispcrt
mkdir build && cd build
cmake -DISPCRT_BUILD_TASKING=OFF -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang ../
make install -j`nproc`
```

To choose another task system, please use CMake flag `-DISPCRT_BUILD_TASK_MODEL=[OpenMP | TBB | Threads]`

**Comment by mwestphal** [comment]
fair enough, maybe the requirements to use a specific binary release should be made clearer somewhere though :)
