### ISSUE TITLE
Snap ispc for ubuntu can't compile: permission denied

### ISSUE THREAD

**Issue by FattiMei** [ispc/ispc#2665]
I installed on ubuntu the ispc compiler with the command
`snap install ispc`

Then I tried compiling this example

```
  // filename: sum_vector.ispc
  export uniform double sum_vector(uniform double A[], uniform int n){
      double sum = 0;
      foreach (i = 0 ... n)
	          sum += A[i];
  
      return reduce_add(sum);
  }
```

With the command
`ispc sum_vector.ispc -o sum_vector.obj -h sum_vector.h`

But I get the error
```
Warning: No --target specified on command-line. Using default system target "avx2-i32x8". 
sum_vector.ispc: Permission denied
```

If I download the binaries from https://github.com/ispc/ispc/releases/download/v1.18.0/ispc-v1.18.0-linux.tar.gz the same commands work fine

**Comment by nurmukhametov** [comment]
Which ubuntu version do you use? Where do you place `sum_vector.ispc` file?

Snap package is confined, so it may have no access to some system-wide directories, e.g., `/tmp`. User home directory usually is mounted in this confinement. If so, then `sum_vector.ispc` file needs to have read access rights to the user that runs ispc.

**Comment by FattiMei** [comment]
Ubuntu version 20.04.6 LTS. The `sum_vector.ispc` source is in a subdirectory of `/home`

```
pwd
> /home/matteo/hpc/parallelcomp/lez03
ls -l sum_vector.ispc 
> -rw-rw-r-- 1 matteo matteo 174 set 21 15:01 sum_vector.ispc
```

I'm user `matteo`

**Comment by nurmukhametov** [comment]
It looks like snap package has to have `home` interface ([link](https://snapcraft.io/docs/home-interface)) in plugs section to have access to files in the user home directory (though it doesn't explain why in my setup it works without that interface).
I have uploaded snap package with that interface enabled to the edge channel.
Could you try it? To install that you need run this command:
```bash
$ snap install ispc --channel=edge
```

**Comment by FattiMei** [comment]
Ok, it works now. Should I close this issue?

**Comment by nurmukhametov** [comment]
> Ok, it works now. Should I close this issue?

Great! Thank you for reporting this!

Let me do this after I promote edge to stable, and merge corresponding fix for `snapcraft.yml`.
