### ISSUE TITLE
Please update libstdc++ on 797e6e0f718b runner

### ISSUE THREAD

**Issue by aneshlya** [ispc/ispc#2666]
Hi @Lectem,

Could you please update libstdc++ on 797e6e0f718b runner? I believe the latest available version is libstdc++.so.6.0.32.
We need it to make the benchmarks built with ispc using LLVM 16.0 work.
Currently I see an error:
```
/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./01_trivial/06_math)
```
https://github.com/ispc/ispc/actions/runs/6332469902/job/17199187860#step:6:14

**Comment by Lectem** [comment]
Hi, sorry for the delay!
It now has `GLIBCXX_3.4.34' which should make it safe for a little while.
Hopefully upgrading the toolchains didn't break anything, I know ubuntu often creates issues when upgrading.
Please confirm and close if everything is working as expected.

**Comment by nurmukhametov** [comment]
Thank you for updating the runner!

Benchmark job looks good now with LLVM 16: https://github.com/ispc/ispc/actions/runs/6417882967
