### ISSUE TITLE
'no platform load command found' warning when linking with Xcode 15

### ISSUE THREAD

**Issue by atafra** [ispc/ispc#2678]
After upgrading to Xcode 15, linking ISPC objects results in the following linker error for each ISPC object:

> ld: warning: no platform load command found in 'oidn/build/devices/cpu/local__/color.dev.o', assuming: macOS

This can be reproduced when building e.g. Embree, Open Image Denoise.

**Comment by atafra** [comment]
Forcing the old linker with `-Wl,-ld_classic` makes the warnings disappear.

**Comment by nurmukhametov** [comment]
Issue #2681 is highly likely related.

**Comment by pbrubaker** [comment]
Did this issue stop reproducing with Xcode 15.1 as mentioned in [this comment?](https://github.com/ispc/ispc/issues/2681#issuecomment-1783244778)

**Comment by alanmikhak** [comment]
I see this issue on Apple M1 with Xcode 16.1 (16B40) and ispc-1.16.1 even if I specify --target-os=macos. It seems ispc-1.16.1 doesn't inject any platform load command into the resulting .o file. Has this issue been resolved in newer versions of ispc?

Here is how I compile the source code with ispc-1.16.1 on macos
% ~/tools/intel.com/ispc-1.16.1/bin/ispc --arch=x86_64 --target-os=macos -O2 cvTimexMethods.ispc -o x86_64/cvTimexMethods_ispc.o
% ~/tools/intel.com/ispc-1.16.1/bin/ispc --arch=aarch64 --target-os=macos --target=neon -O2 cvTimexMethods.ispc -o arm64/cvTimexMethods_ispc.o

# Examine the ispc built .o with vtool

% cd x86_64
% vtool -arch x86_64 -show cvTimexMethods_ispc.o 
cvTimexMethods_ispc.o (architecture x86_64):

# By comparison, .o build with clang++ has a platform load command.

% vtool -arch x86_64 -show cvTimexMethods_cl.o  
cvTimexMethods_cl.o (architecture x86_64):
Load command 1
      cmd LC_BUILD_VERSION
  cmdsize 24
 platform MACOS
    minos 13.3
      sdk 15.1
   ntools 0
