### ISSUE TITLE
Profile-Guided Optimization (PGO) questions and LLVM BOLT support

### ISSUE THREAD

**Issue by zamazan4ik** [ispc/ispc#2687]
Hi!

I am doing research about enabling Profile-Guided Optimization (PGO) in multiple software domains (all current results are available at https://github.com/zamazan4ik/awesome-pgo ). And I have several questions regarding the current PGO infrastructure in ISPC:

* ICPS already supports building with LTO and PGO. Could you please share the performance benefits number from enabling it for ISPC? Would be great to see benchmark results, so ISPC can do data-driven estimation do they need to build ISPC with LTO + PGO or not (if they do in-house builds instead of using prebuilt one)
* Are ISPC prebuilt binaries optimized with LTO and PGO?
* Do you plan to integrate [LLVM BOLT](https://github.com/llvm/llvm-project/blob/main/bolt/README.md) as an additional optimization step after LTO and PGO? Clang already integrated it.

Thanks in advance!

**Comment by nurmukhametov** [comment]
Hello,

- No, no benchmark results.
- Not yet.
- We don't have such plans.
