### ISSUE TITLE
Error/crash "Type too small for SExt"

### ISSUE THREAD

**Issue by ColinChargyBentley** [ispc/ispc#2689]
Hi,
This code does not compile:
```
struct InvertInvertedSignAndIndexes
{
	double<3> InvVec_;
	uint8<3> Sign_;
};

uniform InvertInvertedSignAndIndexes getInvertInvertedSignAndIndexes()
{
	uniform InvertInvertedSignAndIndexes res;

	res.Sign_ = res.InvVec_ < 0.0;

	return res;
}
```
with error:
> Type too small for SExt
>   %19 = sext <4 x i1> %18 to <8 x i1>, !dbg !24061
> LLVM ERROR: Broken module found, compilation aborted!
> /usr/local/src/ispc/src/main.cpp(404): FATAL ERROR: Unhandled signal sent to process; terminating.
> Program terminated with signal: SIGSEGV
> Compiler returned: 139

See for example : https://godbolt.org/z/4rx9r5dv6

Can I workaround this one before you get it fixed ?
Regards,
Colin Chargy

**Comment by nurmukhametov** [comment]
Thank you for reporting this. It looks like a bug.

I can suggest two workarounds. The first one change `Sign_` to `bool<3>`.
```c++
struct InvertInvertedSignAndIndexes
{
    double<3> InvVec_;
    bool<3> Sign_;
};

uniform InvertInvertedSignAndIndexes getInvertInvertedSignAndIndexes(uniform InvertInvertedSignAndIndexes res)
{
    res.Sign_ = res.InvVec_ < 0.0;
    return res;
}
```

The second one doesn't change your struct declaration but the code generated for the first looks better:

```c++
struct InvertInvertedSignAndIndexes
{
    double<3> InvVec_;
    uint8<3> Sign_;
};

uniform InvertInvertedSignAndIndexes getInvertInvertedSignAndIndexes(uniform InvertInvertedSignAndIndexes res)
{
    uniform bool<3> cmp = res.InvVec_ < 0.0;

    res.Sign_.x = cmp.x;
    res.Sign_.y = cmp.y;
    res.Sign_.z = cmp.z;

    return res;
}
```

**Comment by nurmukhametov** [comment]
The minimal reproducer is:
```ispc
uniform uint8<4> foo(uniform uint8<4> a, uniform uint8<4> b) {
	return a < b;
}
```

It was introduced in 1.20 release probably by https://github.com/ispc/ispc/commit/d3388c638471f0e4938277c7bd3e9fa438acd658
