### ISSUE TITLE
[v1.22.0][GCC 13.2.0] Error: Invalid conversion from 'int' to 'yytokentype' [-fpermissive]

### ISSUE THREAD

**Issue by saininav** [ispc/ispc#2706]
Error log:
| build/tmp-glibc/work/x86-64-v3-oe-linux/ispc/1.22.0/build/lex.cpp: In function 'yytokentype lParseOperator(const char*)':
| /usr/src/debug/ispc/1.22.0-r0/build/./parse.hh:246:29: error: invalid conversion from 'int' to 'yytokentype' [-fpermissive]
|build/tmp-glibc/work/x86-64-v3-oe-linux/ispc/1.22.0/build/lex.cpp:3573:16: note: in expansion of macro 'TOKEN_TEMPLATE_NAME'
|  3573 |         return TOKEN_TEMPLATE_NAME;
|       |                ^~~~~~~~~~~~~~~~~~~
| /usr/src/debug/ispc/1.22.0-r0/build/./parse.hh:241:26: error: invalid conversion from 'int' to 'yytokentype' [-fpermissive]
| build/tmp-glibc/work/x86-64-v3-oe-linux/ispc/1.22.0/build/lex.cpp:3575:16: note: in expansion of macro 'TOKEN_IDENTIFIER'
|  3575 |         return TOKEN_IDENTIFIER;
|       |                ^~~~~~~~~~~~~~~~

Build Environment : Yocto
GCC Version: 13.2.0 (GCC)
ISPC tag: [v1.22.0](https://github.com/ispc/ispc/releases/tag/v1.22.0)

**Comment by nurmukhametov** [comment]
I can't reproduce that with GCC 13.2.1. Fedora build of 1.22 with gcc 13 is also fine [link](https://kojipkgs.fedoraproject.org//packages/ispc/1.22.0/1.fc40/data/logs/x86_64/build.log).

Do you provide additional compiler flags? Is it the first error in the build log? It is better to upload somewhere the full build log to better understand what happened.

**Comment by saininav** [comment]
/data/saininav/work/workspace/poky/build/tmp/work/corei7-64-poky-linux/ispc/1.22.0/recipe-sysroot-native/usr/bin/x86_64-poky-linux/x86_64-poky-linux-g++ --sysroot=/data/saininav/work/workspace/poky/build/tmp/work/corei7-64-poky-linux/ispc/1.22.0/recipe-sysroot -DBUILD_DATE=\"20231116\" -DBUILD_VERSION="\"commit bd2c42d42e0cc3da\"" -DISPC_ANDROID_TARGET_OFF -DISPC_FREEBSD_TARGET_OFF -DISPC_IOS_TARGET_OFF -DISPC_MACOS_TARGET_OFF -DISPC_PS_TARGET_OFF -DISPC_WINDOWS_TARGET_OFF -DISPC_X86_ENABLED -D_FORTIFY_SOURCE=2 -I/include -I/data/saininav/work/workspace/poky/build/tmp/work/corei7-64-poky-linux/ispc/1.22.0/git/src -I/data/saininav/work/workspace/poky/build/tmp/work/corei7-64-poky-linux/ispc/1.22.0/git/common -I/data/saininav/work/workspace/poky/build/tmp/work/corei7-64-poky-linux/ispc/1.22.0/build/. -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/data/saininav/work/workspace/poky/build/tmp/work/corei7-64-poky-linux/ispc/1.22.0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fcanon-prefix-map  -fmacro-prefix-map=/data/saininav/work/workspace/poky/build/tmp/work/corei7-64-poky-linux/ispc/1.22.0/git=/usr/src/debug/ispc/1.22.0  -fdebug-prefix-map=/data/saininav/work/workspace/poky/build/tmp/work/corei7-64-poky-linux/ispc/1.22.0/git=/usr/src/debug/ispc/1.22.0  -fmacro-prefix-map=/data/saininav/work/workspace/poky/build/tmp/work/corei7-64-poky-linux/ispc/1.22.0/build=/usr/src/debug/ispc/1.22.0  -fdebug-prefix-map=/data/saininav/work/workspace/poky/build/tmp/work/corei7-64-poky-linux/ispc/1.22.0/build=/usr/src/debug/ispc/1.22.0  -fdebug-prefix-map=/data/saininav/work/workspace/poky/build/tmp/work/corei7-64-poky-linux/ispc/1.22.0/recipe-sysroot=  -fmacro-prefix-map=/data/saininav/work/workspace/poky/build/tmp/work/corei7-64-poky-linux/ispc/1.22.0/recipe-sysroot=  -fdebug-prefix-map=/data/saininav/work/workspace/poky/build/tmp/work/corei7-64-poky-linux/ispc/1.22.0/recipe-sysroot-native=  -fvisibility-inlines-hidden -std=c++17 -fPIE -fvisibility-inlines-hidden -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -fstack-protector-strong -fdata-sections -ffunction-sections -fno-delete-null-pointer-checks -Wformat -Wformat-security -fwrapv -fno-rtti -Wno-register -Wno-error=comment -Wno-mismatched-new-delete -MD -MT CMakeFiles/ispc.dir/lex.cpp.o -MF CMakeFiles/ispc.dir/lex.cpp.o.d -o CMakeFiles/ispc.dir/lex.cpp.o -c /data/saininav/work/workspace/poky/build/tmp/work/corei7-64-poky-linux/ispc/1.22.0/build/lex.cpp
In file included from /data/saininav/work/workspace/poky/build/tmp/work/corei7-64-poky-linux/ispc/1.22.0/build/lex.cpp:795:
/data/saininav/work/workspace/poky/build/tmp/work/corei7-64-poky-linux/ispc/1.22.0/build/lex.cpp: In function 'yytokentype lParseOperator(const char*)':
/usr/src/debug/ispc/1.22.0-r0/build/./parse.hh:246:29: error: invalid conversion from 'int' to 'yytokentype' [-fpermissive]
/data/saininav/work/workspace/poky/build/tmp/work/corei7-64-poky-linux/ispc/1.22.0/build/lex.cpp:3573:16: note: in expansion of macro 'TOKEN_TEMPLATE_NAME'
 3573 |         return TOKEN_TEMPLATE_NAME;
      |                ^~~~~~~~~~~~~~~~~~~
/usr/src/debug/ispc/1.22.0-r0/build/./parse.hh:241:26: error: invalid conversion from 'int' to 'yytokentype' [-fpermissive]
/data/saininav/work/workspace/poky/build/tmp/work/corei7-64-poky-linux/ispc/1.22.0/build/lex.cpp:3575:16: note: in expansion of macro 'TOKEN_IDENTIFIER'
 3575 |         return TOKEN_IDENTIFIER;

**Comment by saininav** [comment]
[log.do_compile.txt](https://github.com/ispc/ispc/files/13483947/log.do_compile.txt)
[log.do_configure.txt](https://github.com/ispc/ispc/files/13483948/log.do_configure.txt)

**Comment by nurmukhametov** [comment]
You are using bison in `-y` mode (emulating POSIX Yacc). It causes token types (`TOKEN_TEMPLATE_NAME` and `TOKEN_IDENTIFIER`) to be defined as `int` whereas `lParseOperator` defined as returning `yytokentype`. This function was added in https://github.com/ispc/ispc/commit/242379fcf019953eda4a00e4a33c1f6134539535. Before that change, compilation with bison `-y` was successful. Other similar functions `lParseInteger`, `lParseFP` returns just `int`. So, I think it is reasonable to do same with `lParseOperator`. Thank you for reporting this!

**Comment by saininav** [comment]
This fixes the issue. Thanks.
