### ISSUE TITLE
ISPCRT: support multiple Intel drivers (e.g. iGPU and DG2)

### ISSUE THREAD

**Issue by johguenther** [ispc/ispc#2708]
see https://github.com/ospray/ospray_studio/issues/26

Even if we want to select the DG2 to run on, ISPCRT throws earlier when there is more than a single Intel driver at [ispcrt/detail/gpu/GPUDevice.cpp:1754](https://github.com/ispc/ispc/blob/main/ispcrt/detail/gpu/GPUDevice.cpp#L1754). One possible way could be to [change `g_deviceList`](https://github.com/ispc/ispc/blob/main/ispcrt/detail/gpu/GPUDevice.cpp#L1695) to store pairs of <driver, device>.

**Comment by nurmukhametov** [comment]
@johguenther, I changed `g_deviceList` to store pairs of `<driver, device>` as you suggested (#2710), but I have two concerns about it:
1. I don't understand what to do with context creation because it requires to choose the driver. The previous supposition about the only driver implied that context is also only one but now it is complicated.
2. It is not quite clear for me how to test this change.

**Comment by johguenther** [comment]
Looks like device selection happens first, which also determines the driver. The constellation that a `nativeDevice` is provided but no `nativeContext` seems an edge case, but then still the `nativeDevice` should be in `g_deviceList`, which can be searched to find the driver to create the matching context.

**Comment by nurmukhametov** [comment]
It is actually possible to create a context first and only then device, see for example: 
https://github.com/ispc/ispc/blob/38d1df8a745d213d328206d147ded339870b51f1/examples/xpu/simple-usm/simple-usm.cpp#L64

**Comment by johguenther** [comment]
Currently [detail/gpu/GPUDevice.cpp:1831](https://github.com/ispc/ispc/blob/main/ispcrt/detail/gpu/GPUDevice.cpp#L1831)
```cpp
// Use the first available device by default for now.
// Later we may do something more sophisticated (e.g. use the one
// with most FLOPs or have some kind of load balancing)
```

So, taking the first driver for the default context and then limiting choosing the device later to that context/driver would be current behavior. Yet like the comment mentions, some better heuristic to choose the default device / driver would be better (but I don't know what information is available by level zero as input for such heuristic).

**Comment by johguenther** [comment]
Hmm, but this would also be not flexible enough for OSPRay (we by default also create the Context first and then the Device). So, how about an env var `ISPCRT_GPU_DRIVER` (similar to existing `ISPCRT_GPU_DEVICE`) to let users override the driver selection (heuristic).

**Comment by nurmukhametov** [comment]
> Hmm, but this would also be not flexible enough for OSPRay (we by default also create the Context first and then the Device). So, how about an env var `ISPCRT_GPU_DRIVER` (similar to existing `ISPCRT_GPU_DEVICE`) to let users override the driver selection (heuristic).

I've added `ISPCRT_GPU_DRIVER` to #2710, as well as printing of available drivers and devices under `ISPCRT_VERBOSE`.
