### ISSUE TITLE
exported functions shouldn't be in the ispc namespace in generated header files

### ISSUE THREAD

**Issue by mmp** [ispc/ispc#271]
This doesn't really make sense, and isn't reflected in the actual naming of the symbols in the object files anyway...

**Comment by pbrubaker** [comment]
I can see that there could possibly be multiply defined symbols across object files, but I think it's a good idea to have the functions in an ISPC (or other/user defined?) namespace to reduce the chance of name conflicts in the host code.  I'm going to close this as there are bigger fish to fry.
