### ISSUE TITLE
Masked stores used when setting shorter width registers in some cases

### ISSUE THREAD

**Issue by rkaric** [ispc/ispc#2719]
Given the following code: https://godbolt.org/z/Kraa491fn

ISPC will operate on XMM registers up until the foreach() is encountered. Since the result is available in XMM0, it can safely perform an aligned/unaligned store using that register.

ISPC seems to broadcast to YMM0, load YMM1, mask store YMM0, and then clear the upper bits on YMM0.

**Comment by nurmukhametov** [comment]
This looks like a duplicate of #2611.

**Comment by pbrubaker** [comment]
Closing as duplicate of #2611.  This issue is mentioned in the other issue's thread.
