### ISSUE TITLE
Please bring back the --emit-c++ feature

### ISSUE THREAD

**Issue by imaginary-person** [ispc/ispc#2721]
Hi, it'd be great if ISPC could optionally generate some C/C++ source files corresponding to the object files it generates, so that users could easily view what intrinsics they could use in their existing source code, instead of inspecting the assembly code of the generated object files. That would also make porting existing source-code easier (without making ISPC a dependency in existing projects).
Currently, ISPC makes it hard for programmers to understand how they should effectively use explicit vectorization, because having to understand assembly is quite time-intensive.

ISPC developers ought to ask themselves whether they want to see more ISPC adoption, or whether they actually want to see more applications leveraging the full potential of Intel hardware because the former is actually restricting the latter.

It seems like ISPC developers are primarily concerned about the adoption of ISPC, and less about programs leveraging the full potential of Intel hardware

Thanks!

**Comment by aneshlya** [comment]
`--emit-c++` feature was not fully functional and we don't have any plans to restore it right now.
If you want to explore what intrinsics could be used on C++ side, you may try the following:
1. Generate LLVM IR from ISPC code using `--emit-llvm` or `--emit-llvm-text`
2. Run [llvm-cbe](https://github.com/JuliaHubOSS/llvm-cbe) on it.

I've never tried `llvm-cbe` by myself but it seems that it might work for your case.

**Comment by pbrubaker** [comment]
Closing as workaround provided and issue is inactive.
