### ISSUE TITLE
Github Action for downloading ISPC in GH workflows

### ISSUE THREAD

**Issue by emoon** [ispc/ispc#2729]
Something that would be nice would be to have an official GH action for ISPC that one can use as part of the workflow when building code code. 

https://docs.github.com/en/actions/creating-actions/about-custom-actions

What this essentially means is that the action should download the appropriate compiler. It would likely be good to support both stable and latest compiler as that way more than one build could be issues (one stable / on latest) to catch regressions.

**Comment by nurmukhametov** [comment]
Great idea! Could you provide examples of similar GitHub actions? Having them as a reference would be really helpful.

**Comment by emoon** [comment]
I'm not sure if this is the best example or not, but this installs Qt https://github.com/jurplel/install-qt-action

So the idea is that you write something like this

```yaml
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
```

In your yaml CI scriptp and it will install Qt for you (binaries, headers, etc) hopefully this helps.

**Comment by ScatteredRay** [comment]
Hey, I gave this a quick go. Just hacked something together real quick so it'll certainly need a few iterations. but to begin the discussion:

https://github.com/ScatteredRay/install-ispc-action

And it should be usable something like this: ```
    - name: install ispc step
      uses: ScatteredRay/install-ispc-action@main
      with:
        version: 1.23.0
        platform: windows
```

No docs yet, and it doesn't perform retry's or do very good error handling. But hopefully it's a start.

**Comment by aneshlya** [comment]
@ScatteredRay, thanks! I think it looks great! 
Several comments:
1. It might be beneficial to include an optional `architecture` input parameter, applicable for Linux/MacOS packages.
2. Ideally, the `version` parameter should be optional as well. By default, the action should be designed to install the latest version.
3. Am I correct that `build` directory is not required to be included in git?

**Comment by ScatteredRay** [comment]
@aneshlya :+1: on #1 and #2. Would be happy to implement. Also need to implement retry support. And I'm sure there are error cases not considered.

Also, would like a slightly better test case then just running --version, Anything in mind?

> Am I correct that build directory is not required to be included in git?

My understanding is that Github Actions requires something that it can just fetch and execute, so my understanding that it was either to include this, or the node_modules directory. But it's entirely possible my understanding is either dated or just plain wrong. So I'll investigate further.

**Comment by aneshlya** [comment]
@ScatteredRay, I created a repo under ispc org: https://github.com/ispc/install-ispc-action. Feel free to contribute there.

> Also, would like a slightly better test case then just running --version, Anything in mind?

You can check with regular expressions that `ispc --version` produces the expected version.
```
version_info=`ispc --version`
pattern="([0-9]+)\.([0-9]+)\.([0-9]+)"
if [[ $version_info =~ $pattern ]]; then
    echo "OK"
else
    echo "Something wrong"
fi
```

**Comment by pbrubaker** [comment]
Hey @ScatteredRay - is this still something you're willing to contribute?

**Comment by ScatteredRay** [comment]
Hey, yeah. I can find some time to continue on this.

**Comment by ScatteredRay** [comment]
Thanks for the ping, I've gone ahead and setup a PR here: https://github.com/ispc/install-ispc-action/pull/1 I'll see about spending some time to address the feedback shortly.

**Comment by pbrubaker** [comment]
Hey, thanks so much!

**Comment by pbrubaker** [comment]
Are we still tracking this issue given we've closed https://github.com/ispc/install-ispc-action/pull/1 ?

**Comment by aneshlya** [comment]
install-ispc-action was merged: https://github.com/ispc/install-ispc-action/pull/3
