### ISSUE TITLE
sse2-i32x8 target generates psuhfb which is not SSE2

### ISSUE THREAD

**Issue by atafra** [ispc/ispc#2735]
This is related to issue #1253, which fixed this issue for sse2-i32x4 but not for x8. The issue seems to be here:
https://github.com/ispc/ispc/blob/f619239c6822d1dd6085bfd1889b37302265b56b/src/ispc.cpp#L903

The problem is that `CPU_Core2` is specified here but that's SSSE3, not SSE2. It should be `CPU_x86_64` like the 4x version.

Of course this is a very old target, so it's not too important but the fix seems to be trivial.

**Comment by nurmukhametov** [comment]
Yes, you are right. CPUs for sse2 x4 and x8 diverged with no reason in https://github.com/ispc/ispc/pull/1327.
