### ISSUE TITLE
Add support for non-type template arguments

### ISSUE THREAD

**Issue by atafra** [ispc/ispc#2737]
Having support for type template arguments is very useful but it's often insufficient. In many cases, non-type arguments, e.g. int or enum, are also very important. A typical use case for these are high-performance kernels (e.g. convolution, machine learning) which require several different variants, each having different parameters (most commonly integer ones, e.g. kernel size). Sometimes the lack of template arguments could be worked around with macros, which is very cumbersome and also has a major limitation: it's not possible to add pragmas inside a macro (e.g. `#pragma unroll`). This can also be worked around but it's even more awkward, and doesn't scale well with the number of required parameter combinations.

**Comment by nurmukhametov** [comment]
Support of numerical template parameters can unlock a reasonable way to implement stdlib functions for short vectors as requested, e.g., in #2707.

Something like this for `max` (although it needs to be defined in the header of ISPC stdlib that is not exist yet):
```ispc
template <typename T, uint N>
uniform T<N> max(uniform const T<N> a, uniform const T<N> b)
{
    uniform T<N> r;
    foreach (i = 0 ... N) {
        r[i] = max(a[i], b[i]);
    }
    return r;
}

uniform double<4> foo(uniform const double<4> a, uniform const double<4> b) {
    return max<double, 4>(a, b);
}
```

**Comment by samayala22** [comment]
Another use case would be to simplify code generation for various indexing behaviors. 

Example: 

```
template<typename T>
inline void axpy(uniform int n, uniform T alpha, uniform T x[], uniform int incx, uniform T y[], uniform int incy) {
    // This can be replaced by a template once it is supported
    if (incx == 1 && incy == 1) {
        #pragma unroll(4)
        foreach(i = 0 ... n) {
            y[i] += alpha * x[i]; // 2 loads + 1 store
        }
    } else if (incx == 1 && incy != 1) {
        #pragma unroll(4)
        foreach(i = 0 ... n) {
            y[i * incy] += alpha * x[i]; // 1 gather + 1 load + 1 scatter
        }
    } else if (incx != 1 && incy == 1) {
        #pragma unroll(4)
        foreach(i = 0 ... n) {
            y[i] += alpha * x[i * incx]; // 1 load + 1 gather + 1 store
        }
    } else {
        #pragma unroll(4)
        foreach(i = 0 ... n) {
            y[i * incy] += alpha * x[i * incx]; // 2 gathers + 1 scatter
        }
    }
}
```

could be replaced by:

```
template<typename T, int incx, int incy>
inline void axpy(uniform int n, uniform T alpha, uniform T x[], uniform T y[]) {
    #pragma unroll(4)
    foreach(i = 0 ... n) {
        y[i * incy] += alpha * x[i * incx]; // infer load type at compile time
    }
}
```

**Comment by atafra** [comment]
Another similar example is implementing efficient convolution kernels using different block sizes. The following code could be significantly cleaned up:
https://github.com/OpenImageDenoise/oidn/blob/v2.2.0-rc/devices/cpu/cpu_conv.ispc
https://github.com/OpenImageDenoise/oidn/blob/v2.2.0-rc/devices/cpu/cpu_conv_compute.isph
https://github.com/OpenImageDenoise/oidn/blob/v2.2.0-rc/devices/cpu/cpu_conv_compute_block.isph

**Comment by aneshlya** [comment]
I've conducted some quick prototyping and believe we can add support for `int` and `enum` parameter types in function templates by the next release (v1.24.0). However, using template parameters for short vectors is trickier – currently, even type template parameters are unsupported in this context. Therefore, the support for short vectors might be delayed, but I agree that incorporating this feature would be highly beneficial.

**Comment by atafra** [comment]
This is great news, thanks! Open Image Denoise doesn't use short vectors, so `int` and `enum` paramer type support would be sufficient.
