### ISSUE TITLE
lld-link: error: undefined symbol: _fltused

### ISSUE THREAD

**Issue by iperov** [ispc/ispc#2740]
I am trying to link .o file with llvm clang and got this error.

looks like `_fltused` is used in msvc, but clang does not contain msvc runtime.

Is it possible to get rid of msvc dependencies to link generated ispc lib in other compilers?

**Comment by nurmukhametov** [comment]
Can you provide an example you are compiling along with command line you use to run ISPC and system compiler?

**Comment by iperov** [comment]
test.ispc:
```
export void simple(uniform float vout[], uniform float vin[], uniform int count, uniform float q, uniform float x, uniform float y) {
    foreach (index = 0 ... count) {
        float v = vin[index];
        vout[index] = v >= q ? x : y;
    }
}
```
```
ispc test.ispc -o test.o -h test.h
```


test.cpp:
```
#include "test.h"

extern "C" __declspec(dllexport) void _dll_entry(){}

extern "C" __declspec(dllexport) void c_test(float* vout, float* vin, int count, float q, float x, float y) 
{    
    return ispc::test(vout, vin, count, q, x, y);
    
    for (int i=0; i<count; ++i)
    {
        float v = vin[i];
        vout[i] = v >= q ? x : y;
    }
}
```


I am using clang from zig.
```
zig c++ -shared -e _dll_entry -o test.dll -flto=thin -O3 test.o test.cpp
```

without `-flto=thin -O3` compilation is fine.

**Comment by iperov** [comment]
also `-nodefaultlibs -nostdinc -nostdinc++` results the same error

**Comment by iperov** [comment]
You may not to fix it.
I just tested the lib to compare the performance.
