### ISSUE TITLE
improve shuffle(T, T, int) implementation.

### ISSUE THREAD

**Issue by MkazemAkhgary** [ispc/ispc#2770]
The second variant of the **shuffle** function, which permutes over two values, generates un-optimized code when the permutation is not static.

Here is an example:

```c++
unmasked varying int32 Shuffle(varying int32 a, varying int32 b, varying int32 perm)
{
    return shuffle(a, b, perm);
}
```

```asm
Shuffle___UM_vyivyivyi:                 # @Shuffle___UM_vyivyivyi
        push    rbp
        mov     rbp, rsp
        and     rsp, -64
        sub     rsp, 128
        vmovaps ymmword ptr [rsp + 32], ymm1
        vmovaps ymmword ptr [rsp], ymm0
        vmovd   eax, xmm2
        cdqe
        vpextrd ecx, xmm2, 1
        vpextrd edx, xmm2, 2
        movsxd  rcx, ecx
        movsxd  rdx, edx
        vpextrd esi, xmm2, 3
        vextracti128    xmm0, ymm2, 1
        vmovd   edi, xmm0
        vpextrd r8d, xmm0, 1
        movsxd  rdi, edi
        movsxd  r8, r8d
        vpextrd r9d, xmm0, 2
        movsxd  r9, r9d
        vpextrd r10d, xmm0, 3
        vmovd   xmm0, dword ptr [rsp + 4*rdi]   # xmm0 = mem[0],zero,zero,zero
        vpinsrd xmm0, xmm0, dword ptr [rsp + 4*r8], 1
        vpinsrd xmm0, xmm0, dword ptr [rsp + 4*r9], 2
        movsxd  rdi, r10d
        vpinsrd xmm0, xmm0, dword ptr [rsp + 4*rdi], 3
        vmovd   xmm1, dword ptr [rsp + 4*rax]   # xmm1 = mem[0],zero,zero,zero
        vpinsrd xmm1, xmm1, dword ptr [rsp + 4*rcx], 1
        vpinsrd xmm1, xmm1, dword ptr [rsp + 4*rdx], 2
        movsxd  rax, esi
        vpinsrd xmm1, xmm1, dword ptr [rsp + 4*rax], 3
        vinserti128     ymm0, ymm1, xmm0, 1
        mov     rsp, rbp
        pop     rbp
        ret
```

_The generated code is even worse for AVX512 targets._

---

Proposed implementation

```c++
unmasked varying int32 Shuffle(varying int32 a, varying int32 b, varying int32 perm)
{
    varying int32 permA = shuffle(a, perm);
    varying int32 permB = shuffle(b, perm - programCount);
    return select(perm < programCount, permA, permB);
}
```

```asm
.LCPI1_0:
        .long   4294967288                      # 0xfffffff8
.LCPI1_1:
        .long   8                               # 0x8
Shuffle___UM_vyivyivyi:                 # @Shuffle___UM_vyivyivyi
        vpermd  ymm0, ymm2, ymm0
        vpbroadcastd    ymm3, dword ptr [rip + .LCPI1_0] # ymm3 = [4294967288,4294967288,4294967288,4294967288,4294967288,4294967288,4294967288,4294967288]
        vpaddd  ymm3, ymm2, ymm3
        vpermd  ymm1, ymm3, ymm1
        vpbroadcastd    ymm3, dword ptr [rip + .LCPI1_1] # ymm3 = [8,8,8,8,8,8,8,8]
        vpcmpgtd        ymm2, ymm3, ymm2
        vblendvps       ymm0, ymm1, ymm0, ymm2
        ret
```

---

Remarks:
- If the permutation is static (such as `perm = {1, 3, 8, 10, 6, 14, 7, 15}`), the current implementation already generates optimized code.
- proposed implementation is only good for int32/float types on AVX2/AVX512 targets. (otherwise generated code is worse)
- If the permutation is out of range (`perm < 0 || perm >= 2*programCount`), the behavior for the current implementation is undefined, while the behavior for the proposed implementation is equivalent to the following function (although not very meaningful):
  
```c++
unmasked varying int32 Shuffle(varying int32 a, varying int32 b, varying int32 perm)
{
    varying int32 permUnderflow = (programCount + (perm % programCount)) % programCount; // rotates around a
    varying int32 permOverflow = ((perm - programCount) % programCount) + programCount; // rotates around b
    return shuffle(a, b, perm < 0 ? permUnderflow : perm >= programCount * 2 ? permOverflow : perm);
}
```

Since the behavior is undefined for the current implementation with invalid permutations, I assume that the behavior change in this case should not matter.

**Comment by MkazemAkhgary** [comment]
slightly better version

```c++
unmasked varying int32 Shuffle(varying int32 a, varying int32 b, varying int32 perm)
{
    varying int32 permA = shuffle(a, perm);
    varying int32 permB = shuffle(b, perm - programCount);
    return select(perm - programCount >= 0, permA, permB);
}
```

this avoids broadcasting programCount twice (one for positive and one for negative).

**Comment by nurmukhametov** [comment]
> proposed implementation is only good for int32/float types on AVX2/AVX512 targets. (otherwise generated code is worse)

I tried to check that but it looks like not all of them generated better code, e.g., `avx2-i16x16` generates a bunch of load/store that doesn't look good.

**Comment by dbabokin** [comment]
This is definitely a smarter way to do the shuffle when the indices are non-static. That implementation that we use is pretty naive (but very generic). The logic is currently implemented in `__shuffle2_<type>` builtins [here](https://github.com/ispc/ispc/blob/aa6610460368619567f0dcda037230dfae369af8/builtins/util.m4#L2088).

Note that one of the goals for target file redesign is to enable easier implementation of cases like that - when for certain ISA, certain data types and certain target width, we have more efficient algorithms.
