### ISSUE TITLE
Round varying values with avx512

### ISSUE THREAD

**Issue by nurmukhametov** [ispc/ispc#2780]
Consider the following code:
```ispc
float RoundToInt(float x)
{
    return round(x);
}
```

when compiled as folow:
```bash
ispc --target=avx512skx-x8 round.ispc -o -
```

it generates suspicious rounding instruction:

```asm
RoundToInt___vyf:                       # @RoundToInt___vyf
        vroundps        ymm0, ymm0, 12
        ret
```

Imm8 operand value 12 (`0b1100`) means that it selects the source of rounding mode control from MXCSR.RC (not from immediate value itself where it is `0b00`, i.e., rounding), so it may under some circumstances produce wrong result.

It also doesn't match codegen with uniform value (imm8 = 8), and codegen for `avx2` and `sse4` (imm8 = 8).

**Comment by dbabokin** [comment]
We generate it differently for AVX512 (`@llvm.nearbyint`) and AVX2 (target specific `@llvm.x86.avx.round.ps.256`) on LLVM IR level. It would be good to unify. Also note that `avx512skx-x16` is using `vrndscaleps`.
