### ISSUE TITLE
should support gather coalescing with generic targets

### ISSUE THREAD

**Issue by mmp** [ispc/ispc#279]
That optimization pass currently isn't executed for generic targets, since it introduces a number of irregular vector types/sizes and operations among them.  (e.g. on generic-16, it ends up using vec2_i64, vec4_i32, vec8_i32, ...).  It would be nice to get those various types/operations implemented so that coalescing could be enabled.

**Comment by pbrubaker** [comment]
The generic targets no longer exist, closing.
