### ISSUE TITLE
Add support for basic type min/max values

### ISSUE THREAD

**Issue by rkaric** [ispc/ispc#2794]
In C/C++ it's possible to use values such as INT_MAX or FLT_MAX by including a standard library header such as <limits.h> or <float.h>. It would be nice if there was some way for ISPC to offer those as well. Perhaps through predefined preprocessor symbols or a standard library header?

https://en.cppreference.com/w/c/types/limits

**Comment by aneshlya** [comment]
ISPC has limits for integral types in stdlib:
`INT8_MAX`/`INT8_MIN`, `INT16_MAX`/`INT16_MIN`, `INT32_MAX`/`INT32_MIN`, `INT64_MAX`/`INT64_MIN`, `UINT8_MAX`, `UINT16_MAX`, `UINT32_MAX`, `UINT64_MAX` .
But doesn't have for floating point types.
Plus, no mentions of it in documentation.

**Comment by nurmukhametov** [comment]
> ISPC has limits for integral types in stdlib: `INT8_MAX`/`INT8_MIN`, `INT16_MAX`/`INT16_MIN`, `INT32_MAX`/`INT32_MIN`, `INT64_MAX`/`INT64_MIN`, `UINT8_MAX`, `UINT16_MAX`, `UINT32_MAX`, `UINT64_MAX` .

They are internal `stdlib.ispc` definitions that are unavailable for users.

So, this example
```ispc
uniform int foo() {
   return INT32_MIN;
}
```
results to
```
<source>:4:11: Error: Undeclared symbol "INT32_MIN". 
   return INT32_MIN;
          ^^^^^^^^^
```
