### ISSUE TITLE
Too few arguments for Print() in gdb

### ISSUE THREAD

**Issue by nurmukhametov** [ispc/ispc#2805]
Following-up the discussion in comments here https://github.com/ispc/ispc/pull/2789#discussion_r1521935655 and this fix https://github.com/ispc/ispc/pull/2797, I need to report a one more case when `Print()` function of `ASTNode`/`Expr` class hierarchy doesn't work in gdb.

For the following test:
```ispc
typedef bool<1> bool1; 
task void f_f(uniform float RET[], uniform float a[]) { 
   RET[programIndex] = 0; 
   bool1 vec1 = {true}; 
   bool1 vec = vec1 == vec1; 
    if (!vec.x) 
       RET[0] = -1; 
}
```

the following workflow:
```bash
$ gdb --quiet --args ./bin/ispc --nostdlib --target=avx2-i8x32 -o test.o test.ispc
(gdb) b FunctionEmitContext::SwitchBoolSize
(gdb) r
(gdb) f 2
(gdb) p this
$1 = (const ispc::SymbolExpr *) 0x55555b67e710
(gdb) p this->Print()
Too few arguments in function call.
(gdb) p ((ispc::Expr*)this)->Print()
`-SymbolExpr <../tests/short-vec-bool3.ispc:13.17 - 13.21> [varying bool<1>] symbol name: vec1
$2 = void
```

Renaming `Print` to something else, e.g., `Dump` allows the debugger to avoid this issue.

**Comment by dbabokin** [comment]
Why is that? Does it stop searching for virtual function if there's a function with `Print` name for the current class, even though it doesn't match the sugnature?

**Comment by nurmukhametov** [comment]
> Why is that? Does it stop searching for virtual function if there's a function with `Print` name for the current class, even though it doesn't match the sugnature?

I don't know. `Print()` is not virtual.
