### ISSUE TITLE
Implicitly casting to double seems to work incorrectly

### ISSUE THREAD

**Issue by ColonelPhantom** [ispc/ispc#2808]
Hi,

I was trying out some different programming languages for parallel stuff using the Mandelbrot set, and noticed that ISPC did some dodgy casting.

In particular, I defined
```c
export void mandelbrot_row(..., int h, int w, ...) {
    foreach(x = 0 ... w) {
        ...
        double Cr = (2.0*x/w - 1.5);
        ...
    }
}
```
which I copy-pasted directly from my original C code (which I adapted from the [Benchmarks Game](https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/mandelbrot-gcc-2.html)). However, ISPC gave subtly different results, making me suspect a compiler bug.

It seems like ISPC is casting incorrectly; the ints are likely being casted too late or going int->float->double. Changing the code to 

```c
double Cr = (2.0*(double)x/(double)w - 1.5)
```
fixes it and results in the same image as the original C code.

It would probably be good if ISPC matched C's behavior here.

If desired, I can probably minimize my reproducer somewhat and post it here :)

**Comment by MkazemAkhgary** [comment]
This is the expected behavior. in the documentation it is mentioned:

> Literal floating-point constants (even without a f suffix) are currently treated as being float type, not double. To have a double precision floating point constant use d suffix.

in your code, you should replace `2.0` with `2.0d` to actually get a double literal. no need to cast integers to doubles in your case.

**Comment by nurmukhametov** [comment]
> This is the expected behavior. in the documentation it is mentioned:
> 
> > Literal floating-point constants (even without a f suffix) are currently treated as being float type, not double. To have a double precision floating point constant use d suffix.

Yes, it is so. This is unfortunate mismatch with C language where "An unsuffixed floating constant has type double. If suffixed by the letter f or F, it has type float. If suffixed by the letter l or L, it has type long double" quoted from C11 standard Section 6.4.4.2.

**Comment by dbabokin** [comment]
It's a deliberate design decision in the language to treat floating point literal as `float`, not as `double` **by default**.

The reasoning is that occasional use of doubles in vector code is very harmful for performance, as unlike in scalar code, doubles take 2x registers and 2x compute and that's on top of slower computations and conversion operations overhead itself.

**Comment by ColonelPhantom** [comment]
> in your code, you should replace `2.0` with `2.0d` to actually get a double literal. no need to cast integers to doubles in your case.

Ah yeah, that did the trick as well.



> It's a deliberate design decision in the language to treat floating point literal as `float`, not as `double` **by default**.

Ideally, wouldn't this depend on the desired output type? e.g. here I'm looking for a double in the end, so (to me) it would make sense to 'widen' the in-between computations as well. If the expression results in a float then using a single-precision literal is of course the right choice.

**Comment by dbabokin** [comment]
> Ideally, wouldn't this depend on the desired output type? e.g. here I'm looking for a double in the end, so (to me) it would make sense to 'widen' the in-between computations as well. If the expression results in a float then using a single-precision literal is of course the right choice.

Such typing rules would require not just changing the default for literals, but involve completely different logic of type inference. ISPC tries to stay as much as possible C/C++ like - i.e. the rules are mostly changed only to avoid sharp corners when operating in SIMD world. But completely changing the type casting / type inference logic is much harder to learn for programmers coming from C/C++ world.

But I do see the value for such kind of rules in pythonic / AI world.

**Comment by ColonelPhantom** [comment]
Makes sense. I was coming at it from an angle of 'trying to make ISPC behave closer to C' by 'widening' to what C does in cases where it likely would have been desired.

In any case, for my use case simply using the `d` suffix fully solved the problem. Feel free to close this issue, unless you consider doing this valuable in some cases?

Although it would probably be a bad idea anyway, since it could lead to non-obvious performance regressions when compiling the same program with a newer ISPC version.
