### ISSUE TITLE
Generate built-in dispatch.ll from C source

### ISSUE THREAD

**Issue by nurmukhametov** [ispc/ispc#2816]
It looks like there is no real reason to have dispatch*.ll files manually generated from `dispatch.c` source. It can be generated during ISPC build process.

Due to missing tests for dispatch logic, it depends on #2815

**Comment by dbabokin** [comment]
Not a call to action, but just to add broader context here. The logic of dispatch module exists in ISPC compiler in 3 different incarnations:
- dispatch.ll - library code that is injected into user binary when auto-dispatch feature is used (i.e. multiple targets are specified in the command line)
- the code checking the ISA of the host where ISPC binary is executed (to determine the target when `--target=host` is specified) - it's part of the compiler itself. [lGetSystemISA()](https://github.com/ispc/ispc/blob/166afe06c622ce6b3842c0531f4df9727d41d0d4/src/ispc.cpp#L129) function in `ispc.cpp`.
- the code of [check_isa.cpp](https://github.com/ispc/ispc/blob/main/check_isa.cpp) - which is standalone utility reporting the ISA of the machine where it is executed on.

I thought about unifying all there 3 places, but they have different requirements and probably unification introduces more problems than brings value.
