### ISSUE TITLE
Add ARM jobs into CI

### ISSUE THREAD

**Issue by nurmukhametov** [ispc/ispc#2817]
At the moment, there is no ARM jobs build and tests in CI. There is a self-hosted ARM runner that can be used for them.

According to https://github.com/ispc/ispc/pull/2810#discussion_r1540400049,  we used to have them in Travis to test ARM.

**Comment by emoon** [comment]
You can use macOS M1 runners for ARM tests if you want https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source
