### ISSUE TITLE
SDE fails on avx512 targets for x86 

### ISSUE THREAD

**Issue by nurmukhametov** [ispc/ispc#2818]
We have suspicious fails in the full run of CI tests for all flavors of avx512 targets for x86 on Linux ([run](https://github.com/ispc/ispc/actions/runs/8463647186), [avx512spr-x8](https://github.com/ispc/ispc/actions/runs/8463647186/job/23187100200)). 

After https://github.com/ispc/ispc/pull/2814, we have an alloy logs as artifacts for this job. According to them, all tests fail with the same error:
```bash
Test ./tests/coalesce-8.ispc failed (return code -6)  
A: /tmp_proj/sde_jenkins/workspace/pypl-sde-nightly-master/GitSDE-master-9.33.0-dev-10-g6ddc3c13b/pin/Source/pin/core_ia32_u/ins_syscall_ia32_unix.cpp: INS_SyscallType: 60: Unknown system call instruction
################################################################################
## STACK TRACE
################################################################################
LEVEL_BASE::MESSAGE_TYPE::MessageNoReturn+0x32 at /home/runner/work/ispc/ispc/sde-external-9.33.0-2024-01-07-lin/ia32/pinbin+0xfbc72 

LEVEL_CORE::INS_SYSCALL_INFO::Init+0x1a0 at /home/runner/work/ispc/ispc/sde-external-9.33.0-2024-01-07-lin/ia32/pinbin+0x1873a0 

LEVEL_VM::REGION::CreateVmsvcEmuArgs+0x57 at /home/runner/work/ispc/ispc/sde-external-9.33.0-2024-01-07-lin/ia32/pinbin+0x1f0f77 

LEVEL_VM::REGION::XlateEmu+0x7c at /home/runner/work/ispc/ispc/sde-external-9.33.0-2024-01-07-lin/ia32/pinbin+0x1fe05c 

LEVEL_VM::REGION::XlateSysCall+0x3f at /home/runner/work/ispc/ispc/sde-external-9.33.0-2024-01-07-lin/ia32/pinbin+0x2d6e9f 

LEVEL_VM::REGION::XlateControlFlow+0xad0 at /home/runner/work/ispc/ispc/sde-external-9.33.0-2024-01-07-lin/ia32/pinbin+0x29aae0 

LEVEL_VM::REGION::XlateBbl+0x116 at /home/runner/work/ispc/ispc/sde-external-9.33.0-2024-01-07-lin/ia32/pinbin+0x2a26c6 

LEVEL_VM::REGION::Xlate+0x59 at /home/runner/work/ispc/ispc/sde-external-9.33.0-2024-01-07-lin/ia32/pinbin+0x1fbcf9 

LEVEL_VM::REGION::XlateAndInstrument+0x178 at /home/runner/work/ispc/ispc/sde-external-9.33.0-2024-01-07-lin/ia32/pinbin+0x1fd3d8 

LEVEL_VM::REGION::MakeApplication+0xf2 at /home/runner/work/ispc/ispc/sde-external-9.33.0-2024-01-07-lin/ia32/pinbin+0x1fdea2 

??? at /home/runner/work/ispc/ispc/sde-external-9.33.0-2024-01-07-lin/ia32/pinbin+0x1b2993 

LEVEL_VM::JIT::CompileInternal+0x25c at /home/runner/work/ispc/ispc/sde-external-9.33.0-2024-01-07-lin/ia32/pinbin+0x1b459c 

LEVEL_VM::CompileInternalWrapper+0x2b at /home/runner/work/ispc/ispc/sde-external-9.33.0-2024-01-07-lin/ia32/pinbin+0x1b64db 

Detach Service Count: 1820
Pin: pin-3.31-98831-c93ba16fe
Copyright 2002-2024 Intel Corporation.
```

I didn't manage to reproduce these fails on:
1.  Linux with 12th Gen Intel(R) Core(TM) i9-12900
2. WSL with 11th Gen Intel(R) Core(TM) i7-1185G7

but I did manage to reproduce them on:
1. Linux with AMD Ryzen 7 7840HS

**Comment by dbabokin** [comment]
This needs to be reported to SDE team. It looks like a bug in SDE.

**Comment by nurmukhametov** [comment]
Pin Readme (a.k.a release notes [link](https://software.intel.com/sites/landingpage/pintool/docs/98830/README)) says that:
>    o Pin has not been tested on systems with non-Intel processors.
     Therefore, incompatible or proprietary instructions in non-Intel processors may cause 
     Pin to function incorrectly. Any attempt to instrument code not supported by Intel 
     processors may lead to failures.

**Comment by dbabokin** [comment]
Looks like we need to disable these targets. We should either disable them in CI, or do the check in `alloy.py`, which disables the run if it's 1) AMD paltform, 2) Linux, 3) `x86` 4) SDE is required for the target.
