### ISSUE TITLE
Doxygen

### ISSUE THREAD

**Issue by nurmukhametov** [ispc/ispc#2888]
Apparently, there is https://ispc.github.io/doxygen/ but it is outdated (v1.13.0). Do we need it? If we need it then we need to update it, otherwise just delete it with related files.

**Comment by dbabokin** [comment]
We use to build doxygen and have it for the release on our website. But I don't find it very useful. Modern IDE do better job in terms of source code browsing, at least for the code size of ISPC codebase.

My vote is for removing it.
