### ISSUE TITLE
Dead-code elimination of alternative implementation of exported functions

### ISSUE THREAD

**Issue by zephyr111** [ispc/ispc#2902]
Hello,

When a function is exported, ISPC usually generates 2 implementations. One which can be called from outside the translation unit (eg. from a C/C++ code) and a local one. When the local one is not useful (ie. never called nor even referenced somewhere), the dead code is not eliminated. This is common with exported functions since they are not called/reference internally most of the time.

[Here](https://godbolt.org/z/sfc1KGTW8) is an example on GodBolt where we can see that the function `compute` is compiled to 2 versions; `compute___un_3C_und_3E_unu` and `compute`. I think the former is not useful and should be automatically removed from the generated assembly code (and binaries). 

This issue results in bigger binaries and less readable assembly code (harder to analyse due to a twice bigger code).

Can this be done automatically? 
If no, is there any way to tell the compiler not to generate the `compute___un_3C_und_3E_unu` function (or to do a more aggressive dead-code optimisation)?

Version: ISPC trunk (>=1.24.0)

**Comment by nurmukhametov** [comment]
It is not the compiler's job to optimize them out. It is up to the linker to do so.

Usually, in the case of `C/C++`, this is done by providing `-ffunction-sections` to the compiler and `--gc-sections` to the linker. The compiler places every function in a separate section, and the linker removes unused sections when the final executable is linked.

Unfortunately, `ISPC` does not currently have an option to place functions in separate sections. However, this can be addressed to resolve the issue.

**Comment by aneshlya** [comment]
If you don't need declaration of exported function in the header file, you can try replacing `export` specifier with `extern "C"`. It will generate only one version of function. You can check the difference between `export` and `extern "C"` functions in the table [here](https://ispc.github.io/ispc.html#interoperability-overview).

**Comment by zephyr111** [comment]
Thank you @aneshlya, It perfectly fits my needs : it divides by ~2 the size of the ISPC generated assembly code (which is great for debugging/profiling), reduces the size of the generated binaries and also speed up compilation!
Thank you @nurmukhametov for this information. I did not know that.

Should I close this issue or left it open (regarding the implementation of linker sections)?

**Comment by aneshlya** [comment]
Let's keep it open.

**Comment by pbrubaker** [comment]
If you are reviewing disassembly interactively on a tool like Compiler Explorer, you don't need to add `extern "C"` you can just remove the export keyword.
