### ISSUE TITLE
Automate security scans

### ISSUE THREAD

**Issue by aneshlya** [ispc/ispc#2913]
- [x] Coverity scans
- [x] Binary check: https://github.com/intel/cve-bin-tool
- [x] Trivy for containers
- [ ] Bandit scan for Python
- [x] Malware scanning (we can use ClamAV as part of ubuntu CI runner)

Later we can add 

- [x] Fuzzing for loops (Yarpgen)
- [ ] Fuzzing for different types of inputs: https://github.com/google/oss-fuzz)

**Comment by llindsaya** [comment]
Would it be easier to use https://github.com/intel/cve-bin-tool-action?
