### ISSUE TITLE
template<int C> as compile-time constant?

### ISSUE THREAD

**Issue by iperov** [ispc/ispc#2938]
```cpp
template <int C> void func()
{
    float O[C] = {0}; // Error: Array dimension must be a compile-time constant.
}
```

**Comment by aneshlya** [comment]
It's not supported right now but there are plans to add it. Not sure when we will add it though. Definitely not in 1.25.0 but probably in 1.26.0.
See related issues: #2522 and https://github.com/ispc/ispc/issues/2737.
After #2522 is done it might be possible to use template parameter in arrays and short vectors dimension and SOA.

I'll close this issue as a duplicate.
