### ISSUE TITLE
provide alloca() in stdlib

### ISSUE THREAD

**Issue by mmp** [ispc/ispc#294]

**Comment by jomeng** [comment]
I'd like to bump this, at least for uniform arrays, to make this possible:

```cpp
uniform unsigned int getNumberOfElements() {...}
uniform float *stackArray = alloca(getNumberOfElements());
```

That would be incredibly useful!

**Comment by dbabokin** [comment]
Note, ``alloca()`` is a feature that would be difficult to bring to GPU.

Other than that, it makes sense to add.

**Comment by jomeng** [comment]
Are there any updates on this issue? Will this be implemented?

**Comment by pbrubaker** [comment]
While I think this should be implemented in stdlib, you can work around it not being there.

In your C/C++ code:

`extern "C"
{
	void* Alloca(unsigned int bytes)
	{
		return alloca(bytes);
	}
};`

In ISPC code:

`extern "C" void *uniform Alloca(uniform unsigned int size);`

Then use `Alloca()` how you would normally use `alloca()`  I tested this with Visual Studio 2015 and it worked fine.

`export void crossProductAoStoSoA(uniform Vector4 a[], uniform Vector4 b[], uniform Vector4 c[], uniform size_t N, uniform int& simd_width)
{
	simd_width = programCount;

    // N must be a multiple of programCount
    // otherwise it's possible to read and write
    // beyond the end of the arrays
    assert(N % programCount == 0);

	// test compile
	uniform Vector4* uniform tmp = (uniform Vector4* uniform) Alloca( sizeof(uniform Vector4)*programCount );
    
    for (uniform int i = 0; i < N; i += programCount)
    {
        varying float ax, ay, az, aw;
        varying float bx, by, bz, bw;

        aos_to_soa4( &(a[i].x), &ax, &ay, &az, &aw );
        aos_to_soa4( &(b[i].x), &bx, &by, &bz, &bw );

        varying float cx = ay * bz - az * by;
        varying float cy = az * bx - ax * bz;
        varying float cz = ax * by - ay * bx;
        varying float cw = 0.0f;

        soa_to_aos4(cx, cy, cz, cw, &(tmp[0].x) );

		memcpy(&(c[i].x), &(tmp[0].x), sizeof(uniform Vector4)*programCount);
    }
}`

**Comment by jomeng** [comment]
Hi,

thanks for this reply! I'm not sure the solution, though, as the memory allocated using `alloca` is freed when the calling function returns. Here are two links to compare:

[MSVC](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/alloca?view=msvc-160)
[GNU Gnulib](https://www.gnu.org/software/gnulib/manual/html_node/alloca.html)

The only way to avoid that, it seems to me, is to inline the wrapper function. So maybe this solution is relying on undefined
behaviour?

**Comment by pbrubaker** [comment]
Ugh, my apologies.  Yes, you're right, this wont work.  That function can't
be inlined either.  So the only reason that was working for me was UB.

**Comment by jomeng** [comment]
Hi,

just checking in again on this, and if there are any updates.

Cheers!
