### ISSUE TITLE
aos_to_soa with foreach ?

### ISSUE THREAD

**Issue by iperov** [ispc/ispc#2946]
in foreach index value becomes varying
```c

... , uniform float values[], uniform uint32 W,

foreach(i = 0 ... W)
{
  float v0;
  float v1;
  aos_to_soa2(&values[i], &v0, &v1); 
}
```

```
Error: Unable to find any matching overload for call to function "aos_to_soa2".
Passed types: (uniform float * varying, varying float * uniform, varying float * uniform)
```

**Comment by iperov** [comment]
@aneshlya 
`for (uniform ` is slower than foreach and requires aligned memory or duplicate the code to process tail data.

also 

![firefox_2024-08-10_11-08-52](https://github.com/user-attachments/assets/cd028e7f-0ae4-4b48-b208-2f45c2781d48)

documentation offers to use foreach as replace of `for (uniform`

but `foreach`'ed variable becomes varying and makes aos_to_soa2 unusable.

So developers commentary is needed.

**Comment by iperov** [comment]
also `foreach (uniform y=0` doesn't work

**Comment by aneshlya** [comment]
The usual approach is to use uniform counter like `baseAddr ` below:
```
uniform float values[];
uniform uint32 baseAddr = 0;
foreach(i = 0 ... W) {
    float v0;
    float v1;
    aos_to_soa2(&(values[baseAddr]), &v0, &v1 );
    baseAddr += programCount * 2;  // We loaded programCount * 2 floats, so advance by that amount.
}
```

**Comment by zephyr111** [comment]
> `for (uniform` is slower than foreach and requires aligned memory or duplicate the code to process tail data.

It should not be slower. 

Please note that **`soa_aos*` functions do not consider the program execution mask** so this is a problem for the last items of a `foreach` unless you know that the number of item is a multiple of `programCount` (though a `foreach` is not really useful in this case) or it is safe to access beyond the limit of the target array (rather unsafe). Note this is mentioned in the documentation:

> Note that these functions do not take the current program execution mask into account; they unconditionally read and write three times the gang size. Hence, if the iteration count is not an integer multiple of the program count, aos_to_soa3() will read past the end of the input data and soa_to_aos3() will write past the end of the output data. [...]

Regarding code duplication, functions can help to reduce it in this case (though it can impact performance, especially when function mutate input arguments passed by reference).

**Comment by iperov** [comment]
@aneshlya it works and gives 16% boost, but it's so not obvious !

```c
uniform uint32 baseAddr = 0;
foreach(i = 0 ... W) {

    // how we can know that baseAddr here is actually +programIndex ?

    aos_to_soa2(&(values[baseAddr]), &v0, &v1 );
    baseAddr += programCount * 2;  // here it is incremented like 8*2
}
```

**Comment by aneshlya** [comment]
The foreach loop counter is basically `programCount*i + programIndex`.
`aos_to_soa2` loads two times the `programCount` size values from the given array starting at the given offset, returning two varying results so when we update uniform counter we multiply it by 2.
Also as @zephyr111 mentioned:  when you use `aos_soa` functions, ensure that the data buffers have a size that is a multiple of `programCount`, so that the read/write overflow does not cause memory corruption. So if your data is guaranteed to be the size which is multiple of `programCount`, `foreach` + `aos_soa` is the way to go. If not, I'd go with uniform `for` loop and implemented remainder logic using shuffles.

**Comment by iperov** [comment]
>  if your data is guaranteed to be the size which is multiple of programCount, foreach + aos_soa is the way to go

there are no cases where data will be a multiple of programCount .
I don't know programCount on the user's computer.
Data can be of size W*2

**Comment by aneshlya** [comment]
@iperov, do you have other questions about aos_to_soa or we can close the issue?
