### ISSUE TITLE
Add compiler option to only emit C++ callable export functions

### ISSUE THREAD

**Issue by rkaric** [ispc/ispc#2995]
Given the following code: https://godbolt.org/z/E3449vvdG

ISPC generates two callable functions, one for C++ and another for C. It would be very helpful to have a compiler option to only generate the C++ version.

If the C version is unused it will be removed as dead code in optimized builds. This would still be useful for Debug builds and generally to improve compile times.

**Comment by nurmukhametov** [comment]
It looks same as #2902.

Indeed, there are two versions but one is for C/C++ (unmangled one `ArrayMax`) and the other is for ISPC code (`ArrayMax___un_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_Cuni` mangled one and contains an extra mask argument).

If some function is for external only calls (from C/C++) then you may specify `extern "C"` instead of `export`, i.e., `extern "C"` is the option you are looking for.

**Comment by rkaric** [comment]
While that is an option, there are situations where you want to exclusively call the C++ version and not the C version. The generate functions prototypes are placed into their own namespace and declared for you as part of the compilation process. This is not the case when using `extern "C"`.

One other thing to note, since it's up to the linker to remove dead code there may variation between toolchains on how well that works. Epic Games has reported that the Apple toolchain does not remove the dead C code while I've confirmed that MSVC does.

**Comment by nurmukhametov** [comment]
I don't understand what it is C++ version you are talking about. In the generated code there are only two functions, the one is for ISPC code, the other for C/C++.

**Comment by nurmukhametov** [comment]
> This is not the case when using `extern "C"`.

Ah, OK. The problem of `extern "C"` is that ISPC doesn't generate declarations for them in the `-h` header file (it is unexpected for me).

Probably, there are twoapproaches (except the `-ffunction-sections`/`--gc-section` mentiond #2902):
1. Add declarations for `extern "C"` functions to the generated header file. Users then need to change `export` to `extern "C"` in their code to avoid extra copies.
2. Add an extra qualifier for `export` keyword, e.g., `export "C"`. In that case, ISPC generates only the externally called function and add its declaration as it happens now for `export` keyword. Users need to change `export` to `export "C"` to avoid an extra function copy. We may also have `export "ISPC"`.

**Comment by rkaric** [comment]
> I don't understand what it is C++ version you are talking about. In the generated code there are only two functions, the one is for ISPC code, the other for C/C++.

The C++ version I'm referring to in the example above is the one with the label `ArrayMax___un_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_Cuni`. That looks like a lot like a C++ name mangled function. The C version is an exact copy starting at the `ArrayMax` label on Line 22.

The goal here is to only generate only one function if possible for either C or C++. Your suggestion of adding an additional export qualifier sounds like this could address the concern.

**Comment by nurmukhametov** [comment]
I have created PR introducing `-ffunction-sections` #2997.
