### ISSUE TITLE
Templates and regular functions can't have the same name

### ISSUE THREAD

**Issue by aneshlya** [ispc/ispc#3015]
This code produces: `Unable to find any matching overload for call to function "func"`
```
varying int32 func(varying int32 a, varying int32 b);
uniform int32 func(uniform int32 a, uniform int32 b);
template <typename T>
uniform T func(uniform T a, uniform T b, uniform int c)
{
    uniform T r = func(a, b);
    return r;
}
uniform int foo2(uniform int a, uniform int b, uniform int c) {
    return func<uniform int>(a, b, c);
}
```
Looks like templates and regular functions can't have the same name.
https://github.com/ispc/ispc/blob/main/src/expr.cpp#L8327-L8339

**Comment by nurmukhametov** [comment]
Fixing this should unlock broader support for short vectors in stdlib, as requested here: #2707.
