### ISSUE TITLE
Use of -MF flag in v1.25.0 emits compile warnings/errors

### ISSUE THREAD

**Issue by jsiwek** [ispc/ispc#3062]
I use a CMake integration that seems to add ISPC flags like `-M -MT foo.obj -MF foo.obj.d`.  When moving from v1.24.0 to v1.25.0, I see warnings/errors (depending on use of `-werror`) like:  `Emitting dependencies file, but filename "foo.obj.d" has suffix "d"?`

With all the confidence of one who briefly looked at the code for the first time to see if there's an easy hack I can do myself if I have to: getting back to equivalent behavior of v1.24.0 may be a simple change in `OutputTypeInfo::isSuffixValid()` to return true if the `validSuffixes` member vector is empty, like it is for dependencies.

https://github.com/ispc/ispc/blob/b0d935e52aa8d9b03cedd0113d6c44f5be233f57/src/module.cpp#L1550

https://github.com/ispc/ispc/blob/b0d935e52aa8d9b03cedd0113d6c44f5be233f57/src/module.h#L138-L150

https://github.com/ispc/ispc/blob/b0d935e52aa8d9b03cedd0113d6c44f5be233f57/src/module.cpp#L1574-L1578

**Comment by aneshlya** [comment]
Thanks for quick report of this issue. We'll create a new minor release to address this.
