### ISSUE TITLE
Using assume to remove extra brances and tails

### ISSUE THREAD

**Issue by emoon** [ispc/ispc#3065]
Hi,

I'm trying to use the `assume` compiler hint to git rid of extra checks/branches as I know in my case that a count variable will always be a multiple of `programCount` What I tried is this

```C
export void add_values(uniform float out[], uniform float input[], uniform int count) {
    assume(count % programCount == 0);

    for (uniform int i = 0; i < count; i += programCount)  {
        out[i + programIndex] = input[i + programIndex] + input[i + programIndex];
    }
}
```
Looking at the generated code here https://godbolt.org/z/f3a3rf6rf there are still lots of checks happening. I wonder if there is a way to improve this?

**Comment by aneshlya** [comment]
There are code for two versions of `add_values` function generated:
1. internal masked version add_values___un_3C_unf_3E_un_3C_unf_3E_uni (for calling inside ISPC module)
2. external unmasked version add_values (for calling from C++ side)

Internal version generates all code "masked" so there will be lots of additional checks. 
External version has only checks related to unrolling so you may try to adjust unrolling factor.
If you want to keep only external version of the function you can mark it with `__attribute__((external_only))` attribute.

**Comment by aneshlya** [comment]
@emoon , was your issue resolved?

**Comment by aneshlya** [comment]
I'm closing this issue. Feel free to re-open if your question was not resolved.
