### ISSUE TITLE
core.isph and stdlib.isph may still be registered as dependencies in v1.25.1 on Windows?

### ISSUE THREAD

**Issue by jsiwek** [ispc/ispc#3066]
Follow up to #3062, particularly bad9ac20aae0adbfdf5a285a10b31ca024d0cc04: in a CMake+Ninja build system using Windows OS and ISPC v1.25.1, I see ISPC object files always being treated as dirty and rebuilt.  They also report dependencies on non-existing files `c:/core.isph` and `c:/stdlib.isph` -- I don't know exactly whether having those as missing file dependencies entirely explains and translates to the undesired always-dirty+rebuild behavior I see, but it's a suspect.  Maybe this platform-dependent handling:

https://github.com/ispc/ispc/blob/bad9ac20aae0adbfdf5a285a10b31ca024d0cc04/src/module.cpp#L2994-L3000

simply needs to be factored out and re-used in the following logic rather than the hardcoded `/` file prefix or else use some other way to identify those "files" in a platform-independent way ?

https://github.com/ispc/ispc/blob/bad9ac20aae0adbfdf5a285a10b31ca024d0cc04/src/module.cpp#L163-L164

**Comment by nurmukhametov** [comment]
Thanks for reporting this issue. Yes, windows specific paths were overlooked in https://github.com/ispc/ispc/commit/bad9ac20aae0adbfdf5a285a10b31ca024d0cc04.

> I don't know exactly whether having those as missing file dependencies entirely explains and translates to the undesired always-dirty+rebuild behavior I see, but it's a suspect.

I am sure this is a reason. BTW, what project do you build?

**Comment by jsiwek** [comment]
> BTW, what project do you build?

Not a public one if you were hoping for exact way to repro, but let me know if you can't and want me to try making a minimal test case.

**Comment by nurmukhametov** [comment]
@jsiwek , could you check with your project that undesired always-dirty+rebuild behavior is fixed by #3077? You can download the archive with ISPC binary from PR appveyor job.

**Comment by jsiwek** [comment]
The build from #3077 does fix my issue, thanks.
