### ISSUE TITLE
Backport a LLVM patch for #2954 to earlier versions.

### ISSUE THREAD

**Issue by aneshlya** [ispc/ispc#3101]
Here is a note https://github.com/ispc/ispc/issues/2954#issuecomment-2438529795 when it started passing to help finding the patch.

**Comment by nurmukhametov** [comment]
This test was fixed by https://github.com/llvm/llvm-project/commit/795c24c6fb4f9635c912f4084fa9339ea068c3d5 (PR https://github.com/llvm/llvm-project/pull/109689).
