### ISSUE TITLE
standard library ldexp does not handle x=0

### ISSUE THREAD

**Issue by sjb3d** [ispc/ispc#3115]
Hi, the implementation of `ldexp(x, n)` in the ISPC standard library does not seem to handle the case where `x` is 0.

Some example results from a test case where 0 is expected for all outputs:
```
ldexp(0e0, -4) = -4.2535296e37
ldexp(0e0, -2) = -1.7014118e38
ldexp(0e0, 2) = 2.3509887e-38
ldexp(0e0, 4) = 9.403955e-38
```

This can be problematic when `n` is negative, as it results in high-exponent floating-point output, which can cause issues in code ported from C or GPU shading languages. In particular I found this issue moving code from HLSL, where the zero case is handled correctly (returning 0 with sign bit preserved), and have to replace the code with `x * ldexp(1.0f, n)` for correct results.

If matching this behaviour is not considered to be worth the performance cost, I think it would at least be good to mention this case somewhere in the standard library docs!

**Comment by aneshlya** [comment]
Thanks for reporting this. I think it should be fixed even with performance cost. 
Related to https://github.com/ispc/ispc/issues/2236.
