### ISSUE TITLE
Consider adding reduce_or and reduce_and to standard library

### ISSUE THREAD

**Issue by sjb3d** [ispc/ispc#3125]
Reductions using bitwise or/and can be useful to merge bitfields for active instances, but it seems like these are currently not provided. Could these be considered for a future release?

(It seems that atomics and `exclusive_scan` is already provided for bitwise or/and, but curiously not `reduce`, so I hope this would be considered in scope for the standard lib!)

**Comment by pbrubaker** [comment]
If I'm understanding correctly, it seems like `any()`, `all()`, `none()` and `lanemask()` should be able to provide what you need.

**Comment by pbrubaker** [comment]
What use case were you picturing?  Could `any(),` `all(),` `none()` or `lanemask()` work instead?

**Comment by sjb3d** [comment]
Hi, my use case is to merge some per-thread flags (bits of a `varying` u32) into a single uniform value for the whole gang.

Currently I'm using `atomic_or_local` into a uniform value on the stack, and this works fine.

For this case the control flow is pretty simple, so probably I could change the code to store the flags as a `uniform` variable all the time, and just use `any` on the conditions that set bits, I think that would also work and then not need a reduce afterwards.

I guess this is a bit of niche use case, these reductions just seemed like a missing bit of the standard library, thought I should raise an issue in case this was an easy fix of an unintentional oversight.

**Comment by sjb3d** [comment]
Update: yep so using `any` on the conditions, and keeping the value as `uniform` all the time works fine (and does not require any reduce step any more), thanks for the suggestion!

**Comment by pbrubaker** [comment]
> Update: yep so using `any` on the conditions, and keeping the value as `uniform` all the time works fine (and does not require any reduce step any more), thanks for the suggestion!

So good to hear!  I thought the mask operations might work for you but I wasn't sure.  I'm going to go ahead and close this.
