### ISSUE TITLE
Incorrect error message when building for aarch64

### ISSUE THREAD

**Issue by emoon** [ispc/ispc#3126]
If I compile with commandline (which is incorrect)
```
--target=neon-i8x4
```
I get the following error message
```
Error: Incorrect targets: neon-i8x4. Choices are: sse2-i32x4, sse2-i32x4, neon-i8x16, neon-i32x4, gen9-x8. 
Compiler returned: 255
```
But if you try (which is included in the list above)
```
--target=neon-i8x16
``` 
You will get this error
```
Error: arch = aarch64 and target = neon-i8x16 is not a valid combination. 
Compiler returned: 1
```

**Comment by aneshlya** [comment]
Hi @emoon ,

It's not merged yet but there is upcoming update to the docs that should clarify the situation with neon targets:
https://github.com/ispc/ispc/pull/3121/commits/229b3a607ca78664f4260010828d69c1d7b58116.
The `--target=neon-i8x4` target does not exist.
The `--target=neon-i8x16` supports armv7 (32-bit) only.

Please tell me what is your workflow and what targets on what ARM platforms do you need?

For now we plan to deprecate `neon-i8x16` and `neon-i16x8`, keep `neon-i32x4` and `neon-i32x8` and add sve targets.

**Comment by nurmukhametov** [comment]
I have come across this recently:

```bash
$ ./bin/ispc "--target=sse4.2-i16x8 " t.ispc --emit-llvm-text -o -
Error: Incorrect targets: sse4.2-i16x8 . Choices are: sse2-i32x4, sse2-i32x4, neon-i8x16, neon-i32x4, gen9-x8. 
Compiler returned: 255
```

Note that there is an extra space after the proper target name, but the error message confused me (and I believed for a while that I had misconfigured or broken this target) because there is no sse4.2-i16x8 among the presented choices. It looks like the error message could be improved.

**Comment by aneshlya** [comment]
Yes, that's should be fixed. I also noticed this some time ago. I'll do this.

**Comment by emoon** [comment]
@aneshlya Hey, those targets should be fine for me 👍
