### ISSUE TITLE
ISPC Upgrading from Unreal Engine 5.3 to 5.5 no longer compiles on Windows On Arm for (x86_64)

### ISSUE THREAD

**Issue by deathlyrage** [ispc/ispc#3133]
![Image](https://github.com/user-attachments/assets/9bba7119-8965-4ccd-a661-4450311276bc)

**Repo Steps:**
1. Clone the repo from epic games https://github.com/EpicGames/UnrealEngine.git 5.5 branch
2. run Setup and GenerateProjectFiles.bat
3. Attempt to compile either via visual studio project or via batch / powershell command

I have asked qualcomm for help on the issue they suggested making sure i was using the latest ISPC version.

Unreal 5.5 ships with 1.24. I Updated it to 1.25.3 (8 November 2024) and its still broken.
ISPC exe can be found here: 5.5\Engine\Source\ThirdParty\Intel\ISPC\bin\Windows 

The Test Project I used for the compile was the default unreal engine example project called 'Lyra Starter Game' downloaded from Epic Games Marketplace. However breaks in any workload with ISPC.

Note that ISPC works on normal X86 machines.

Interesting note that Unreal 5.3 did work on ISPC on Windows on Arm which shipped with a older ISPC version which was 1.18.0.

Based upon ISPC updating and that being broken on WOA im guessing its a ISPC issue, however I could use some help on this one. Please note that im using Compiling Unreal for Windows X64 and it's not an Arm Native Compile. 

I have tested this on 2 seperate windows on arm snapdragon machines, One is a Lenovo T14s Thinkpad and one is a Snapdragon Dev Kit 2024.

First time submitting a bug like this so let me know if you have any questions or need any further system information.

**Comment by aneshlya** [comment]
Hi @deathlyrage,

The ISPC binary for Windows provided in ISPC releases on Github is built for x86_64, so it cannot run on an ARM machine. I'm unsure how it worked for you in version 1.18.0—it shouldn't have. The Windows ISPC release binaries on GitHub have always been built for x86_64.

While we do include an ISPC binary for aarch64 in the Linux releases, we do not currently provide one for Windows due to hardware availability limitations. If there is a demand for it, we can try to find a build machine for this.

**Comment by aneshlya** [comment]
That's interesting. I didn't know about emulation mode. From the docs I see that the error message "0xc000007b" typically occurs when there's a mismatch between 32-bit and 64-bit dependencies or when required libraries are not present.

So you're saying that in exact the same environment ISPC v1.18.0 was working and ISPC v1.25.3 is not, right?

It would be great to gain access to the ARM machine. I can attempt to do it on my side, and if I'm unsuccessful, I can reach out to you again. Additionally, identifying the specific ISPC version where the issue started would be very helpful, as it would narrow down the changes made to the ISPC build process.

**Comment by aneshlya** [comment]
OK, I set up MS Azure Windows 11 system with Ampere Altra and both ISPC v1.18.0 and 1.25.3 are running fine there.
I installed latest vcruntime for arm64 before running ispc.
I don't have access to Qualcomm HW so I'll appreciate if you can ask them for help.

**Comment by deathlyrage** [comment]
Hi,

It's not that the executable never runs at all, its when we throw this unreal engine 5.5 workload it only on Arm it fails. If that makes sense. It's like the IPSC is executing some code or instruction which makes it fall over.

On the Ampere Altra system can you try the unreal engine 5.5 code checkout and build? I suspect the problem will be reproducable over there potentionally. 

I have double checked the vcruntimes for arm64 and x64 were installed properly before running ipsc.

Thanks,
Matt

**Comment by aneshlya** [comment]
I have reproduced the issue and am currently investigating.

**Comment by aneshlya** [comment]
The issue is only reproducible inside Unreal Engine build. ISPC compilation from command line seems to be working fine (however I'm not completely sure that compiler flags are exactly the same). The problem may be with UE build system.

**Comment by deathlyrage** [comment]
Thanks so much for the help!
