### ISSUE TITLE
Fix unnecessary scalarization of some uniform vector type converts

### ISSUE THREAD

**Issue by mmp** [ispc/ispc#33]
(See comment around line 4013 of expr.cpp, in TypeCastExpr.cpp.)

Currently, when we're type converting from e.g. a uniform float<4> to a uniform int<4>, we are still serializing, doing the float->int for each element, even though there's an SSE instruction to do this all at once.  We should special the case of type converting uniform short-vectors to differently-typed uniform short vectors to not seralize in this case.  (We still need the loop over elements for both varying short vectors as well as uniform->varying short-vector type conversions.)

**Comment by aneshlya** [comment]
Fixed by https://github.com/ispc/ispc/pull/2492 and was included to ISPC v1.20.0
