### ISSUE TITLE
Does ispc support Expression Templates C++0x feature? re: Gaalet ...

### ISSUE THREAD

**Issue by Art** [ispc/ispc#341]
Followig Florian Seybold's work Geometric Algebra Algorithm Expression Templates, Gaalet (GraVisMa 2010).
And Dr. Dietmar Hildenbrand et al GAAOptimizer, Gaalop.

Performant parallel system stack?
CGA, C++0x-version, Gaalet, Gaalop, many/multi-core Xeon Phi (MIC)

CGA,      ispc (C++0x-version, Gaalet, Gaalop )   , many/multi-core Xeon Phi (MIC)   ??

Thanks for any feedback.

PLH OOE Art Scott

**Comment by pbrubaker** [comment]
Closing as question answered.
