### ISSUE TITLE
Trouble with "gnu/stubs-32.h"

### ISSUE THREAD

**Issue by mattwalsh** [ispc/ispc#350]
When I compile from source  on a 64-bit Linux machine I hit this:

```
In file included from /usr/include/features.h:385:
/usr/include/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found
# include <gnu/stubs-32.h>
          ^
```

Funny thing (and maybe more serious thing) is, if I then make again it doesn’t fail on this error.

I was able to hack around this by putting a copy I found laying around somewhere in a dir and then changing the Make step for the 32-bit builtins like so:

```
objs/builtins-c-32.cpp: builtins/builtins.c
        @echo Creating C++ source from builtins definition file $<
        @$(CLANG) -I/my_include_place/include -m32 -emit-llvm -c $< -o - | llvm-dis - | python bitcode2cpp.py c-32 > $@
```

It appears this file is not guaranteed to be on a Linux 64-bit system (the stubs-64.h is present, however).

**Comment by lsff** [comment]
@mmp  Thx. It works to me
