### ISSUE TITLE
Crash when trying mandelbrot_tasks

### ISSUE THREAD

**Issue by mattwalsh** [ispc/ispc#379]
Pulled down the latest ispc today (9-13-2012); got this error when doing a make:

[ mandelbrot_tasks]$ make
/bin/mkdir -p objs/
ispc -O2 --arch=x86-64  --target=sse2,sse4-x2,avx-x2 mandelbrot.ispc -o objs/mandelbrot_ispc.o -h objs/mandelbrot_ispc.h
ispc: /usr/pic1/llvm/llvm-3.1.src/include/llvm/CodeGen/LiveInterval.h:130: llvm::LiveRange::LiveRange(llvm::SlotIndex, llvm::SlotIndex, llvm::VNInfo*): Assertion `S < E && "Cannot create empty or backwards range"' failed.
main.cpp(207): FATAL ERROR: Unhandled signal sent to process; terminating.

---

**\* Please file a bug report at https://github.com/ispc/ispc/issues
**\* (Including as much information as you can about how to reproduce this error).
**\* You have apparently encountered a bug in the compiler that we'd like to fix!

---

make: **\* [objs/mandelbrot_ispc.h] Aborted
make: **\* Deleting file `objs/mandelbrot_ispc.h'

**Comment by aneshlya** [comment]
The issue is outdated and not reproducible.
