### ISSUE TITLE
func.cpp:276: Assertion failed: "type->isUnmasked || type->isExported".

### ISSUE THREAD

**Issue by ArchRobison** [ispc/ispc#410]
I'm compiling on a Sandy Bridge system and suffered the assertion failure.  Version of compiler is:

Intel(r) SPMD Program Compiler (ispc), 1.3.0 (build commit b69d783e096e2294 @ 20120628, LLVM 3.2)
## Here is a transcript:

$ ispc tally_ispc.ispc --target=avx
Warning: No output file or header file name specified. Program will be compiled and warnings/errors will be issued, but no
        output will be generated.
tally_ispc.ispc:31:22: Performance Warning: Modulus operator with varying types is very inefficient.
        a[i].pos.x = 3*i % 100 \* 0.02f;
                     ^^^^^^^^^

tally_ispc.ispc:32:22: Performance Warning: Modulus operator with varying types is very inefficient.
        a[i].pos.y = 5*i % 100 \* 0.02f;
                     ^^^^^^^^^

tally_ispc.ispc:33:22: Performance Warning: Modulus operator with varying types is very inefficient.
        a[i].vel.x = 7*i % 100 \* 0.02f;
                     ^^^^^^^^^

tally_ispc.ispc:34:22: Performance Warning: Modulus operator with varying types is very inefficient.
        a[i].vel.y = 11*i % 100 \* 0.02f;
                     ^^^^^^^^^^

func.cpp:276: Assertion failed: "type->isUnmasked || type->isExported".

---

**\* Please file a bug report at https://github.com/ispc/ispc/issues
**\* (Including as much information as you can about how to reproduce this error).
**\* You have apparently encountered a bug in the compiler that we'd like to fix!

---

main.cpp(204): FATAL ERROR: Unhandled signal sent to process; terminating.
## And here is the source file.  It's not necessarily correct ISPC, but should nonetheless not crash the compiler.

struct Point {
    varying float x, y;
};

float SquareOfDistanceFromOrigin( const Point& p ) {
    return p.x_p.x+p.y_p.y;
}

struct Ant {
    Point pos, vel;
};

varying int HitCount;
uniform float Radius;

void CheckHit( Ant a ) {        // Why can't a be passed by const-ref?
    if( SquareOfDistanceFromOrigin(a.pos)<Radius*Radius )
        HitCount += 1;
}

void Update( uniform Ant a[], uniform int n ) {
    for( int i=0; i<n; ++i ) {
        a[i].pos.x += a[i].vel.x;
        a[i].pos.y += a[i].vel.y;
        CheckHit( a[i] );
    }
}

void Init( uniform Ant a[], uniform int n ) {
    for( int i=0; i<n; ++i ) {
        a[i].pos.x = 3_i % 100 \* 0.02f;
        a[i].pos.y = 5_i % 100 \* 0.02f;
        a[i].vel.x = 7_i % 100 \* 0.02f;
        a[i].vel.y = 11_i % 100 \* 0.02f;
    }
}

extern "C" int Run(uniform int n) {
    Ant\* uniform a = uniform new Ant[n];
    Init(a,n);
    HitCount = 0;
    Radius = 1;
    for( int t=0; t<1000; ++t ) {
        Update(a,n);
    }
    int  m = HitCount;
    delete[] a;
    return m;
}

**Comment by aneshlya** [comment]
The compiler doesn't crash anymore for this case starting from ISPC v1.12.0.
