### ISSUE TITLE
Disabling warnings locally

### ISSUE THREAD

**Issue by tkoziara** [ispc/ispc#537]
Would it not be useful to have a local #pragma to disable performance warnings per line?

Working on a larger code, where some bits need to stay as they are while other get developed, I would personally find it quite useful. Now vim keeps jumping to those uninteresting warnings. Such #pragmas would at the same time mark bits of the code that may require attention in the future.

**Comment by emoon** [comment]
Any plans on supporting something like this? I have seen some code (from the Intel Texture Compressor) that does this

```
inline float gather_float(varying float* uniform ptr, int idx)
{
	return ptr[idx]; // (perf warning expected)
}

**Comment by dbabokin** [comment]
That would be nice to have, but it's not in my plans at the moment. Pull requests are welcome.

**Comment by dbabokin** [comment]
Fixed. See #1342 for details.

**Comment by emoon** [comment]
Awesome! Thanks for adding this :)
