### ISSUE TITLE
feature: #pragma unroll support

### ISSUE THREAD

**Issue by 3gx** [ispc/ispc#548]
Is there support for #pragma unroll [n] for loop unrolling, like in CUDA, e.g.

```
#pragma unroll 2
for (uniform int i = 0; i < N; i++)
 { .. do stuff .. }
```

where `N` can be either a runtime or a compile-time parameter? If not, are any plans to add this feature and/or how much work is required to accomplish this?

**Comment by dbabokin** [comment]
CC @JeffRous here.

**Comment by JeffRous** [comment]
+1. This is especially useful for loops that do a small number of things with many iterations, like sum an array.

**Comment by DeepakRajendrakumaran** [comment]
https://github.com/ispc/ispc/pull/1880 - fixed with this commit.
