### ISSUE TITLE
SVML is missing

### ISSUE THREAD

**Issue by 3gx** [ispc/ispc#573]
I just noticed that SVML was removed from ispc. This is not cool, as it makes ispc less friendly to scientific HPC codes, in which lots of things must be done in double precision, like pow, log, etc.. 

I noticed also that default library serialises log/pow operations, and this hits performance quite badly (I am currently working on a code, and was unable to get speed-up with ispc vs icc, mostly because pow/log was serialised).

Is it possible to restore SVML functionality; alternatively, any help on how to get double precision vector functions for pow/log will be highly appreciated.

Cheers,
  Evghenii

**Comment by RoyiAvital** [comment]
Anything new about SVML support?

**Comment by dbabokin** [comment]
@RoyiAvital No news on this front. Do you want to use SVML in ISPC?

**Comment by RoyiAvital** [comment]
Yes. It would be great. As SVML is significantly faster than any other Math library out there.
I saw that Intel contributed some of the Math in SVML to GCC.

Could it do it in this project as well?

**Comment by dbabokin** [comment]
I'm going to close this issues with #2195, which fixes all known problems with SVML support: add support for more functions and enables all x86 targets to support SVML (both float and double types).

As for adding some of SVML function implementations to ISPC (as it was done with GCC), we should be able to do that, but no promises yet.

**Comment by RoyiAvital** [comment]
This is so great!

It will be great to have an example in documentation for this.
