### ISSUE TITLE
extern C produces func.cpp:284: Assertion failed: "type->isUnmasked || type->isExported"

### ISSUE THREAD

**Issue by ingowald** [ispc/ispc#598]
Simple hello world fct tagged as 'extern C' throws assertion.

reproducer
<helloWorldISPC.ispc>
extern "C" 
  void ispc_printHelloWorld()
  {
    print("hello world from ISPC\n");
  }
</helloWorldISPC.ispc>

Cmdline:

ispc -I /home/wald/Projects/OSPRay/apps/testing -D__SSE4__ --pic -O1 --target sse4 --wno-perf --opt=fast-math --opt=force-aligned-memory -h /home/wald/Projects/OSPRay/sse/apps/testing/helloWorldISPC_ispc.h -o /home/wald/Projects/OSPRay/sse/apps/testing/helloWorldISPC.dev.o -MMM /home/wald/Projects/OSPRay/sse/apps/testing/helloWorldISPC.dev.idep /home/wald/Projects/OSPRay/apps/testing/helloWorldISPC.ispc
func.cpp:284: Assertion failed: "type->isUnmasked || type->isExported".

version:
wald@w510 ~/Projects/OSPRay/sse $ ispc --version
Intel(r) SPMD Program Compiler (ispc), 1.4.5dev (build commit 1913199a4505a5f9 @ 20130921, LLVM 3.3)
wald@w510 ~/Projects/OSPRay/sse $ uname -a
Linux w510.localdomain 2.6.32-358.14.1.el6.x86_64 #1 SMP Tue Jul 16 23:51:20 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aneshlya** [comment]
This case works staring from ISPC v1.19.0.
