### ISSUE TITLE
extern C block doesn't allow function body

### ISSUE THREAD

**Issue by ingowald** [ispc/ispc#599]
extern "C" {
  void ispc_printHelloWorld()
  {
    print("hello world from ISPC\n");
  }
}

produces:
wald@w510 ~/Projects/OSPRay/sse $ ispc -I /home/wald/Projects/OSPRay/apps/testing -D__SSE4__ --pic -O1 --target sse4 --wno-perf --opt=fast-math --opt=force-aligned-memory -h /home/wald/Projects/OSPRay/sse/apps/testing/helloWorldISPC_ispc.h -o /home/wald/Projects/OSPRay/sse/apps/testing/helloWorldISPC.dev.o -MMM /home/wald/Projects/OSPRay/sse/apps/testing/helloWorldISPC.dev.idep /home/wald/Projects/OSPRay/apps/testing/helloWorldISPC.ispc
/home/wald/Projects/OSPRay/apps/testing/helloWorldISPC.ispc:4:3: Error: 
        syntax error, unexpected '{', expecting ',' or ';'. 
  {
  ^

Using freshly updated and rebuilt github version:
wald@w510 ~/Projects/OSPRay/sse $ ispc --version
Intel(r) SPMD Program Compiler (ispc), 1.4.5dev (build commit 1913199a4505a5f9 @ 20130921, LLVM 3.3)

**Comment by aneshlya** [comment]
ISPC doesn't support `extern "C"`  blocks. However definition of extern "C"  functions is supported staring from ISPC v1.19.0.
```
extern "C" void ispc_printHelloWorld() {
    print("hello world from ISPC\n");
}
```

**Comment by aneshlya** [comment]
Support of multiple function definitions/declarations inside `extern "C"` is covered by #385. I'm closing this one as duplicate.
