### ISSUE TITLE
Bug printing bools.  Bools have correct value but false gets printed as "true".

### ISSUE THREAD

**Issue by tkoziara** [ispc/ispc#662]
See the code attached at:

https://groups.google.com/forum/#!topic/ispc-users/zuSa1LAGONA

When doing:

inline static uniform bool isfinite (uniform float x)
{
 return intbits(x) != 0x7F800000 && intbits(x) != 0xFF800000 && !isnan (x);
}

inline static uniform bool isfinite (uniform double x)
{
 return intbits(x) != 0x7FF0000000000000 && intbits(x) != 0xFFF0000000000000 && !isnan (x);
}

export void bug1_ispc ()
{
  uniform float alpha = 0.0;
  uniform double beta = 0.0;

  print ("float 0.0 => !isfinite = %, isfinite = % \n", !isfinite (alpha), isfinite(alpha));
  print ("double 0.0 => !isfinite = %, isfinite = % \n", !isfinite (beta), isfinite(beta));
}

I am getting:
float 0.0 => !isfinite = true, isfinite = true 
double 0.0 => !isfinite = true, isfinite = true

**Comment by aneshlya** [comment]
The issue seems outdated, printing of bools works fine for several releases already.
We have tests for checking this functionality: 

- https://github.com/ispc/ispc/blob/main/tests/print_bool.ispc
- https://github.com/ispc/ispc/blob/main/tests/print_bool_simd.ispc
