### ISSUE TITLE
Internal error / core dump

### ISSUE THREAD

**Issue by ingowald** [ispc/ispc#696]
<test.ispc>
extern "C" void _foo(void_) 
{ return NULL; }
</test.ispc>

wald@latte ~/Projects/ispc $ ./ispc /tmp/test.ispc  --target sse4 -o /tmp/test.o
func.cpp:323: Assertion failed: "type->isUnmasked || type->isExported".

---

**\* Please file a bug report at https://github.com/ispc/ispc/issues
**\* (Including as much information as you can about how to reproduce this error).
**\* You have apparently encountered a bug in the compiler that we'd like to fix!

---

main.cpp(225): FATAL ERROR: Unhandled signal sent to process; terminating.
Aborted (core dumped)

Note: also tried making the pointers explicitly uniform, didn't change anything.

**Comment by aneshlya** [comment]
The assertion was replaced with a nice error `Error: 'extern "C"' function "foo" cannot be defined in ISPC. ` in ISPC v1.12.0. `extern "C"` function definition is supported starting from ISPC v1.19.0.
