### ISSUE TITLE
The benchmark "mandekbrot_tasks" is broken now.

### ISSUE THREAD

**Issue by ifilippov** [ispc/ispc#706]
Our benchmark "mandelbrot_tasks" prints
"A total of 131072 tasks have been launched from the current function--the simple built-in task system can handle no more. You can increase the values of TASK_QUEUE_CHUNK_SIZE and LOG_TASK_QUEUE_CHUNK_SIZE to work around this limitation.  Sorry!  Exiting."
and exits. It happens because now it has 3d tasking logic when we launched (width/span) \* (height/span) tasks and this is more than 131072.

We should change logic of division into tasks or increase number of tasks in queue.

**Comment by aneshlya** [comment]
Not reproducible anymore.
