### ISSUE TITLE
reduce_equal cause fatal error when result assigned to uniform bool

### ISSUE THREAD

**Issue by gacteon** [ispc/ispc#722]
This cause compilation error: 

```
unsigned int32 key_1 = ...;
uniform unsigned int32 u_key_1;
uniform bool is_u_key_1 = reduce_equal(key_1, &u_key_1);
```

FATAL error : Unhandled signal sent to process; terminating.

If remove uniform from bool is_u_key_1 like this:

```
unsigned int32 key_1 = ...;
uniform unsigned int32 u_key_1;
bool is_u_key_1 = reduce_equal(key_1, &u_key_1);
```

All will be compiled without errors.

Compilation is performed on Windows with Intel(r) SPMD Program Compiler (ispc), 1.6.0 (build  @ Dec 19 2013, LLVM 3.4).

**Comment by nurmukhametov** [comment]
Fixed since at least 1.9.1. Test is added by #2636
