### ISSUE TITLE
error: expr.cpp:4076: Assertion failed: "ptrType != NULL"

### ISSUE THREAD

**Issue by goldfeldjg** [ispc/ispc#750]
Hi, as requested, I'm leaving a description of the error:
the line that causes this is:

v64 = (&((int64*)(bTbase)))[i];

where the respective types are:
v64:          varying int64
bTbase:    uniform int32\* uniform
i:               const varying int32      (a "foreach" loop identifier)

Cheers,
Jonathan

**Comment by nurmukhametov** [comment]
Fixed since at least 1.9.1. Test is added by #2636
