### ISSUE TITLE
extern "C" void exit(uniform int) produces unsigned int declaration for generic target

### ISSUE THREAD

**Issue by svenwoop** [ispc/ispc#790]
The code 
  extern "C" void exit(uniform int); 
produces 
  extern "C" { void exit(uint32_t ); }
for the generic target output. The generated declaration should be  
  extern "C" { void exit(int32_t ); }

**Comment by aneshlya** [comment]
This issue is related to generic targets that were removed in v1.12.0 so I'm closing it as not planned.
