### ISSUE TITLE
Error: Assertion failed (ctx.cpp:2335): "m->errorCount > 0". 

### ISSUE THREAD

**Issue by ingowald** [ispc/ispc#792]
Attached 'bug.ispc' produces
Error: Assertion failed (ctx.cpp:2335): "m->errorCount > 0". 
Compile with ./ispc bug.ispc, happens with both ToT and ispc 1.7 binary.

**Comment by aneshlya** [comment]
The reproducer is not accessible anymore. Closing the issue.
