### ISSUE TITLE
Preprocessor failure does not terminate

### ISSUE THREAD

**Issue by mattwalsh** [ispc/ispc#800]
Consider this program; it is compile-able save for the extraneous #endif.

```
export void J(
    uniform float a[],
    uniform float b[],
    uniform int N) {

}

#endif
```

If I compile this with ispc (ispc testcase.ispc -o testcase.o) I get this output...

```
testcase.ispc:9:2: error: #endif without #if
#endif
```

this is a valid error.  However, this error does not stop compilation.  In fact a .o file is generated and the return code ($?) is zero.

I believe this should error out, not even try to produce the .o file and return an error to the shell.

**Comment by dbabokin** [comment]
Fixed by #2280
