### ISSUE TITLE
Crash when using logic operators on bool<X>

### ISSUE THREAD

**Issue by jrouwe** [ispc/ispc#882]
This code:

void main()
{
    bool&lt;3&gt; a;
    bool&lt;3&gt; b;
    a && b;
}

will trigger an assertion (and then crash ispc):

test.ispc:5:2: Error: Assertion failed (ctx.cpp:1776): "v0->getType() == v1->getType()".
        a && b;

I would expect a && b == { a.x && b.x, a.y && b.y, a.z && b.z }.

The same holds for the || operator.

**Comment by nurmukhametov** [comment]
Fixed since 1.14.0. Test is added by #2636
