### ISSUE TITLE
ISPC 1.8.0 Windows binary crashes with --cpu=core2 --target=sse4-x2 on round function use

### ISSUE THREAD

**Issue by nnevatie** [ispc/ispc#905]
`echo export void crash(float input[], float output[]) {output[0] = round(input[0]);} | ispc.exe -o round.obj --cpu=core2 --target=sse4-x2`

Error message:
`LLVM ERROR: Cannot select: intrinsic %llvm.x86.sse41.round.ps`

This does not crash with the previous version of ISPC.

**Comment by nurmukhametov** [comment]
Fixed since at least 1.9.1. Test is added by #2636
