### ISSUE TITLE
Adding debug symbols causes compiler to be terminated

### ISSUE THREAD

**Issue by radomik** [ispc/ispc#952]
Trying to compile code:
<a href="https://www.dropbox.com/s/i7qqjzyz55ijccn/quat.ispc?dl=0">https://www.dropbox.com/s/i7qqjzyz55ijccn/quat.ispc?dl=0</a>

With command:
<code>
ispc -O2 -g --arch=x86-64 --target=sse4-i32x4 quat.ispc -o quat_ispc.o -h quat_ispc.h</code>

Produces:
<code>
main.cpp(226): FATAL ERROR: Unhandled signal sent to process; terminating.</code>

The same works great without <b>-g</b> flag.

Info:
Intel(r) SPMD Program Compiler (ispc), 1.8.0 (build no_version_info @ 20141221, LLVM 3.5)
System: Linux Gentoo x64, 
CPU: Intel Core 2 Duo T9300 (SSE2 and SSE4)
LLVM version 3.5.0

**Comment by aguskov** [comment]
Have you tried this version of ISPC?
http://sourceforge.net/projects/ispcmirror/files/v1.8.1/ispc-v1.8.1-linux.tar.gz/download
Intel(r) SPMD Program Compiler (ispc), 1.8.1 (build commit c2016af1623c535a @ 20141231, LLVM 3.5)
It seems to be working fine.

**Comment by nurmukhametov** [comment]
The link to the test case is not available.
