### ISSUE TITLE
Assertion failed: "(bitSize % 8) == 0".

### ISSUE THREAD

**Issue by caughtbyatoe** [ispc/ispc#957]
The following code generates a compiler assertion:

print("sizeof(uniform bool) = %\n", sizeof(uniform bool));

ispc.cpp:1003: Assertion failed: "(bitSize % 8) == 0".
***
*** Please file a bug report at https://github.com/ispc/ispc/issues
*** (Including as much information as you can about how to reproduce this error).
*** You have apparently encountered a bug in the compiler that we'd like to fix!
***
main.cpp(225): FATAL ERROR: Unhandled signal sent to process; terminating.

I've tested under 1.8.1 and 1.6

**Comment by lashgar** [comment]
Any workaround or update on this issue? The very same issue exists in 1.8.2.

**Comment by dbabokin** [comment]
Fixed by #1100
